AVG(gpu_clk),
MIN(gpu_clk),
MAX(gpu_clk),     
AVG(gpu_clkr),
MIN(gpu_clkr),
MAX(gpu_clkr),   
AVG(gpu_memf),
MIN(gpu_memf),
MAX(gpu_memf),   
AVG(gpu_memt),
MIN(gpu_memt),
MAX(gpu_memt),   
AVG(gpu_memu),
MIN(gpu_memu),
MAX(gpu_memu),   
AVG(gpu_memur),
MIN(gpu_memur),
MAX(gpu_memur),  
AVG(gpu_pu),
MIN(gpu_pu),
MAX(gpu_pu),     
AVG(gpu_sclk),
MIN(gpu_sclk),
MAX(gpu_sclk),   
AVG(gpu_temp),
MIN(gpu_temp),
MAX(gpu_temp),   
AVG(gpu_util),
MIN(gpu_util),
MAX(gpu_util),  
AVG(gpu_pcie_tx),
MIN(gpu_pcie_tx),
MAX(gpu_pcie_tx),
AVG(gpu_pcie_rx),
MIN(gpu_pcie_rx),
MAX(gpu_pcie_rx),
AVG(gpu_nvlink_tx),
MIN(gpu_nvlink_tx),
MAX(gpu_nvlink_tx),
AVG(gpu_nvlink_rx),
MIN(gpu_nvlink_rx),
MAX(gpu_nvlink_rx),
AVG(gpu_active),
MIN(gpu_active),
MAX(gpu_active),
COUNT(gpuid)