gpu_clk_avg,
gpu_clk_min,
gpu_clk_max,
gpu_clkr_avg,
gpu_clkr_min,
gpu_clkr_max,
gpu_memf_avg,
gpu_memf_min,
gpu_memf_max,
gpu_memt_avg,
gpu_memt_min,
gpu_memt_max,
gpu_memu_avg,
gpu_memu_min,
gpu_memu_max,
gpu_memur_avg,
gpu_memur_min,
gpu_memur_max,
gpu_pu_avg,
gpu_pu_min,
gpu_pu_max,
gpu_sclk_avg,
gpu_sclk_min,
gpu_sclk_max,
gpu_temp_avg,
gpu_temp_min,
gpu_temp_max,
gpu_util_avg,
gpu_util_min,
gpu_util_max,
gpu_pcie_tx_avg,
gpu_pcie_tx_min,
gpu_pcie_tx_max,
gpu_pcie_rx_avg,
gpu_pcie_rx_min,
gpu_pcie_rx_max,
gpu_nvlink_tx_avg,
gpu_nvlink_tx_min,
gpu_nvlink_tx_max,
gpu_nvlink_rx_avg,
gpu_nvlink_rx_min,
gpu_nvlink_rx_max,
gpu_active_avg,
gpu_active_min,
gpu_active_max,
gpu_numgpus
