AVG(gpu_clk_avg),
MIN(gpu_clk_min),
MAX(gpu_clk_max),
AVG(gpu_clkr_avg),
MIN(gpu_clkr_min),
MAX(gpu_clkr_max),
AVG(gpu_memf_avg),
MIN(gpu_memf_min),
MAX(gpu_memf_max),
AVG(gpu_memt_avg),
MIN(gpu_memt_min),
MAX(gpu_memt_max),
AVG(gpu_memu_avg),
MIN(gpu_memu_min),
MAX(gpu_memu_max),
AVG(gpu_memur_avg),
MIN(gpu_memur_min),
MAX(gpu_memur_max),
AVG(gpu_pu_avg),
MIN(gpu_pu_min),
MAX(gpu_pu_max),
AVG(gpu_sclk_avg),
MIN(gpu_sclk_min),
MAX(gpu_sclk_max),
AVG(gpu_temp_avg),
MIN(gpu_temp_min),
MAX(gpu_temp_max),
AVG(gpu_util_avg),
MIN(gpu_util_min),
MAX(gpu_util_max),
AVG(gpu_pcie_tx_avg),
MIN(gpu_pcie_tx_min),
MAX(gpu_pcie_tx_max),
AVG(gpu_pcie_rx_avg),
MIN(gpu_pcie_rx_min),
MAX(gpu_pcie_rx_max),
AVG(gpu_nvlink_tx_avg),
MIN(gpu_nvlink_tx_min),
MAX(gpu_nvlink_tx_max),
AVG(gpu_nvlink_rx_avg),
MIN(gpu_nvlink_rx_min),
MAX(gpu_nvlink_rx_max),
AVG(gpu_active_avg),
MIN(gpu_active_min),
MAX(gpu_active_max),
MAX(gpu_numgpus)
