- { name: gpu_clk_avg,          type: clk_t }
- { name: gpu_clk_min,          type: clk_t }
- { name: gpu_clk_max,          type: clk_t }
- { name: gpu_clkr_avg,         type: clkr_t }
- { name: gpu_clkr_min,         type: clkr_t }
- { name: gpu_clkr_max,         type: clkr_t }
- { name: gpu_memf_avg,         type: mem_t }
- { name: gpu_memf_min,         type: mem_t }
- { name: gpu_memf_max,         type: mem_t }
- { name: gpu_memt_avg,         type: mem_t }
- { name: gpu_memt_min,         type: mem_t }
- { name: gpu_memt_max,         type: mem_t }
- { name: gpu_memu_avg,         type: mem_t }
- { name: gpu_memu_min,         type: mem_t }
- { name: gpu_memu_max,         type: mem_t }
- { name: gpu_memur_avg,        type: rate_t }
- { name: gpu_memur_min,        type: rate_t }
- { name: gpu_memur_max,        type: rate_t }
- { name: gpu_pu_avg,           type: power_t }
- { name: gpu_pu_min,           type: power_t }
- { name: gpu_pu_max,           type: power_t }
- { name: gpu_sclk_avg,         type: clk_t }
- { name: gpu_sclk_min,         type: clk_t }
- { name: gpu_sclk_max,         type: clk_t }
- { name: gpu_temp_avg,         type: temp_t }
- { name: gpu_temp_min,         type: temp_t }
- { name: gpu_temp_max,         type: temp_t }
- { name: gpu_util_avg,        type: rate_t }
- { name: gpu_util_min,        type: rate_t }
- { name: gpu_util_max,        type: rate_t }
- { name: gpu_pcie_tx_avg,      type: bytes_t }
- { name: gpu_pcie_tx_min,      type: bytes_t }
- { name: gpu_pcie_tx_max,      type: bytes_t }
- { name: gpu_pcie_rx_avg,      type: bytes_t }
- { name: gpu_pcie_rx_min,      type: bytes_t }
- { name: gpu_pcie_rx_max,      type: bytes_t }
- { name: gpu_nvlink_tx_avg,    type: bytes_t }
- { name: gpu_nvlink_tx_min,    type: bytes_t }
- { name: gpu_nvlink_tx_max,    type: bytes_t }
- { name: gpu_nvlink_rx_avg,    type: bytes_t }
- { name: gpu_nvlink_rx_min,    type: bytes_t }
- { name: gpu_nvlink_rx_max,    type: bytes_t }
- { name: gpu_active_avg,       type: float_t }
- { name: gpu_active_min,       type: float_t }
- { name: gpu_active_max,       type: float_t }
- { name: gpu_numgpus,          type: count_t }
