nodeerr:
  tables:
    - table:
        name: nodeerr
        options:
          update:
            LML: nodeerr
          update_trigger:
            - nodeerr_last
            - nodeerr_stat_by_node 
          archive:
            limit: max(nodeerrts)-21d
          index: nodeid,msgcls
        columns: 
          - { name: nodeid,          type: nodeid_t,          LML_from: node,            LML_default: 'unknown' }
          - { name: nodeerrts,       type: ts_t,              LML_from: timestamp,       LML_default: -1       ,  LML_minlastinsert: mintsinserted }
          - { name: jobid,           type: jobid_t,           LML_from: jobid,           LML_default: 'unknown' }
          - { name: cmd,             type: longstr_t,         LML_from: command,         LML_default: 'unknown' }
          - { name: pid,             type: pid_t,             LML_from: pid,             LML_default: 0 }
          - { name: user,            type: owner_t,           LML_from: username,        LML_default: 'unknown' }
          - { name: msgcls,          type: cnt_t,             LML_from: msgcls,          LML_default: 0 }
          - { name: msg,             type: extralongstr_t,    LML_from: msg,             LML_default: "" }
          - { name: uid,             type: pid_t,             LML_from: uid,             LML_default: 0 }
          - { name: gid,             type: pid_t,             LML_from: gid,             LML_default: 0 }

    - table:
        name: nodeerr_last
        options:
          update:
            sql_update_contents:
               vars: mintsinserted
               # 0. remove duplicates from nodeerr
               # 1. take over all new entries 
               # 2. compute number of entries/node         
               # 3. delete all old entries where more than 5 ts/node are stored        
               # 4. remove duplicates from nodeerr_last
               sql: 
                    DELETE FROM nodeerr WHERE rowid NOT IN (SELECT MIN(rowid) FROM nodeerr GROUP BY nodeid,nodeerrts,pid);
                    INSERT INTO nodeerr_last (nodeid,nodeerrts,jobid,cmd,pid,user,msgcls,msg,uid,gid)
                           SELECT nodeid,nodeerrts,jobid,cmd,pid,user,msgcls,msg,uid,gid
                           FROM nodeerr WHERE nodeerrts >= mintsinserted;
                    DELETE FROM nodeerr_last_stat;
                    INSERT INTO nodeerr_last_stat (nodeid,cnt,oldestts)
                           SELECT nodeid,count(*),min(nodeerrts)
                           FROM nodeerr_last GROUP BY nodeid;
                    DELETE FROM nodeerr_last WHERE rowid NOT IN (SELECT MIN(rowid) FROM nodeerr_last GROUP BY nodeid,nodeerrts,jobid,pid,user,msgcls,msg,pid,gid);
                    DELETE FROM nodeerr_last WHERE (nodeid||nodeerrts) IN (select nodeid||oldestts FROM nodeerr_last_stat WHERE cnt>5);
        columns: 
          - { name: nodeid,          type: nodeid_t }
          - { name: nodeerrts,       type: ts_t }
          - { name: jobid,           type: jobid_t }
          - { name: cmd,             type: longstr_t }
          - { name: pid,             type: pid_t }
          - { name: user,            type: owner_t }
          - { name: msgcls,          type: cnt_t } 
          - { name: msg,             type: extralongstr_t }
          - { name: uid,             type: pid_t }
          - { name: gid,             type: pid_t }


    - table:
        name: nodeerr_last_stat
        options:
        columns: 
          - { name: nodeid,          type: nodeid_t }
          - { name: cnt,             type: cnt_t } 
          - { name: oldestts,        type: ts_t }
          
          
    - table:
        name: nodeerr_stat_by_node 
        options:
          update:
            sql_update_contents:
               sql: DELETE FROM nodeerr_stat_by_node;
                    INSERT INTO nodeerr_stat_by_node (nodeid,msgcls,cnt)
                    SELECT nodeid,msgcls,count(*)
                    FROM nodeerr
                    GROUP BY nodeid,msgcls
        columns: 
          - { name: nodeid,          type: nodeid_t }
          - { name: msgcls,          type: cnt_t } 
          - { name: cnt,             type: cnt_t } 
          
