# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- table:
    name: loadmem_aggr_by_ts_feat_status
    options:
      update:
        sql_update_contents:
          vars: mintsinserted
          sql: DELETE FROM loadmem_aggr_by_ts_feat_status WHERE (ts >= mintsinserted);
               INSERT INTO loadmem_aggr_by_ts_feat_status
                                 (ts, fid, feat, status, substatus, count, load_avg, load_min,
                                  load_max, used_cores_avg, used_cores_min, used_cores_max,
                                  total_cores_avg, used_mem_avg, used_mem_min, used_mem_max,
                                  total_mem_avg)
                                              SELECT ts, feat||status||substatus, feat, status, substatus, count(*),
                                                     AVG(load),       MIN(load),       MAX(load),
                                                     AVG(used_cores), MIN(used_cores), MAX(used_cores), AVG(total_cores),
                                                     AVG(used_mem),   MIN(used_mem),   MAX(used_mem),   AVG(total_mem)
                                              FROM loadmem where (ts >= mintsinserted)
                                              GROUP by ts, feat, status, substatus;
               INSERT INTO loadmem_aggr_by_ts_feat_status
                                 (ts, fid, feat, status, substatus, count, load_avg, load_min,
                                  load_max, used_cores_avg, used_cores_min, used_cores_max,
                                  total_cores_avg, used_mem_avg, used_mem_min, used_mem_max,
                                  total_mem_avg)
                                              SELECT ts, feat||status||"ALL",  feat, status, "ALL", count(*),
                                                     AVG(load),       MIN(load),       MAX(load),
                                                     AVG(used_cores), MIN(used_cores), MAX(used_cores), AVG(total_cores),
                                                     AVG(used_mem),   MIN(used_mem),   MAX(used_mem),   AVG(total_mem)
                                              FROM loadmem where (ts >= mintsinserted)
                                              GROUP by ts, feat, status;
               INSERT INTO loadmem_aggr_by_ts_feat_status
                                 (ts, fid, feat, status, substatus, count, load_avg, load_min,
                                  load_max, used_cores_avg, used_cores_min, used_cores_max,
                                  total_cores_avg, used_mem_avg, used_mem_min, used_mem_max,
                                  total_mem_avg)
                                              SELECT ts, "ALL"||status||substatus, "ALL", status, substatus, count(*),
                                                     AVG(load),       MIN(load),       MAX(load),
                                                     AVG(used_cores), MIN(used_cores), MAX(used_cores), AVG(total_cores),
                                                     AVG(used_mem),   MIN(used_mem),   MAX(used_mem),   AVG(total_mem)
                                              FROM loadmem where (ts >= mintsinserted)
                                              GROUP by ts, status, substatus;
               INSERT INTO loadmem_aggr_by_ts_feat_status
                                 (ts, fid, feat, status, substatus, count, load_avg, load_min,
                                  load_max, used_cores_avg, used_cores_min, used_cores_max,
                                  total_cores_avg, used_mem_avg, used_mem_min, used_mem_max,
                                  total_mem_avg)
                                              SELECT ts, "ALL"||status||"ALL", "ALL", status, "ALL", count(*),
                                                     AVG(load),       MIN(load),       MAX(load),
                                                     AVG(used_cores), MIN(used_cores), MAX(used_cores), AVG(total_cores),
                                                     AVG(used_mem),   MIN(used_mem),   MAX(used_mem),   AVG(total_mem)
                                              FROM loadmem where (ts >= mintsinserted)
                                              GROUP by ts, status;
               INSERT INTO loadmem_aggr_by_ts_feat_status
                                 (ts, fid, feat, status, substatus, count, load_avg, load_min,
                                  load_max, used_cores_avg, used_cores_min, used_cores_max,
                                  total_cores_avg, used_mem_avg, used_mem_min, used_mem_max,
                                  total_mem_avg)
                                              SELECT ts, "ALL"||"ALL"||"ALL", "ALL", "ALL", "ALL", count(*),
                                                     AVG(load),       MIN(load),       MAX(load),
                                                     AVG(used_cores), MIN(used_cores), MAX(used_cores), AVG(total_cores),
                                                     AVG(used_mem),   MIN(used_mem),   MAX(used_mem),   AVG(total_mem)
                                              FROM loadmem where (ts >= mintsinserted)
                                              GROUP by ts;
               INSERT INTO loadmem_aggr_by_ts_feat_status
                                 (ts, fid, feat, status, substatus, count, load_avg, load_min,
                                  load_max, used_cores_avg, used_cores_min, used_cores_max,
                                  total_cores_avg, used_mem_avg, used_mem_min, used_mem_max,
                                  total_mem_avg)
                                              SELECT mintsinserted, feat||status||substatus, feat, status, substatus,0,
                                                     0,0,0,
                                                     0,0,0,0,
                                                     0,0,0,0
                                              FROM loadmem_aggr_by_ts_feat_status
                                              GROUP by feat,status,substatus
                                              HAVING feat||status||substatus
                                                     NOT IN (SELECT feat||status||substatus
                                                             FROM loadmem_aggr_by_ts_feat_status
                                                             WHERE (ts=mintsinserted)
                                                             )
      archive:
        limit: max(ts)-72h
      index: feat,status,substatus,ts
    columns: 
      - { name: ts,              type: ts_t }
      - { name: fid,             type: fid_t }
      - { name: feat,            type: feature_t }
      - { name: status,          type: status_t }
      - { name: substatus,       type: status_t }
      - { name: count,           type: count_t }
      - { name: load_avg,        type: load_t }
      - { name: load_min,        type: load_t }
      - { name: load_max,        type: load_t }
      - { name: used_cores_avg,  type: cores_f_t }
      - { name: used_cores_min,  type: cores_f_t }
      - { name: used_cores_max,  type: cores_f_t }
      - { name: total_cores_avg,  type: cores_f_t }
      - { name: used_mem_avg,    type: mem_f_t }
      - { name: used_mem_min,    type: mem_f_t }
      - { name: used_mem_max,    type: mem_f_t }
      - { name: total_mem_avg,   type: mem_f_t }

- table:
    name: loadmem_status_max_ts
    options:
      update:
        sql_update_contents:
          sql: DELETE FROM loadmem_status_max_ts;
               INSERT INTO loadmem_status_max_ts
                                 (fid, ts)
                                 SELECT fid,max(ts)
                                 FROM loadmem_aggr_by_ts_feat_status
                                 GROUP by fid;
    columns: 
      - { name: fid,             type: fid_t }
      - { name: ts,              type: ts_t }

      
- table:
    name: loadmem_by_ts_feat_status_last
    options:
      update:
        sql_update_contents:
          sql: DELETE FROM loadmem_by_ts_feat_status_last;
               INSERT INTO loadmem_by_ts_feat_status_last
                                 (ts, fid, feat, status, substatus,
                                  count, load_avg, load_min,
                                  load_max, used_cores_avg, used_cores_min, used_cores_max,
                                  total_cores_avg, used_mem_avg, used_mem_min, used_mem_max,
                                  total_mem_avg)
                                 SELECT A.ts, A.fid, A.feat, A.status, A.substatus,
                                  A.count, A.load_avg, A.load_min,
                                  A.load_max, A.used_cores_avg, A.used_cores_min, A.used_cores_max,
                                  A.total_cores_avg, A.used_mem_avg, A.used_mem_min, A.used_mem_max,
                                  A.total_mem_avg
                                 FROM loadmem_aggr_by_ts_feat_status A, loadmem_status_max_ts S
                                 WHERE A.fid=S.fid AND A.ts=S.ts;
    columns: 
      - { name: ts,              type: ts_t }
      - { name: fid,             type: fid_t }
      - { name: feat,            type: feature_t }
      - { name: status,          type: status_t }
      - { name: substatus,       type: status_t }
      - { name: count,           type: count_t }
      - { name: load_avg,        type: load_t }
      - { name: load_min,        type: load_t }
      - { name: load_max,        type: load_t }
      - { name: used_cores_avg,  type: cores_f_t }
      - { name: used_cores_min,  type: cores_f_t }
      - { name: used_cores_max,  type: cores_f_t }
      - { name: total_cores_avg,  type: cores_f_t }
      - { name: used_mem_avg,    type: mem_f_t }
      - { name: used_mem_min,    type: mem_f_t }
      - { name: used_mem_max,    type: mem_f_t }
      - { name: total_mem_avg,   type: mem_f_t }


- table:
    name: loadmem_time_aggr_feat_status
    options:
      update:
        sql_update_contents:
          sqldebug: 1
          vars: mintsinserted
          aggr_by_time_resolutions: [1, 60, 1440]     # in minutes (1 min, 1 hour, 1 day)
          aggr_by_time_mintsvar: mintsinserted
          sql: 
               INSERT INTO loadmem_time_aggr_feat_status
                           (_time_res, _time_cnt, ts, fid, count_avg)
                                 SELECT 1, 1,
                                        ts, fid, count
                                 FROM loadmem_aggr_by_ts_feat_status
                                 WHERE (ts >=  mintsinserted)
      archive:
        limit_aggr_time: [ 6120, 133920, 2628000 ]     # in minutes (3 days, 93 days, 5 years)
        limit_aggr_time_var: ts
    columns: 
      - { name: _time_res,       type: _time_res_t }
      - { name: _time_cnt,       type: _time_cnt_t }
      - { name: ts,              type: ts_t,      time_aggr: TS  }
      - { name: fid,             type: fid_t,     time_aggr: KEY  }
      - { name: count_avg,       type: count_f_t, time_aggr: AVG }
      
      
# Update tables: (fill new time_aggr table with data from old span tables)
# _time_res=1
# insert into loadmem_time_aggr_feat_status (_time_res,_time_cnt,ts,fid,count_avg) select 1,1,ts,fid,count from loadmem_aggr_by_ts_feat_status where ts<(select min(ts) from loadmem_time_aggr_feat_status where (_time_res=1));
# _time_res=60
# insert into loadmem_time_aggr_feat_status (_time_res,_time_cnt,ts,fid,count_avg) select 60,60,ts,fid,count_avg from loadmem_aggr_ts_feat_status_hourly where ts<=(select min(ts) from loadmem_time_aggr_feat_status where (_time_res=60));
# _time_res=1440
# insert into loadmem_time_aggr_feat_status (_time_res,_time_cnt,ts,fid,count_avg) select 1440,1440,ts,fid,count_avg from loadmem_aggr_ts_feat_status_daily where ts<=(select min(ts) from loadmem_time_aggr_feat_status where (_time_res=1440));
# Status:
# select _time_res,count(*),sum(_time_cnt),min(ts),max(ts),(max(ts)-min(ts))/60.0/60.0/24.0 from loadmem_time_aggr_feat_status where fid="ALLRuALL" group by _time_res;
