# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

JUWELS_BOOSTER:
  booster:
    cores: 48
    mem: 512
    memgpu: 40
  largebooster:
    cores: 48
    mem: 512
    memgpu: 40
  develbooster:
    cores: 48
    mem: 512
    memgpu: 40
  develbooster-sw:
    cores: 48
    mem: 512
    memgpu: 40
  maintbooster:
    cores: 48
    mem: 512
    memgpu: 40
