# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

archive:
  archive_data: yes
  remove_data: yes
options:
  parallel: yes
  parwaitsec: 40   # timeout in sec

vars:
 %include "./jobreport_vars.yaml"
    
directories:
 - { path: "$outputdir/projects, $outputdir/support, $outputdir/config, 
            $outputdir/_info, $outputdir/sec_files, $outputdir/mentors,
            $outputdir/_queued, $outputdir/_sysstat, $outputdir/llview_batch,  
            $outputdir/../tmp/data/, $outputdir/../tmp/data/sysstat, 
            $outputdir/LLtemplates, $outputdir/ll, 
            $outputdir/_internal, $outputdir/_internal/DBtab, 
            $outputdir/_internal/steptimings" }
 - {
     FORALL: 'P:VAR_project',
     path: '$outputdir/projects/$P'
   }
 - { 
     FORALL: 'P,U:VAR_project_user',
     path: '$outputdir/projects/$P/$U'
    }
 - {
     FORALL: 'M:VAR_mentor',
     path: '$outputdir/mentors/mentor_$M'
   }


datafiles:
 %include "./data_csv_dat/jobreport_datafiles_loadmem.yaml"
 %include "./data_csv_dat/jobreport_datafiles_fabric.yaml"
 %include "./data_csv_dat/jobreport_datafiles_fsusage.yaml"
 %include "./data_csv_dat/jobreport_datafiles_gpu.yaml"
 %include "./data_csv_dat/jobreport_datafiles_jobdata.yaml"
 %include "./data_json/jobreport_datafiles_json.yaml"
 %include "./data_json/jobreport_datafiles_json_jureptool.yaml"
 %include "./data_templates/jobreport_datafiles_table_templates.yaml"
 %include "./data_access/jobreport_datafiles_access.yaml"
 %include "./data_csv_dat/jobreport_datafiles_sysstat.yaml"
 %include "./data_csv_dat/jobreport_datafiles_internal.yaml"
 %include "./data_csv_dat/jobreport_datafiles_roles.yaml"
 %include "./data_csv_dat/jobreport_datafiles_projstat.yaml"
 %include "./data_csv_dat/jobreport_datafiles_jumonc.yaml"
#  %include "./data_csv_dat/jobreport_datafiles_export.yaml"

datamngt:
 - action:
     name: compress_finished_files
     type: compress
     options:
       parallel_level: 12
       limit: 25h
       max_files: 50
       # gzip, xz (not for web server)
       compress_tool: gzip
       
 - action:
     name: archive_jobs_files
     type: archive
     options:
       parallel_level: 12
       dirtype: perday
       tarfileprefix: JOB_
       limit: 21d
       %include "./jobreport_archive_extra_limits.yaml"
       max_files: 2000
       tmptardir: '/tmp/jobreport_archive_jobs_files'
    
footerfiles:
 %include "./jobreport_footer.yaml"

graphpages:
 %include "./graphpages/jobreport_graphpage_SYSTEM.yaml"
 %include "./graphpages/jobreport_graphpage_internalstat.yaml"
 %include "./graphpages/jobreport_graphpage_internaltransfer.yaml"
 %include "./graphpages/jobreport_graphpage_sysoverview.yaml"
 %include "./graphpages/jobreport_graphpage_sysstatistics.yaml"
 %include "./graphpages/jobreport_graphpage_syspower.yaml"
 %include "./graphpages/jobreport_graphpage_sysio.yaml"
 %include "./graphpages/jobreport_graphpage_sysinterconnect.yaml"
 %include "./graphpages/jobreport_graphpage_environment.yaml"
 %include "./graphpages/jobreport_graphpage_steptimelines.yaml"
 
views:
 %include "./views/jobreport_view_support.yaml"
 %include "./views/jobreport_view_mentor.yaml"
 %include "./views/jobreport_view_project.yaml"
 %include "./views/jobreport_view_user.yaml"
