# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

########
# Footer
########
- footer:
    name:          "CPU_GPU"
    filepath:      "$outputdir/ll/footer_CPU_GPU.json"
    footerset:
       %include "./footers/jobreport_footer_loadmem.yaml"
    #    %include "./footers/jobreport_footer_cpuusage.yaml"
    #    %include "./footers/jobreport_footer_cpucores.yaml"
    #    %include "./footers/jobreport_footer_memory.yaml"
    #    %include "./footers/jobreport_footer_gpu.yaml"
    #    %include "./footers/jobreport_footer_fabric.yaml"
    #    %include "./footers/jobreport_footer_fs.yaml"

- footer:
    name:          "sysstat"
    filepath:      "$outputdir/ll/footer_sysstat.json"
    footerset:
       %include "./footers/jobreport_footer_sysstat.yaml"

- footer:
    name:          "sysrackpwr"
    filepath:      "$outputdir/ll/footer_sysrackpwr.json"
    footerset:
       %include "./footers/jobreport_footer_sysrackpwr.yaml"

- footer:
    name:          "queuedjobs"
    filepath:      "$outputdir/ll/footer_queuedjobs.json"
    footerset:
       %include "./footers/jobreport_footer_queuedjobs.yaml"

- footer:
    name:          "DBstat"
    filepath:      "$outputdir/ll/footer_DBstat.json"
    footerset:
       %include "./footers/jobreport_footer_DBstat.yaml"

- footer:
    name:          "DBgraph"
    filepath:      "$outputdir/ll/footer_DBgraph.json"
    footerset:
       %include "./footers/jobreport_footer_DBgraph.yaml"

- footer:
    name:          "steptimings"
    filepath:      "$outputdir/ll/footer_steptimings.json"
    footerset:
       %include "./footers/jobreport_footer_steptimings.yaml"

- footer:
    name:          "projstat"
    filepath:      "$outputdir/ll/footer_projstat.json"
    footerset:
       %include "./footers/jobreport_footer_projstat.yaml"

# - footer:
#     name:          "corepattern"
#     filepath:      "$outputdir/ll/footer_corepattern.json"
#     footerset:
#        %include "./footers/jobreport_footer_corepattern.yaml"

- footer:
    name:          "memheatmap"
    filepath:      "$outputdir/ll/footer_memheatmap.json"
    footerset:
       %include "./footers/jobreport_footer_memheatmap.yaml"