# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- {
    name: VAR_project,
    type: 'hash_values',    
    database: accountmap,
    table: allprojects,
    columns: 'project'
  }
- {
    name: VAR_account_owner_running,
    type: 'hash_values',    
    database: jobreport,
    table: joblist_stat_by_account_owner_do_update,
    columns:  'account,owner',
    sql: "SELECT account,owner 
          FROM joblist_stat_by_account_owner_do_update WHERE timeframe = 0",
    defer: 1
  }
- {
    name: VAR_account_owner_today,
    type: 'hash_values',    
    database: jobreport,
    table: joblist_stat_by_account_owner_do_update,
    columns:  'account,owner',
    sql: "SELECT account,owner 
          FROM joblist_stat_by_account_owner_do_update WHERE timeframe = 1",
    defer: 1
  }
- {
    name: VAR_account_owner_threeweeks,
    type: 'hash_values',    
    database: jobreport,
    table: joblist_stat_by_account_owner_do_update,
    columns:  'account,owner',
    sql: "SELECT account,owner 
          FROM joblist_stat_by_account_owner_do_update WHERE timeframe = 2",
    defer: 1
  }
- {
    name: VAR_project_user,
    type: 'hash_values',    
    database: accountmap,
    table: usermap,
    columns:  'project,id'
  }
- {
    name: VAR_mentor,
    type: 'hash_values',    
    database: accountmap,
    table: mentorlist,
    columns: 'wsaccount'
  }
- {
    name: VAR_projectlist,
    type: 'hash_values',    
    database: jobreport,
    table: projstat_per_project_aggr,
    columns: 'account'
  }
- {
    name: VAR_project_user_job,
    type: 'hash_values',    
    database: jobreport,
    table: joblist,
    columns:  'account,owner,jobid',
    sql: "SELECT account,owner,jobid 
          FROM joblist 
          WHERE jobid IN (SELECT jobid FROM updatedjobs) and (ts>0) and (account!='root') and (account!='deepest-admin')"
  }
- {
    name: VAR_project_user_job_jumonc,
    type: 'hash_values',    
    database: jobreport,
    table: joblist,
    columns:  'account,owner,jobid',
    sql: "SELECT account,owner,jobid 
          FROM joblist 
          WHERE jobid IN (SELECT jobid FROM updatedjobs) and (ts>0) and (account!='root') and (account!='deepest-admin') and (jmc_numvars>0)"
  }
- {
    name: VAR_project_user_job_all,
    type: 'hash_values',    
    database: jobreport,
    table: joblist,
    columns:  'account,owner,jobid',
    sql: "SELECT account,owner,jobid 
          FROM joblist WHERE owner != 'unknown'"
  }
- {
    name: VAR_project_user_queuedjobs_current,
    type: 'hash_values',    
    database: jobstate,
    table: currentjobs_deferred_by_owner_account,
    columns:  'account,owner,jobid',
    sql: "SELECT account,owner,jobid 
          FROM currentjobs_deferred_by_owner_account WHERE owner != 'unknown'"
  }
- {
    name: VAR_sysstat_feature_status,
    type: 'hash_values',       
    database: loadmemstate,
    table: loadmem_by_ts_feat_status_last,
    columns:  'fid',
    sql: "SELECT distinct fid 
          FROM loadmem_by_ts_feat_status_last"
  }
- {
    name: VAR_sysstat_feature_status_only_all,
    type: 'hash_values',       
    database: loadmemstate,
    table: loadmem_by_ts_feat_status_last,
    columns:  'fid',
    sql: "SELECT distinct fid 
          FROM loadmem_by_ts_feat_status_last
          WHERE feat='ALL' AND substatus='ALL'"
  }
- {
    name: VAR_queuestat_queues,
    type: 'hash_values',       
    database: jobstate,
    table: stat_by_queue_ts,
    columns:  'queue',
    sql: "SELECT distinct queue 
          FROM stat_by_queue_ts"
  }
- {
    name: VAR_sysenvstat_system,
    type: 'hash_values',       
    database: sysstatstate,
    table: sysstat_last,
    columns:  'sysname',
    sql: "SELECT distinct sysname 
          FROM sysstat_last"
  }
- {
    name: VAR_sysrackpwr_system,
    type: 'hash_values',       
    database: sysstatstate,
    table: rackpwr_last,
    columns:  'name',
    sql: "SELECT distinct name 
          FROM rackpwr_last"
  }
- {
    name: VAR_support,
    type: 'hash_values',       # VAR_project_user_job->{$project}->{$user}->{$jobid}
    database: accountmap,
    table: supportmap,
    columns:  'wsaccount',
    sql: "SELECT wsaccount FROM supportmap"
  }
- {
    name: VAR_DB_table,
    type: 'hash_values',       
    database: DBstat,
    table: LMLDBstatcurrent,
    columns:  'tabpath',
    sql: "SELECT tabpath FROM LMLDBstatcurrent"
  }

- {
    name: VAR_WFstep,
    type: 'hash_values',       
    database: steptimings,
    table: steptimingscurrent,
    columns:  'id',
    sql: "SELECT id FROM steptimingscurrent"
  }

- {
    name: VAR_WF,
    type: 'hash_values',       
    database: steptimings,
    table: steptimingscurrent,
    columns:  'wf_name',
    sql: "SELECT wf_name FROM steptimingscurrent"
  }
  
  
- {
    name: VAR_transfer,
    type: 'hash_values',       
    database: transfer,
    table: transfer,
    columns:  'ts_name',
    sql: "SELECT distinct ts_name FROM transfer"
  }

- {
    name: VAR_hist_memcls,
    type: 'hash_values',       
    database: loadmemstate,
    table: loadmem_heatmap_node_mem_cls,
    columns:  'memcls',
    sql: "SELECT distinct memcls FROM loadmem_heatmap_node_mem_cls"
  }

- {
    name: VAR_corepattern,
    type: 'hash_values',       
    database: pcpucoresstate,
    table: pcpucores_current_pattern,
    columns:  'pid',
    sql: "SELECT p.pid FROM pcpucores_current_pattern c, pcpucores_time_aggr_span_avg p WHERE c.pattern=p.pattern"
#    sql: "SELECT distinct p.pid FROM pcpucores_time_aggr_span_avg p"
  }
