# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

_x:
  header: 'ts'
  type: 'int32'
_y:
  header: 'nodeid'
  type: 'str'
  name: 'Node'
_overview:
  left:
    _label: 'Avg. CPU Usage (%)'
    _range: [0,100]
    plots:
      - Node: 
        - 'CPU Usage'
  right:
    _label: 'Avg. GPU Active SM (%)'
    _range: [0,100]
    plots:
      - GH200: 
        - 'GPU Active SM'
Cores:
  _file_header: 'coreusagenodefile'
  _datapoints_header: 'cores_ndps'
  Cores Usage:
    _x: 
      header: 'coreid'
      type: 'int16'
      name: 'Core ID'
    header: 'usage1_avg'
    type: 'float16'
    unit: '%'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,100]
    description: 'Average core usage along the runtime of the job (max. 100%)'
#  Logical Cores Usage:
#    _x: 
#      header: 'coreid'
#      type: 'int16'
#      name: 'Core ID'
#    header: 'usage2_avg'
#    type: 'float16'
#    unit: '%'
#    log: False
#    note: ''
#    cmap: 'cmc.hawaii'
#    lim: [0,100]
#    description: 'Average logical core usage along the runtime of the job (max. 100%)'

Node:
  _file_header: 'loadmemnodefile'
  _datapoints_header: 'ld_ndps'
  _max_graph_per_page: 3
  CPU Usage:
    header: 'usage'
    type: 'float16'
    unit: '%'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,100]
    description: 'Average core usage among all cores in the nodes (max. 100%)'
  Number of Cores Used:
    header: 'used_cores_phys'
    type: 'int16'
    unit: 'cores'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,'cores']
    description: 'Number of cores with usage >25%'
#  Number of Logical Cores Used:
#    header: 'used_cores_logic'
#    type: 'int16'
#    unit: 'cores'
#    log: False
#    note: ''
#    cmap: 'cmc.hawaii'
#    lim: [0,'cores']
#    description: 'Number of logical cores with usage >25%'
  Load:
    header: 'load'
    type: 'float16'
    unit: ''
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,'cores']
    description: '1-min CPU load average'
  Memory Usage:
    header: 'used_mem'
    type: 'float32'
    unit: 'GiB'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,'mem']
    description: 'Amount of allocated RAM memory (in GiB) in the node'
  Current Power:
    _file_header: 'pwrnodefile'
    _datapoints_header: 'pwr_nd_ndps'
    header: 'power'
    type: 'float32'
    unit: 'W'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: False
    skip_when_all: 0.0
    description: 'Current power (in Watts) used in the whole node'
GH200:
  _file_header: 'gpunodefile'
  _datapoints_header: 'gpu_ndps'
  _fill_with: 0.0
  _gpu: true
  _y:
    name: 'Socket'
  GPU Active SM:
    header: 'gpu_active'
    type: 'float16'
    unit: '%'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,100]
    description: 'Percentage of time at least one warp was active on a GPU multiprocessor, averaged over all multiprocessors.'
  GPU Utilization: 
    header: 'gpu_util'
    type: 'float16'
    unit: '%'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,100]
    description: 'Percent of time over the past sample period during which one or more kernels was executing on the GPU'
  GPU Memory Usage: 
    header: 'gpu_memu'
    type: 'float32'
    unit: 'GiB'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,'memgpu']
    description: 'Amount of memory (in GiB) used on the GPU'
  GPU Temperature: 
    header: 'gpu_temp'
    type: 'float32'
    unit: '°C'
    log: False
    note: ''
    cmap: 'cmc.lajolla_r'
    lim: [40,83]
    description: 'Current Temperature (in Celsius) on the GPU'
  GPU Clk Throttle Reason:
    header: 'gpu_clkr'  
    type: 'int16'  
    unit: '#'  
    log: 2  
    note: "1:GpuIdle / 2:AppClkSet\n4:SwPwrCap / 8:HWSlowDown\n16:SyncBoost\n32:SwThermSlDwn\n64:HwThermSlDwn\n128:PwrBrakeSlDwn"  
    cmap: 'cmc.hawaii'
    lim: False  
    skip_when_all: NaN
    description: 'Information about factors that are reducing the frequency of GPU clocks'
  GPU StreamMP Clk:
    header: 'gpu_sclk'  
    type: 'float32'  
    unit: 'MHz'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Current frequency in MHz of the GPU SM (Streaming Multiprocessor) clock'
  GPU Memory Usage Rate:
    header: 'gpu_memur'  
    type: 'float32'  
    unit: '%'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: [0,100]  
    description: 'Percent of time over the past sample period during which GPU memory was being read or written'
  GPU Memory Clk:
    header: 'gpu_clk'  
    type: 'float32'  
    unit: 'MHz'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Current frequency of the GPU memory clock, in MHz'
  CPU Power: 
    _file_header: 'pwrchipfile'
    _datapoints_header: 'pwr_ch_ndps'
    _y:
      header: 'chipid'
    header: 'cpupower'
    type: 'float32'
    unit: 'W'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim:  False
    description: 'Power usage (in Watts) for the Grace unit including CPU, Memory and System IO'
  CPU Power Cap: 
    _file_header: 'pwrchipfile'
    _datapoints_header: 'pwr_ch_ndps'
    _y:
      header: 'chipid'
    header: 'cpupowercap'
    type: 'float32'
    unit: 'W'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim:  False
    skip_when_all: 100.0
    description: 'Power cap (in Watts) for the Grace unit including CPU, Memory and System IO'
  GPU Power: 
    _file_header: 'pwrchipfile'
    _datapoints_header: 'pwr_ch_ndps'
    _y:
      header: 'chipid'
    header: 'gpu_pu'
    type: 'float32'
    unit: 'W'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim:  False
    description: 'Power usage (in Watts) for the Hopper GPU and its associated circuitry (e.g. memory)'
  Superchip Power: 
    _file_header: 'pwrchipfile'
    _datapoints_header: 'pwr_ch_ndps'
    _y:
      header: 'chipid'
    header: 'power'
    type: 'float32'
    unit: 'W'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim:  False
    description: 'Power usage (in Watts) for the whole Grace-Hopper unit'
  PCIe TX:
    header: 'gpu_pcie_tx'  
    type: 'float32'  
    unit: 'GiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'The rate of data transmitted over the PCIe bus in GiB/s'
  PCIe RX:
    header: 'gpu_pcie_rx'  
    type: 'float32'  
    unit: 'GiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'The rate of data received over the PCIe bus in GiB/s'
  NVLink TX:
    header: 'gpu_nvlink_tx'
    type: 'float32'
    unit: 'GiB/s'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: False
    description: 'The rate of data transmitted over NVLink in in GiB/s'
  NVLink RX:
    header: 'gpu_nvlink_rx'
    type: 'float32'
    unit: 'GiB/s'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: False
    description: 'The rate of data received over NVLink in GiB/s'

File System \$HOME:
  _file_header: 'fshomenodefile'  
  _datapoints_header: 'fs_home_ndps'  
  _fill_with: 0.0
  Read: 
    header: 'MbrR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average read data rate (in MiB/s) in the last minute'
  Write:
    header: 'MbwR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average write data rate (in MiB/s) in the last minute'
  Open/Close Operations:
    header: 'ocR'  
    type: 'float32'  
    unit: 'op./s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average operation rate (in operations/s) in the last minute'

File System \$PROJECT:
  _file_header: 'fsprojectnodefile'  
  _datapoints_header: 'fs_project_ndps'  
  _fill_with: 0.0
  Read: 
    header: 'MbrR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average read data rate (in MiB/s) in the last minute'
  Write:
    header: 'MbwR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average write data rate (in MiB/s) in the last minute'
  Open/Close Operations:
    header: 'ocR'  
    type: 'float32'  
    unit: 'op./s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average operation rate (in operations/s) in the last minute'

File System \$SCRATCH:
  _file_header: 'fsscratchnodefile'  
  _datapoints_header: 'fs_scratch_ndps'  
  _fill_with: 0.0
  Read: 
    header: 'MbrR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average read data rate (in MiB/s) in the last minute'
  Write:
    header: 'MbwR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average write data rate (in MiB/s) in the last minute'
  Open/Close Operations:
    header: 'ocR'  
    type: 'float32'  
    unit: 'op./s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average operation rate (in operations/s) in the last minute'

File System \$DATA:
  _file_header: 'fsfastdatanodefile'  
  _datapoints_header: 'fs_fastdata_ndps'  
  _fill_with: 0.0
  Read: 
    header: 'MbrR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average read data rate (in MiB/s) in the last minute'
  Write:
    header: 'MbwR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average write data rate (in MiB/s) in the last minute'
  Open/Close Operations:
    header: 'ocR'  
    type: 'float32'  
    unit: 'op./s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average operation rate (in operations/s) in the last minute'

Interconnect:
  _file_header: 'fabricnodefile'  
  _datapoints_header: 'fa_ndps'  
  _fill_with: 0.0
  Data Input: 
    header: 'mbin'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average data input throughput (in MiB/s) in the last minute'
  Data Output: 
    header: 'mbout'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average data output throughput (in MiB/s) in the last minute'
  Packet Input:
    header: 'pckin'  
    type: 'float32'  
    unit: 'pkt/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average package input throughput (in pkt/s) in the last minute'
  Packet Output:
    header: 'pckout'  
    type: 'float32'  
    unit: 'pkt/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average package output throughput (in pkt/s) in the last minute'

User:
  _file_header: 'jmcfile'  
  _datapoints_header: 'jmc_ndps' 
  _section: 'jmc'  
  
