joberr:
  tables:
    - table:
        name: joberr
        options:
          update:
            LML: joberr
          archive:
            limit: max(errmsgts)-21d
        columns: 
          - { name: jobid,           type: jobid_t,           LML_from: jobid,           LML_default: 'unknown' }
          - { name: errmsgts,        type: ts_t,              LML_from: ts,              LML_default: -1        }
          - { name: nummsgs,         type: tasks_t,           LML_from: nummsgs,         LML_default: 0 }
          - { name: numnodes,        type: tasks_t,           LML_from: numnodes,        LML_default: 0 }
          - { name: errmsgnodes,     type: extralongstr_t,    LML_from: errmsgnodes,     LML_default: "" }
          - { name: errmsgs,         type: extralongstr_t,    LML_from: errmsgs,         LML_default: "" }

          
    # additional common tables jobmapts, jobmapnode 
    %include "../conf_common/jobmap_tables.yaml"

          
