# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

        - { name: jobid,           display_group: default }
        - { name: ts,              display_group: default }
        - { name: owner,           display_group: default }
        - { name: jgroup,          display_group: default }
        - { name: jstatus,         display_group: default }
        - { name: detailedstatus,  display_group: default }
        - { name: state,           display_group: default }
        - { name: wall,            display_group: default }
        - { name: wallsoft,        display_group: default }
        - { name: queuedate,       display_group: default }
        - { name: name,            display_group: default }
        - { name: comment,         display_group: default }
        - { name: totalcores,      display_group: default }
        - { name: totaltasks,      display_group: default }
        - { name: totalgpus,       display_group: default }
        - { name: queue,           display_group: default }
        - { name: dependency,      display_group: default }
        - { name: qos,             display_group: default }
        - { name: command,         display_group: default }
        - { name: classprio,       display_group: default }
        - { name: groupprio,       display_group: default }
        - { name: userprio,        display_group: default }
        - { name: sysprio,         display_group: default }
        - { name: favored,         display_group: default }
        - { name: restart,         display_group: default }
        - { name: account,         display_group: default }
        - { name: runtime,         display_group: default }
        - { name: starttime,       display_group: default }
        - { name: endtime,         display_group: default }
        - { name: numnodes,        display_group: default }
        - { name: reason,          display_group: default }
        - { name: ArrayJobId,      display_group: default }
        - { name: ArrayTaskId,     display_group: default }
        - { name: resid,           display_group: default }
        - { name: waittime,        display_group: default }
        - { name: timetostart,     display_group: default }
        - { name: posinqueue,      display_group: default }
        - { name: nsteps,          display_group: default }

        - { name: ts_start,        display_group: step }
        - { name: ts_end,          display_group: step }
        - { name: stepspec,        display_group: step }

        - { name: istatus_avg,     display_group: status }
        - { name: istatus_min,     display_group: status }
        - { name: istatus_max,     display_group: status }
        - { name: load_avg,        display_group: load }
        - { name: load_min,        display_group: load }
        - { name: load_max,        display_group: load }
        - { name: used_cores_avg,  display_group: load }
        - { name: used_cores_min,  display_group: load }
        - { name: used_cores_max,  display_group: load }
        - { name: used_mem_avg,    display_group: memory }  
        - { name: used_mem_min,    display_group: memory }  
        - { name: used_mem_max,    display_group: memory }  

        - { name: errmsgts,        display_group: errmsg }
        - { name: nummsgs,         display_group: errmsg }
        - { name: errmsgnodes,     display_group: errmsg }
        - { name: errmsgs,         display_group: errmsg }

        - { name: falastts,        display_group: fabric }
        - { name: mbin_avg,        display_group: fabric }
        - { name: mbin_min,        display_group: fabric }
        - { name: mbin_max,        display_group: fabric }
        - { name: mbout_avg,       display_group: fabric }
        - { name: mbout_min,       display_group: fabric }
        - { name: mbout_max,       display_group: fabric }
        - { name: pckin_avg,       display_group: fabric }
        - { name: pckin_min,       display_group: fabric }
        - { name: pckin_max,       display_group: fabric }
        - { name: pckout_avg,      display_group: fabric }
        - { name: pckout_min,      display_group: fabric }
        - { name: pckout_max,      display_group: fabric }

        - { name: fs_all_fslastts,        display_group: fsusage }
        - { name: fs_all_bw_avg,          display_group: fsusage }
        - { name: fs_all_bw_min,          display_group: fsusage }
        - { name: fs_all_bw_max,          display_group: fsusage }
        - { name: fs_all_br_avg,          display_group: fsusage }
        - { name: fs_all_br_min,          display_group: fsusage }
        - { name: fs_all_br_max,          display_group: fsusage }
        - { name: fs_all_ooc_avg,         display_group: fsusage }
        - { name: fs_all_ooc_min,         display_group: fsusage }
        - { name: fs_all_ooc_max,         display_group: fsusage }

        - { name: gpulastts,       display_group: gpu }
        - { name: istatus_avg,     display_group: gpu }
        - { name: istatus_min,     display_group: gpu }
        - { name: istatus_max,     display_group: gpu }
        - { name: gpu_eadm_d_sum,  display_group: gpu }
        - { name: gpu_eadm_s_sum,  display_group: gpu }
        - { name: gpu_eaom_d_sum,  display_group: gpu }
        - { name: gpu_eaom_s_sum,  display_group: gpu }
        - { name: gpu_evdm_d_sum,  display_group: gpu }
        - { name: gpu_evdm_s_sum,  display_group: gpu }
        - { name: gpu_evom_d_sum,  display_group: gpu }
        - { name: gpu_evom_s_sum,  display_group: gpu }
        - { name: gpu_clk_avg,     display_group: gpu }
        - { name: gpu_clk_min,     display_group: gpu }
        - { name: gpu_clk_max,     display_group: gpu }
        - { name: gpu_clkr_avg,    display_group: gpu }
        - { name: gpu_clkr_min,    display_group: gpu }
        - { name: gpu_clkr_max,    display_group: gpu }
        - { name: gpu_link_avg,    display_group: gpu }
        - { name: gpu_link_min,    display_group: gpu }
        - { name: gpu_link_max,    display_group: gpu }
        - { name: gpu_memf_avg,    display_group: gpu }
        - { name: gpu_memf_min,    display_group: gpu }
        - { name: gpu_memf_max,    display_group: gpu }
        - { name: gpu_memt_avg,    display_group: gpu }
        - { name: gpu_memt_min,    display_group: gpu }
        - { name: gpu_memt_max,    display_group: gpu }
        - { name: gpu_memu_avg,    display_group: gpu }
        - { name: gpu_memu_min,    display_group: gpu }
        - { name: gpu_memu_max,    display_group: gpu }
        - { name: gpu_memur_avg,   display_group: gpu }
        - { name: gpu_memur_min,   display_group: gpu }
        - { name: gpu_memur_max,   display_group: gpu }
        - { name: gpu_pciw_avg,    display_group: gpu }
        - { name: gpu_pciw_min,    display_group: gpu }
        - { name: gpu_pciw_max,    display_group: gpu }
        - { name: gpu_pfst_avg,    display_group: gpu }
        - { name: gpu_pfst_min,    display_group: gpu }
        - { name: gpu_pfst_max,    display_group: gpu }
        - { name: gpu_pu_avg,      display_group: gpu }
        - { name: gpu_pu_min,      display_group: gpu }
        - { name: gpu_pu_max,      display_group: gpu }
        - { name: gpu_rtp_d_avg,   display_group: gpu }
        - { name: gpu_rtp_d_min,   display_group: gpu }
        - { name: gpu_rtp_d_max,   display_group: gpu }
        - { name: gpu_rtp_s_avg,   display_group: gpu }
        - { name: gpu_rtp_s_min,   display_group: gpu }
        - { name: gpu_rtp_s_max,   display_group: gpu }
        - { name: gpu_rtpd_avg,    display_group: gpu }
        - { name: gpu_rtpd_min,    display_group: gpu }
        - { name: gpu_rtpd_max,    display_group: gpu }
        - { name: gpu_sclk_avg,    display_group: gpu }
        - { name: gpu_sclk_min,    display_group: gpu }
        - { name: gpu_sclk_max,    display_group: gpu }
        - { name: gpu_temp_avg,    display_group: gpu }
        - { name: gpu_temp_min,    display_group: gpu }
        - { name: gpu_temp_max,    display_group: gpu }
        - { name: gpu_usage_avg,   display_group: gpu }
        - { name: gpu_usage_min,   display_group: gpu }
        - { name: gpu_usage_max,   display_group: gpu }
        - { name: gpu_pcie_tx_avg, display_group: gpu }
        - { name: gpu_pcie_tx_min, display_group: gpu }
        - { name: gpu_pcie_tx_max, display_group: gpu }
        - { name: gpu_pcie_rx_avg, display_group: gpu }
        - { name: gpu_pcie_rx_min, display_group: gpu }
        - { name: gpu_pcie_rx_max, display_group: gpu }
