# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

columns: 'jobid, ts, owner, jgroup, jstatus, detailedstatus, state, wall,
         wallsoft, queuedate, name, comment, totalcores,
         totaltasks, totalgpus, queue, dependency, qos, command, classprio,
         groupprio, userprio, sysprio, favored, restart, account, runtime,
         starttime, endtime, numnodes, reason, ArrayJobId, ArrayTaskId, resid, waittime,
         timetostart, posinqueue, nsteps,
         ts_start, ts_end, stepspec,
         istatus_avg, istatus_min, istatus_max, load_avg, load_min, load_max,
         used_cores_avg, used_cores_min, used_cores_max, used_mem_avg,
         used_mem_min, used_mem_max,
         errmsgts, nummsgs, errmsgnodes, errmsgs,
         falastts, mbin_avg, mbin_min, mbin_max, mbout_avg, mbout_min,
         mbout_max, pckin_avg, pckin_min, pckin_max, pckout_avg, pckout_min,
         pckout_max,
         fs_all_fslastts, fs_all_bw_avg, fs_all_bw_min, fs_all_bw_max, fs_all_br_avg, fs_all_br_min, fs_all_br_max, fs_all_ooc_avg,
         fs_all_ooc_min, fs_all_ooc_max,
         gpulastts, istatus_avg, istatus_min, istatus_max, gpu_eadm_d_sum,
         gpu_eadm_s_sum, gpu_eaom_d_sum, gpu_eaom_s_sum, gpu_evdm_d_sum,
         gpu_evdm_s_sum, gpu_evom_d_sum, gpu_evom_s_sum, gpu_clk_avg,
         gpu_clk_min, gpu_clk_max, gpu_clkr_avg, gpu_clkr_min, gpu_clkr_max,
         gpu_link_avg, gpu_link_min, gpu_link_max, gpu_memf_avg, gpu_memf_min,
         gpu_memf_max, gpu_memt_avg, gpu_memt_min, gpu_memt_max, gpu_memu_avg,
         gpu_memu_min, gpu_memu_max, gpu_memur_avg, gpu_memur_min,
         gpu_memur_max, gpu_pciw_avg, gpu_pciw_min, gpu_pciw_max, gpu_pfst_avg,
         gpu_pfst_min, gpu_pfst_max, gpu_pu_avg, gpu_pu_min, gpu_pu_max,
         gpu_rtp_d_avg, gpu_rtp_d_min, gpu_rtp_d_max, gpu_rtp_s_avg,
         gpu_rtp_s_min, gpu_rtp_s_max, gpu_rtpd_avg, gpu_rtpd_min,
         gpu_rtpd_max, gpu_sclk_avg, gpu_sclk_min, gpu_sclk_max, gpu_temp_avg,
         gpu_temp_min, gpu_temp_max, gpu_usage_avg, gpu_usage_min,
         gpu_usage_max, gpu_pcie_tx_avg, gpu_pcie_tx_min, gpu_pcie_tx_max,
         gpu_pcie_rx_avg, gpu_pcie_rx_min, gpu_pcie_rx_max'
