# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

fabricstate:
  tables:
    # additional common tables jobmapts, jobmapnode 
    %include "../conf_common/jobmap_tables.yaml"
    %include "../conf_common/nodeinfo_tables.yaml"

    #---------------------------
    # table, filled by LML input
    #---------------------------
    - table:
        name: fabric
        options:
          update:
            LML: fbnode
            LLgenDB: set_node2nid(nodeid,nodeinfo,nodeid,nid)
            mode: add
          update_trigger:
            - fabric_jobmap_by_nd_minmaxts
            - fabric_aggr_by_ts
            - fabric_time_aggr_ts
            - node_update_status
            - fabric_aggr_by_node
            - fabric_current_jobid
            - fabric_by_jobid_nodeid_ts
            - fabric_aggr_by_jobid_ts
            - fabric_aggr_by_jobid
          archive:
            limit: max(ts)-25h
#          index: nodeid,ts
        columns: 
          - { name: nodeid,      type: nodeid_t,   LML_from: id,          LML_default: 'unknown' }
          - { name: ts,          type: ts_t,       LML_from: fb_ts,       LML_default: -1,  LML_minlastinsert: mintsinserted}
          - { name: mbin,        type: mb_t,       LML_from: fb_mbin,     LML_default: 0.0 }
          - { name: mbout,       type: mb_t,       LML_from: fb_mbout,    LML_default: 0.0 }
          - { name: pckin,       type: pck_t,      LML_from: fb_pckin,    LML_default: 0.0 }          
          - { name: pckout,      type: pck_t,      LML_from: fb_pckout,   LML_default: 0.0 }          


    #-------------------------------
    # tables, containing per ts info
    #-------------------------------
    - table:
        name: fabric_aggr_by_ts
        options:
          update:
            sql_update_contents:
              sqldebug: 0
              vars: mintsinserted
              sql: DELETE FROM fabric_aggr_by_ts WHERE (ts >= mintsinserted);
                   DELETE FROM fabric_aggr_by_ts WHERE (ts < mintsinserted - 72*3600);
                   INSERT INTO fabric_aggr_by_ts (ts,mbin_avg,mbin_min,mbin_max,mbin_sum,
                                                  mbout_avg,mbout_min,mbout_max,mbout_sum,
                                                  pckin_avg,pckin_min,pckin_max,pckin_sum,
                                                  pckout_avg,pckout_min,pckout_max,pckout_sum)
                                                SELECT ts,
                                                        AVG(mbin),MIN(mbin),MAX(mbin),SUM(mbin),
                                                        AVG(mbout),MIN(mbout),MAX(mbout),SUM(mbout),
                                                        AVG(pckin),MIN(pckin),MAX(pckin),SUM(pckin),
                                                        AVG(pckout),MIN(pckout),MAX(pckout),SUM(pckout)
                                                 FROM fabric WHERE (ts >= mintsinserted)
                                                 GROUP by ts
        columns: 
          - { name: ts,           type: ts_t }
          - { name: mbin_avg,     type: mb_t }
          - { name: mbin_min,     type: mb_t }
          - { name: mbin_max,     type: mb_t }
          - { name: mbin_sum,     type: mb_t }
          - { name: mbout_avg,    type: mb_t }
          - { name: mbout_min,    type: mb_t }
          - { name: mbout_max,    type: mb_t }
          - { name: mbout_sum,    type: mb_t }
          - { name: pckin_avg,    type: pck_t }
          - { name: pckin_min,    type: pck_t }
          - { name: pckin_max,    type: pck_t }
          - { name: pckin_sum,    type: pck_t }
          - { name: pckout_avg,   type: pck_t }
          - { name: pckout_min,   type: pck_t }
          - { name: pckout_max,   type: pck_t }
          - { name: pckout_sum,   type: pck_t }

    - table:
        name: fabric_time_aggr_ts
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              aggr_by_time_resolutions: [1, 60, 1440]     # in minutes (1 min, 1 hour, 1 day)
              aggr_by_time_mintsvar: mintsinserted
              sql: DELETE FROM fabric_time_aggr_ts WHERE (ts >= mintsinserted);
                   INSERT INTO fabric_time_aggr_ts (_time_res, _time_cnt, ts, mbin_sum,mbout_sum,pckin_sum,pckout_sum)
                                                SELECT 1,1, ts, mbin_sum,mbout_sum,pckin_sum,pckout_sum
                                                FROM fabric_aggr_by_ts
                                                WHERE (ts >= mintsinserted)
              sqldebug: 0
          archive:
            limit_aggr_time: [ 6120, 133920, 2628000 ]     # in minutes (3 days, 93 days, 5 years)
            limit_aggr_time_var: ts
        columns: 
          - { name: _time_res, type: _time_res_t }
          - { name: _time_cnt, type: _time_cnt_t }
          - { name: ts,           type: ts_t,  time_aggr: TS  }
          - { name: mbin_sum,     type: mb_t,  time_aggr: AVG }
          - { name: mbout_sum,    type: mb_t,  time_aggr: AVG }
          - { name: pckin_sum,    type: pck_t, time_aggr: AVG }
          - { name: pckout_sum,   type: pck_t, time_aggr: AVG }

    #-----------------------------------
    # tables, containing per nodeid info
    #-----------------------------------
    - table:
        name: fabric_aggr_by_node
        options:
          update:
            # updates only a subset of nodes in one step (full turn in 15 steps)
            sql_update_contents:
              sql: DELETE FROM fabric_aggr_by_node
                          WHERE nodeid IN (
                                       SELECT nodeid FROM nodeinfo, node_update_status
                                       WHERE nid%update_step_max=update_step and step_id=1
                                       );
                   INSERT INTO fabric_aggr_by_node SELECT nodeid,
                                                          AVG(mbin),MIN(mbin),MAX(mbin),
                                                          AVG(mbout),MIN(mbout),MAX(mbout),
                                                          AVG(pckin),MIN(pckin),MAX(pckin),
                                                          AVG(pckout),MIN(pckout),MAX(pckout)
                                                   FROM fabric 
                                                   WHERE nodeid IN (
                                                         SELECT nodeid FROM nodeinfo, node_update_status
                                                         WHERE nid%update_step_max=update_step and step_id=1
                                                         )
                                                   GROUP by nodeid

        columns: 
          - { name: nodeid,      type: nodeid_t }
          - { name: mbin_avg,    type: mb_t }
          - { name: mbin_min,    type: mb_t }
          - { name: mbin_max,    type: mb_t }
          - { name: mbout_avg,   type: mb_t }
          - { name: mbout_min,   type: mb_t }
          - { name: mbout_max,   type: mb_t }
          - { name: pckin_avg,    type: pck_t }
          - { name: pckin_min,    type: pck_t }
          - { name: pckin_max,    type: pck_t }
          - { name: pckout_avg,   type: pck_t }
          - { name: pckout_min,   type: pck_t }
          - { name: pckout_max,   type: pck_t }
          
    #----------------------------------
    # tables, containing per jobid info
    #----------------------------------
    - table:
        name: fabric_by_jobid_nodeid_ts
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql: DELETE FROM fabric_by_jobid_nodeid_ts WHERE (ts >= mintsinserted);
                   INSERT INTO fabric_by_jobid_nodeid_ts SELECT jnt.jobid, fa.ts, fa.nodeid,
                                                         fa.mbin, fa.mbout, fa.pckin, fa.pckout
                               FROM fabric_jobmap_by_nd_minmaxts jnt,
                                    fabric fa
                               WHERE  (fa.ts >= mintsinserted)
                                      AND (fa.ts >= jnt.mints) AND (fa.ts <= jnt.maxts+59) AND (jnt.nodeid=fa.nodeid)
              sqldebug: 0                                      
          archive:
            limit: max(ts)-25h
        columns: 
          - { name: jobid,       type: jobid_t }
          - { name: ts,          type: ts_t }
          - { name: nodeid,      type: nodeid_t }
          - { name: mbin,        type: mb_t }
          - { name: mbout,       type: mb_t }
          - { name: pckin,       type: pck_t }
          - { name: pckout,      type: pck_t }

    - table:
        name: fabric_aggr_by_jobid_ts
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql: DELETE FROM fabric_aggr_by_jobid_ts WHERE (ts >= mintsinserted);
                   INSERT INTO fabric_aggr_by_jobid_ts
                        SELECT jobid,
                               ts,
                               AVG(mbin),   MIN(mbin),   MAX(mbin),
                               AVG(mbout),  MIN(mbout),  MAX(mbout),
                               AVG(pckin),  MIN(pckin),  MAX(pckin),
                               AVG(pckout), MIN(pckout), MAX(pckout)
                               FROM fabric_by_jobid_nodeid_ts
                               WHERE (ts >= mintsinserted)
                               GROUP by jobid,ts;
          archive:
            limit: max(ts)-25h
        columns: 
          - { name: jobid,       type: jobid_t }
          - { name: ts,          type: ts_t    }
          - { name: mbin_avg,    type: mb_t }
          - { name: mbin_min,    type: mb_t }
          - { name: mbin_max,    type: mb_t }
          - { name: mbout_avg,   type: mb_t }
          - { name: mbout_min,   type: mb_t }
          - { name: mbout_max,   type: mb_t }
          - { name: pckin_avg,    type: pck_t }
          - { name: pckin_min,    type: pck_t }
          - { name: pckin_max,    type: pck_t }
          - { name: pckout_avg,   type: pck_t }
          - { name: pckout_min,   type: pck_t }
          - { name: pckout_max,   type: pck_t }

    - table:
        name: fabric_aggr_by_jobid
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql: DELETE FROM fabric_aggr_by_jobid WHERE jobid IN (SELECT jobid from fabric_current_jobid);
                   INSERT INTO fabric_aggr_by_jobid
                        SELECT jobid, MAX(ts), COUNT(ts),
                               AVG(mbin_avg),  MIN(mbin_min),  MAX(mbin_max),
                               AVG(mbout_avg), MIN(mbout_min), MAX(mbout_max),
                               AVG(pckin_avg),  MIN(pckin_min),  MAX(pckin_max),
                               AVG(pckout_avg), MIN(pckout_min), MAX(pckout_max)
                               FROM fabric_aggr_by_jobid_ts
                               WHERE jobid IN (SELECT jobid from fabric_current_jobid)
                               GROUP by jobid;
        columns: 
          - { name: jobid,       type: jobid_t }
          - { name: falastts,    type: ts_t    }
          - { name: fa_ndps,     type: count_t    }
          - { name: mbin_avg,    type: mb_t }
          - { name: mbin_min,    type: mb_t }
          - { name: mbin_max,    type: mb_t }
          - { name: mbout_avg,   type: mb_t }
          - { name: mbout_min,   type: mb_t }
          - { name: mbout_max,   type: mb_t }
          - { name: pckin_avg,    type: pck_t }
          - { name: pckin_min,    type: pck_t }
          - { name: pckin_max,    type: pck_t }
          - { name: pckout_avg,   type: pck_t }
          - { name: pckout_min,   type: pck_t }
          - { name: pckout_max,   type: pck_t }


# only in sqlite > 3.8.3          
#                                   printf("%s:%d",i.nodeid,i.nr) AS nmap

          
    #----------------------------
    # temp. tables to speed joins 
    #----------------------------
         
    - table:
        name: fabric_jobmap_by_nd_minmaxts
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql: DELETE FROM fabric_jobmap_by_nd_minmaxts;
                   INSERT INTO fabric_jobmap_by_nd_minmaxts
                        SELECT jt.jobid,
                               jn.nodeid,
                               min(jt.ts),
                               max(jt.ts)
                               FROM jobnodemap jn, jobtsmap jt
                               WHERE (jt.jobid=jn.jobid)
                               GROUP BY jt.jobid,jn.nodeid;
          update_trigger:
        columns: 
          - { name: jobid,    type: jobid_t }
          - { name: nodeid,   type: nodeid_t }
          - { name: mints,    type: ts_t    }
          - { name: maxts,    type: ts_t    }
          
    - table:
        name: fabric_current_jobid
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sqldebug: 0
              sql: DELETE FROM fabric_current_jobid;
                   INSERT INTO fabric_current_jobid
                        SELECT jt.jobid
                               FROM jobtsmap jt
                               WHERE (jt.ts >= mintsinserted-59);
          update_trigger:
        columns: 
          - { name: jobid,    type: jobid_t }

# Update tables: (fill new time_aggr table with data from old span tables)
# one line:
# select _time_res,count(*),sum(_time_cnt),min(ts),max(ts),(max(ts)-min(ts))/60.0/60.0/24.0 from fabric_time_aggr_ts   group by _time_res;insert into fabric_time_aggr_ts (_time_res,_time_cnt,ts, mbin_sum,mbout_sum,pckin_sum,pckout_sum) select 1,1,ts, mbin_sum,mbout_sum,pckin_sum,pckout_sum from fabric_aggr_by_ts where ts<(select min(ts) from fabric_time_aggr_ts where (_time_res=1));insert into fabric_time_aggr_ts (_time_res,_time_cnt,ts, mbin_sum,mbout_sum,pckin_sum,pckout_sum) select 60,60,ts, mbin_sum,mbout_sum,pckin_sum,pckout_sum from fabric_aggr_by_ts_hourly where ts<=(select min(ts) from fabric_time_aggr_ts where (_time_res=60)); insert into fabric_time_aggr_ts (_time_res,_time_cnt,ts, mbin_sum,mbout_sum,pckin_sum,pckout_sum) select 1440,1440,ts, mbin_sum,mbout_sum,pckin_sum,pckout_sum from fabric_aggr_by_ts_daily where ts<=(select min(ts) from fabric_time_aggr_ts where (_time_res=1440));select _time_res,count(*),sum(_time_cnt),min(ts),max(ts),(max(ts)-min(ts))/60.0/60.0/24.0 from fabric_time_aggr_ts  group by _time_res;
