# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

icmapstate:
  tables:
    # additional common tables jobmapts, jobmapnode 
    %include "../conf_common/jobmap_tables.yaml"

    - table:
        name: trigger
        options:
          update:
            LML: trigger
            mode: replace
          update_trigger:
            - icmap_current_jobid
            - icmap_aggr_by_jobid
        columns: 
          - { name: ts,          type: ts_t,       LML_from: ts,          LML_default: -1,  LML_minlastinsert: mintsinserted   }

    #-----------------------------------------
    # table, filled by LML input, static input
    #-----------------------------------------
    - table:
        name: icmap
        options:
          update:
            LML: icmap
            mode: replace
          archive:
        columns: 
          - { name: nodeid,      type: nodeid_t,   LML_from: id,          LML_default: 'unknown' }
          - { name: ts,          type: ts_t,       LML_from: ts,          LML_default: -1 }
          - { name: nr,          type: count_t,    LML_from: nr,          LML_default: 0.0 }

    - table:
        name: icmap_current_jobid
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sqldebug: 0
              sql: DELETE FROM icmap_current_jobid;
                   INSERT INTO icmap_current_jobid
                        SELECT jt.jobid
                               FROM jobtsmap jt
                               WHERE (jt.ts >= mintsinserted-59);
          update_trigger:
        columns: 
          - { name: jobid,    type: jobid_t }

    - table:
        name: icmap_aggr_by_jobid
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sqldebug: 0
              sql: DELETE FROM icmap_aggr_by_jobid WHERE jobid IN (SELECT jobid from icmap_current_jobid);
                   INSERT INTO icmap_aggr_by_jobid (jobid, icmaplastts, icgroupmap)
                        SELECT jobid, maxts, group_concat(nmap," ")
                        FROM (
                        SELECT jt.jobid,
                                max(jt.ts) AS maxts,
                                i.nodeid||":"||i.nr AS nmap
                               FROM jobnodemap jn, jobtsmap jt, icmap i
                               WHERE (jt.jobid=jn.jobid) AND (jn.nodeid=i.nodeid)
                               GROUP BY jt.jobid,jn.nodeid
                              )
                              GROUP by jobid;
        columns: 
          - { name: jobid,       type: jobid_t }
          - { name: icmaplastts, type: ts_t    }
          - { name: icgroupmap,  type: extralongstr_t }
