# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

nodeid_t:
  sql: VARCHAR(14) NOT NULL DEFAULT '-'
ts_t:
  sql: INT(8) NOT NULL DEFAULT -1
count_t:
  sql: INT(8) NOT NULL DEFAULT -1
count_f_t:
  sql: FLOAT(14) NOT NULL DEFAULT -1
status_t:
  sql: VARCHAR(20) NOT NULL DEFAULT 'unknown'
feature_t:
  sql: VARCHAR(10) NOT NULL DEFAULT 'U'
istatus_t:
  sql: INT(4) NOT NULL DEFAULT -1
load_t:
  sql: FLOAT(14) NOT NULL DEFAULT 0
usage_t:
  sql: FLOAT(14) NOT NULL DEFAULT 0
cores_t:
  sql: INT(12) NOT NULL DEFAULT 0
cores_f_t:
  sql: FLOAT(14) NOT NULL DEFAULT 0
tasks_t:
  sql: INT(12) NOT NULL DEFAULT 0
mem_t:
  sql: INT(14) NOT NULL DEFAULT 0
mem_f_t:
  sql: FLOAT(14) NOT NULL DEFAULT 0
jobid_t:
  sql: VARCHAR(30) NOT NULL DEFAULT '-'
resid_t:
  sql: VARCHAR(30) NOT NULL DEFAULT '-'
ukey_t:
  sql: VARCHAR(30) NOT NULL DEFAULT '-'
perc_t:
  sql: FLOAT(8) DEFAULT 0
owner_t:
  sql: VARCHAR(50) NOT NULL DEFAULT '-'
jgroup_t:
  sql: VARCHAR(50) NOT NULL DEFAULT '-'
jstatus_t:
  sql: VARCHAR(30) NOT NULL DEFAULT '-'
detailedstatus_t:
  sql: VARCHAR(40) NOT NULL DEFAULT '-'
wall_t:
  sql: INT(10) NOT NULL DEFAULT '-'
date_t:
  sql: VARCHAR(19) NOT NULL DEFAULT '-'
name_t:
  sql: VARCHAR(256) NOT NULL DEFAULT '-'
comment_t:
  sql: VARCHAR(256) NOT NULL DEFAULT '-'
queue_t:
  sql: VARCHAR(30) NOT NULL DEFAULT '-'
qos_t:
  sql: VARCHAR(30) NOT NULL DEFAULT '-'
dependency_t:
  sql: VARCHAR(256) NOT NULL DEFAULT '-'
command_t:
  sql: VARCHAR(512) NOT NULL DEFAULT '-'
prio_t:
  sql: INT(10) NOT NULL DEFAULT 0
favored_t:
  sql: INT(4) NOT NULL DEFAULT 0
restart_t:
  sql: INT(4) NOT NULL DEFAULT 0
account_t:
  sql: VARCHAR(30) NOT NULL DEFAULT '-'
time_t:
  sql: INT(10) NOT NULL DEFAULT 0
hour_t:
  sql: FLOAT(26) NOT NULL DEFAULT 0
hour_n_t:
  sql: FLOAT(26) DEFAULT 0
pos_t:
  sql: INT(10) NOT NULL DEFAULT 0
mb_t:
  sql: FLOAT(14) NOT NULL DEFAULT 0
pck_t:
  sql: FLOAT(14) NOT NULL DEFAULT 0
fs_t:
  sql: VARCHAR(15) NOT NULL DEFAULT '-'
bytes_t:
  sql: INT(32) NOT NULL DEFAULT 0
Mops_t:
  sql: FLOAT(14) NOT NULL DEFAULT 0
ops_t:
  sql: INT(20) NOT NULL DEFAULT 0
errcnt_t:
  sql: INT(12) NOT NULL DEFAULT 0
clk_t:
  sql: INT(6) NOT NULL DEFAULT 0
clkr_t:
  sql: INT(6) NOT NULL DEFAULT 0
num_t:
  sql: INT(10) NOT NULL DEFAULT 0
rate_t:
  sql: FLOAT(26) NOT NULL DEFAULT 0
power_t:
  sql: INT(10) NOT NULL DEFAULT 0
power_f_t:
  sql: FLOAT(32) NOT NULL DEFAULT 0
cnt_t:
  sql: INT(24) NOT NULL DEFAULT 0
cnt_f_t:
  sql: FLOAT(16) NOT NULL DEFAULT 0
cnt_n_t:
  sql: INT(24) DEFAULT 0
temp_t:
  sql: INT(4) NOT NULL DEFAULT 0
temp_f_t:
  sql: FLOAT(16) NOT NULL DEFAULT 0
shortstr_t:
  sql: VARCHAR(16) NOT NULL DEFAULT '-'
fid_t:
  sql: VARCHAR(48) NOT NULL DEFAULT '-'
longstr_t:
  sql: VARCHAR(512) NOT NULL DEFAULT '-'
llongstr_t:
  sql: VARCHAR(2048) NOT NULL DEFAULT '-'
extralongstr_t:
  sql: VARCHAR(100000) NOT NULL DEFAULT '-'
score_t:
  sql: FLOAT(16) NOT NULL DEFAULT 0
flag_t:
  sql: INT(1) NOT NULL DEFAULT 0
filename_t:
  sql: VARCHAR(512) NOT NULL DEFAULT '-'
chainid_t:
  sql: VARCHAR(30) NOT NULL DEFAULT '-'
checksum_t:
  sql: FLOAT(32) NOT NULL DEFAULT 0
pid_t:
  sql: INT(10) NOT NULL DEFAULT 0
_time_res_t:
  sql: INT(12) NOT NULL DEFAULT -1
_time_cnt_t:
  sql: INT(8) NOT NULL DEFAULT -1
int_t:
  sql: INT(16) NOT NULL DEFAULT -1
float_t:
  sql: FLOAT(32) NOT NULL DEFAULT 0
primary_key_t:
  sql: INTEGER NOT NULL PRIMARY KEY

