# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

# tables for incremental node update

- table:
    name: nodeinfo
    options:
      update:
      index: nodeid
    columns: 
    - { name: nodeid,      type: nodeid_t }
    - { name: nid,         type: cnt_t }

- table:
    name: node_update_status
    options:
      update:
        sql_update_contents:
          sql: INSERT INTO node_update_status (step_id,update_step,update_step_max)
                           SELECT 1,0,15 WHERE NOT EXISTS(
                                                           SELECT 1
                                                           FROM node_update_status
                                                           WHERE (step_id=1)
                                                           );
               UPDATE node_update_status SET update_step = (update_step + 1) % update_step_max WHERE (step_id = 1);

    columns: 
    - { name: step_id,           type: cnt_t }
    - { name: update_step,       type: cnt_t }
    - { name: update_step_max,   type: cnt_t }

          
