# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "syspower"
    filepath:      "$outputdir/ll/graphpage_syspower.json"
    columns: 1
    graphs: 
            
       - name: "system_rack_power"
         xcol: "date"
         height: "450px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "Power Usage per Rack (kW)"
           legend:
               x: "0.5"
               xanchor: "center"
               y: "1"
               yanchor: "bottom"
         traces:
           %include "jobreport_graphpage_sysoverview_rackpower.yaml"

       - name: "system_compare"
         xcol: "date"
         height: "250px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "#nodes"
           yaxis2: 
               title: "Power Usage per Rack (kW)"
           legend:
               x: "0.5"
               xanchor: "center"
               y: "1"
               yanchor: "bottom"
         traces:
           - name:   "Power All Racks"
             ycol: "power"
             yaxis:  "y2"
             type:   "line"
             color:  "#00F000"
             datapath: "data/_sysstat/sysrackpwr_allracks.csv"
           - name:   "Nodes allocated and running jobs"
             ycol: "count"
             yaxis:  "y"
             mode:   "lines+markers"
             marker:
                 size: 3
             color:  "#B00000"
             datapath: "data/_sysstat/sysstat_ALLRuALL.csv"
           
       - name: "GPU_compare1"
         xcol: "date"
         height: "250px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "GPU usage (perc)"
           yaxis2: 
               title: "Power Usage per Rack (kW)"
           legend:
               x: "0.5"
               xanchor: "center"
               y: "1"
               yanchor: "bottom"
         traces:
           - name:   "Power All Racks"
             ycol: "power"
             yaxis:  "y2"
             type:   "line"
             color:  "#00F000"
             datapath: "data/_sysstat/sysrackpwr_allracks.csv"
           - name:   "GPU usage (all)"
             ycol: "gpuuse"
             yaxis:  "y"
             type:   "scatter"
             color:  "#A00000"
             datapath: "data/_sysstat/GPU_all.csv"

       - name: "GPU_compare2"
         xcol: "date"
         height: "450px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "Power Usage (mW)"
           yaxis2: 
               title: "Power Usage per Rack (kW)"
           legend:
               x: "0.5"
               xanchor: "center"
               y: "1"
               yanchor: "bottom"
         traces:
           - name:   "Power All Racks"
             ycol: "power"
             yaxis:  "y2"
             type:   "line"
             color:  "#00F000"
             datapath: "data/_sysstat/sysrackpwr_allracks.csv"
           - name:   "avg. GPU power"
             ycol: "gpupow"
             yaxis:  "y"
             type:   "scatter"
             color:  "#A00000"
             datapath: "data/_sysstat/GPU_all.csv"
             
             
