# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "sysio"
    filepath:      "$outputdir/ll/graphpage_sysio.json"
    columns: 1
    graphs: 
       - name: "Read_activity"
         xcol: "date"
         height: "330px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "MiB/s"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Read Activity per File System<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "HOME"
             ycol: "MbrR_sum"
             yaxis:  "y"
             color:  "#B00000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_HOME_span.csv"
           - name:   "FASTDATA"
             ycol: "MbrR_sum"
             yaxis:  "y"
             color:  "#B0B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_FASTDATA_span.csv"
           - name:   "PROJECT"
             ycol: "MbrR_sum"
             yaxis:  "y"
             color:  "#0000B0"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_PROJECT_span.csv"
           - name:   "SCRATCH"
             ycol: "MbrR_sum"
             yaxis:  "y"
             color:  "#00B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_SCRATCH_span.csv"
       - name: "Write_activity"
         xcol: "date"
         height: "330px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "MiB/s"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Write Activity per File System<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "HOME"
             ycol: "MbwR_sum"
             yaxis:  "y"
             color:  "#B00000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_HOME_span.csv"
           - name:   "FASTDATA"
             ycol: "MbwR_sum"
             yaxis:  "y"
             color:  "#B0B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_FASTDATA_span.csv"
           - name:   "PROJECT"
             ycol: "MbwR_sum"
             yaxis:  "y"
             color:  "#0000B0"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_PROJECT_span.csv"
           - name:   "SCRATCH"
             ycol: "MbwR_sum"
             yaxis:  "y"
             color:  "#00B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_SCRATCH_span.csv"
       - name: "OpenClose_activity"
         xcol: "date"
         height: "330px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "Operations/s"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Open/Close Activity per File System<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "HOME"
             ycol: "ocR_sum"
             yaxis:  "y"
             color:  "#B00000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_HOME_span.csv"
           - name:   "FASTDATA"
             ycol: "ocR_sum"
             yaxis:  "y"
             color:  "#B0B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_FASTDATA_span.csv"
           - name:   "PROJECT"
             ycol: "ocR_sum"
             yaxis:  "y"
             color:  "#0000B0"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_PROJECT_span.csv"
           - name:   "SCRATCH"
             ycol: "ocR_sum"
             yaxis:  "y"
             color:  "#00B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_IO_SCRATCH_span.csv"
