# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

- name:   "16GB"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#A9DFBF"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_maxmem_16.csv"
- name:   "32GB"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#7DCEA0"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_maxmem_32.csv"
- name:   "64GB"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#52BE80"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_maxmem_64.csv"
- name:   "96GB"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#27AE60"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_maxmem_96.csv"
- name:   "128GB"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#229954"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_maxmem_128.csv"
- name:   "256GB"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#1E8449"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_maxmem_256.csv"
- name:   "384GB"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#FAD7A0"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_maxmem_384.csv"
- name:   "512GB"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  ""
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_maxmem_512.csv"
