# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "internalstat"
    filepath:      "$outputdir/ll/graphpage_internalstat.json"
    stat_database: jobreport_json_stat
    stat_table:    datasetstat_graphpages
    columns: 2
    graphs: 
       - name: "DBstat_ALL"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "DB:  #rows in all tables"
         datapath: "data/_internal/DBtab/DBtab_ALL:ALLtab.csv"
         
         traces:
           - name:   "DB: total #rows in all tables"
             ycol: "nrows"
             yaxis:  "y"
             type:   "line"
             color:  "#0000B0"
             
       - name: "DBstat_joblist"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "DB: #jobs"
         traces:
           - name:   "DB: #jobs stored in DB"
             ycol: "nrows"
             yaxis:  "y"
             type:   "line"
             color:  "#0000B0"
             datapath: "data/_internal/DBtab/DBtab_jobreport:joblist.csv"
           - name:   "DB: #jobs stored on disk"
             ycol: "nrows"
             yaxis:  "y"
             type:   "line"
             color:  "#B0B000"
             datapath: "data/_internal/DBtab/DBtab_jobreport_stat_loadmem:datasetstat_csv.csv"
             
       - name: "Step_Timings_P2"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
             title: "duration (s)"
         traces:
           - trace:
             name:   "step_PART2_ALL"
             ycol: "dt"
             yaxis:  "y"
             type:   "line"
             color:  "#A00000"
             datapath: "data/_internal/steptimings/step_PART2_ALL.csv"

       - name: "Step_Timings_P4"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
             title: "duration (s)"
         traces:
           - trace:
             name:   "step_PART4_ALL"
             ycol: "dt"
             yaxis:  "y"
             type:   "line"
             color:  "#A00000"
             datapath: "data/_internal/steptimings/step_PART4_ALL.csv"

       - name: "Step_Timings_DBupdate"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
             title: "duration (s)"
         traces:
           - trace:
             name:   "step_PART2_LMLDBupdate"
             ycol: "dt"
             yaxis:  "y"
             type:   "line"
             color:  "#A00000"
             datapath: "data/_internal/steptimings/step_PART2_LMLDBupdate.csv"

       - name: "Step_Timings_jobreport"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
             title: "duration (s)"
         traces:
           - trace:
             name:   "step_PART4_jobreport"
             ycol: "dt"
             yaxis:  "y"
             type:   "line"
             color:  "#A00000"
             datapath: "data/_internal/steptimings/step_PART4_jobreport.csv"
             
       - name: "update_rate"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
             title: "number of updates"
         traces:
           - trace:
             name:   "Updates per hour"
             ycol: "num_upd"
             yaxis:  "y"
             type:   "line"
             color:  "#A00000"
             datapath: "data/_sysstat/sysstat_ALLALLALL_hourly.csv"
             
       - name: "llview_usage"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
             title: "number of users"
         traces:
           - trace:
             name:   "Unique users that accessed portal"
             ycol: "nusers_web"
             yaxis:  "y"
             type:   "line"
             color:  "#A00000"
             datapath: "data/_sysstat/llview_usage.dat"
           - trace:
             name:   "Unique users that submitted jobs"
             ycol: "nusers_sub"
             yaxis:  "y"
             type:   "line"
             color:  "#00A000"
             datapath: "data/_sysstat/llview_usage.dat"
           - trace:
             name:   "Unique users that submitted jobs and accessed portal"
             ycol: "nusers_both"
             yaxis:  "y"
             type:   "line"
             color:  "#0000A0"
             datapath: "data/_sysstat/llview_usage.dat"
             
       - name: "DCGM_stat"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
             title: "number of GPUs"
         traces:
           - trace:
             name:   "#GPUs active"
             ycol: "numGPUs"
             yaxis:  "y"
             type:   "line"
             color:  "#00A000"
             datapath: "data/_sysstat/GPU_all.csv"
           - trace:
             name:   "#GPUs DCGM up"
             ycol: "numDCGMup"
             yaxis:  "y"
             type:   "line"
             color:  "#0000A0"
             datapath: "data/_sysstat/GPU_all.csv"
           - trace:
             name:   "#GPUs DCGM down"
             ycol: "numDCGMdown"
             yaxis:  "y"
             type:   "line"
             color:  "#A00000"
             datapath: "data/_sysstat/GPU_all.csv"
             
            
             
