# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "sysstatistics"
    filepath:      "$outputdir/ll/graphpage_sysstatistics.json"
    columns: 1
    graphs: 

       - name: "Job_size_hist_avg"
         xcol: "date"
         height: "400px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "#nodes"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Number of nodes used by jobs of size x<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           %include "jobreport_graphpage_sysstatistics_size_hist_avg.yaml"  
           
       - name: "Memory_hist_max"
         xcol: "date"
         height: "350px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "#nodes"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Number of nodes used up to x GB memory (maximum over runtime of job)<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           %include "jobreport_graphpage_sysstatistics_memory_hist_max.yaml"  
           
       - name: "Memory_hist_avg"
         xcol: "date"
         height: "350px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "#nodes"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Number of nodes used up to x GB memory (average over runtime of job)<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           %include "jobreport_graphpage_sysstatistics_memory_hist_avg.yaml"  

       - name: "UsedNodes_by_MaxMemory_ts_heatmap"
         xcol: "date"
         height: "350px"
         layout:
          #  %include "jobreport_graphpage_layout_range.yaml"
           paper_bgcolor: '#FFFFFF'
           plot_bgcolor: '#FFFFFF'
          #  xaxis: 
          #      type: "date"
           yaxis: 
               title: "Memory Range"
          #  legend:
          #      x: "0.0"
          #      xref: "x domain"
          #      xanchor: "left"
          #      y: "1"
          #      yanchor: "top"
           title:
               text: "<b>Number of nodes used up to x GB memory per time (maximum over runtime of job)<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "UsedNodes"
             xcol: "date"
             ycol: "memcls"
             zcol: "sum_nodes"
            #  yaxis:  "y"
             type:   "heatmap"
             fill: null
            #  colorscale: 'Hot'
            #  reversescale: true

            #  stackgroup: "memory"
             datapath: "data/_sysstat/sysstat_heatmap_maxmem.csv"
           
       - name: "UsedNodes_by_MaxMemory_node_heatmap"
         xcol: "date"
         height: "350px"
         layout:
           paper_bgcolor: '#FFFFFF'
           plot_bgcolor: '#FFFFFF'
           xaxis: 
               type: "log"
           yaxis: 
               title: "Memory Range"
          #  legend:
          #      x: "0.0"
          #      xref: "x domain"
          #      xanchor: "left"
          #      y: "1"
          #      yanchor: "top"
           title:
               text: "<b>Number of nodes used up to x GB memory per job size (maximum over runtime of job)<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "UsedNodes"
             xcol: "sizecls"
             ycol: "memcls"
             zcol: "sum_nodes"
            #  yaxis:  "y"
             type:   "heatmap"
             fill: null
            #  colorscale: 'Hot'
            #  reversescale: true

            #  stackgroup: "memory"
             datapath: "data/_sysstat/sysstat_heatmap_maxmem_node.csv"
           
