# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "sysstatistics"
    filepath:      "$outputdir/ll/graphpage_sysstatistics.json"
    stat_database: jobreport_json_stat
    stat_table:    datasetstat_graphpages
    columns: 1
    graphs: 
       - name: "Job_size_hist_avg"
         xcol: "date"
         height: "400px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "#nodes"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Number of nodes used by jobs of size x<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           %include "jobreport_graphpage_sysstatistics_size_hist_avg.yaml"  
