# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "sysenv"
    filepath:      "$outputdir/ll/graphpage_sysenv.json"
    stat_database: jobreport_json_stat
    stat_table:    datasetstat_graphpages
    columns: 1
    graphs: 
       - name: "system_env_power"
         xcol: "date"
         height: "400px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "System Power Usage  (kW)"
           legend:
               x: "0.15"
               xanchor: "left"
               y: "1"
               yanchor: "bottom"
           title:
               text: "<b>System Power Usage  (kW)<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Power All Racks"
             ycol: "power"
             yaxis:  "y"
             type:   "line"
             color:  "#40A040"
             stackgroup: "power"
             %include "jobreport_graphpage_environment_input.yaml"

       - name: "water-temp"
         xcol: "date"
         height: "350px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "Water Cooling Temperature  (&deg;C)"
           legend:
               x: "0.15"
               xanchor: "left"
               y: "1"
               yanchor: "bottom"
           title:
               text: "<b>Water Cooling Temperature (&deg;C)<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:

           - name:   "Outlet Temperature (&deg;C)"
             ycol: "water_outlet_temp"
             yaxis:  "y"
             type:   "line"
             color:  "#A00000"
             %include "jobreport_graphpage_environment_input.yaml"
             
           - name:   "Inlet Temperature (&deg;C)"
             ycol: "water_inlet_temp"
             yaxis:  "y"
             type:   "line"
             color:  "#0000B0"
             %include "jobreport_graphpage_environment_input.yaml"
             
       - name: "water-flow"
         xcol: "date"
         height: "250px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "Water Cooling Flow rate (m3/hour)"
           legend:
               x: "0.15"
               xanchor: "left"
               y: "1"
               yanchor: "bottom"
           title:
               text: "<b>Water Cooling Flow rate (m3/hour)<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Water Cooling Flow rate (m3/hour)"
             ycol: "water_flowrate"
             yaxis:  "y"
             type:   "line"
             color:  "#0000B0"
             %include "jobreport_graphpage_environment_input.yaml"

       - name: "water-power"
         xcol: "date"
         height: "250px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "Water Cooling Power (kW)"
           legend:
               x: "0.15"
               xanchor: "left"
               y: "1"
               yanchor: "bottom"
           title:
               text: "<b>Water Cooling Power (kW)<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Water Cooling Power (kW)"
             ycol: "water_power"
             yaxis:  "y"
             type:   "line"
             color:  "#0000B0"
             %include "jobreport_graphpage_environment_input.yaml"
             
