# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

- name:   "Rack01"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#000040"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_01.csv"
- name:   "Rack02"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#000050"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_02.csv"
- name:   "GPU03"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#005030"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_03.csv"
- name:   "GPU04"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#005040"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_04.csv"
- name:   "GPU05"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#005050"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_05.csv"
- name:   "GPU06"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#005060"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_06.csv"
- name:   "GPU07"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#005070"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_07.csv"
- name:   "GPU08"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#005080"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_08.csv"
- name:   "Rack09"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#000090"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_09.csv"
- name:   "Rack10"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#0000A0"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_10.csv"
- name:   "Rack11"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#0000B0"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_11.csv"
- name:   "Rack12"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#0000C0"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_12.csv"
- name:   "Rack13"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#0000D0"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_13.csv"
- name:   "Rack14"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#0000E0"
  stackgroup: "rack"
  datapath: "data/_sysstat/sysrackpwr_14.csv"
- name:   "All Racks"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#00F000"
  datapath: "data/_sysstat/sysrackpwr_allracks.csv"
- name:   "Total Power"
  ycol: "power"
  yaxis:  "y"
  type:   "line"
  color:  "#F00000"
  datapath: "data/_sysstat/sysenvstat_JURECA_DC.csv"
