# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "SYSTEM"
    filepath:      "$outputdir/ll/graphpage_SYSTEM.json"
    columns: 2
    graphs: 
       - name: "totalpower"
         xcol: "date"
         layout:
           annotations: 
             -   xref: "paper"
                 yref: "paper"
                 x: 1.0
                 xanchor: "right"
                 align: "right"
                 y: 1.0
                 yanchor: "bottom"
                 text: "Min: #min#, Max: #max#, Avg: #avg#, Last: #last#"
                 showarrow: false
           xaxis: 
               rangeselector: 
                 buttons:
                   - step: 'day'
                     stepmode: 'backward'
                     count: 1
                     label: '1d'
                   - step: 'day'
                     stepmode: 'backward'
                     count: 7
                     label: '1w'
                   - step: 'month'
                     stepmode: 'backward'
                     count: 1
                     label: '1m'
                   - step: 'month'
                     stepmode: 'backward'
                     count: 6
                     label: '6m'
                  #  - step: 'year'
                  #    stepmode: 'backward'
                  #    count: 1
                  #    label: '1y'
                   - step: 'all'
               rangeslider: 
                visible: true
                bordercolor: '#888888'
                borderwidth: 1
                thickness: 0.20
                translate: '(0,-13)'
           yaxis: 
               title: "System Power Usage"
         datapath: "data/_sysstat/sysrackpwr_allracks.csv"
         traces:
           - name:   "Full System (kW)"
             ycol: "power"
             yaxis:  "y"
             type:   "line"
             color:  "#00B0B0"
       - name: "powerrack"
         xcol: "date"
         layout:
           margin:
             b: 80
           annotations: 
             -  xref: "paper"
                yref: "paper"
                x: 0.5
                xanchor: "center"
                align: "center"
                y: -1.4
                yanchor: "top"
                text: "Min: #min#, Max: #max#, Avg: #avg#, Last: #last#"
                showarrow: false
           xaxis: 
               rangeselector: 
                 buttons:
                   - step: 'day'
                     stepmode: 'backward'
                     count: 1
                     label: '1d'
                   - step: 'day'
                     stepmode: 'backward'
                     count: 7
                     label: '1w'
                   - step: 'month'
                     stepmode: 'backward'
                     count: 1
                     label: '1m'
                   - step: 'month'
                     stepmode: 'backward'
                     count: 6
                     label: '6m'
                  #  - step: 'year'
                  #    stepmode: 'backward'
                  #    count: 1
                  #    label: '1y'
                   - step: 'all'
               rangeslider: 
                visible: true
                bordercolor: '#888888'
                borderwidth: 1
                thickness: 0.20
                translate: '(0,-13)'
           yaxis: 
               title: "Rack Power Usage"
               autorange: true
               fixedrange: false
         traces:
           - name:   "Rack 01 (kW)"
             ycol: "power"
             yaxis:  "y"
             type:   "line"
             color:  "#8B0000"
             datapath: "data/_sysstat/sysrackpwr_01.csv"
           - name:   "Rack 02 (kW)"
             ycol: "power"
             yaxis:  "y"
             type:   "line"
             color:  "#008B00"
             datapath: "data/_sysstat/sysrackpwr_02.csv"
           - name:   "Rack 03 (kW)"
             ycol: "power"
             yaxis:  "y"
             type:   "line"
             color:  "#00008B"
             datapath: "data/_sysstat/sysrackpwr_03.csv"
                  
       - name: "totalpowertest"
         xcol: "date"
         layout:
           margin:
             t: 50
             b: 0
           annotations: 
             -   xref: "paper"
                 yref: "paper"
                 x: 1.0
                 xanchor: "right"
                 align: "right"
                 y: 1.0
                 yanchor: "bottom"
                 text: "Min: #min#, Max: #max#, Avg: #avg#, Last: #last#"
                 showarrow: false
           xaxis: 
               rangeselector: 
                 buttons:
                   - step: 'day'
                     stepmode: 'backward'
                     count: 1
                     label: '1d'
                   - step: 'day'
                     stepmode: 'backward'
                     count: 7
                     label: '1w'
                   - step: 'month'
                     stepmode: 'backward'
                     count: 1
                     label: '1m'
                   - step: 'month'
                     stepmode: 'backward'
                     count: 6
                     label: '6m'
                  #  - step: 'year'
                  #    stepmode: 'backward'
                  #    count: 1
                  #    label: '1y'
                   - step: 'all'
               rangeslider: 
                visible: true
                bordercolor: '#888888'
                borderwidth: 1
                thickness: 0.10
                translate: '(0,@2)'
           yaxis: 
               title: "System Power Usage"
         datapath: "data/_sysstat/sysrackpwr_allracks.csv"
         traces:
           - name:   "Full System (kW)"
             ycol: "power"
             yaxis:  "y"
             type:   "line"
             color:  "#B0B000"
