# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "sysoverview"
    filepath:      "$outputdir/ll/graphpage_sysoverview.json"
    stat_database: jobreport_json_stat
    stat_table:    datasetstat_graphpages
    columns: 1
    graphs: 
       - name: "Node_state"
         xcol: "date"
         height: "550px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "#nodes"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Number of nodes per state<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Nodes allocated and running jobs"
             ycol: "count"
             yaxis:  "y"
            #  mode:   "lines+markers"
            #  marker:
            #      size: 3
             color:  "#00B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_ALLRuALL_span.csv"
           - name:   "Nodes planned (backfilling)"
             ycol: "count"
             yaxis:  "y"
             type:   "line"
             color:  "#00B0B0"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_ALLPlALL_span.csv"
           - name:   "Nodes idle"
             ycol: "count"
             yaxis:  "y"
             type:   "line"
             color:  "#B0B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_ALLIdALL_span.csv"
           - name:   "Nodes idle powered down"
             ycol: "count"
             yaxis:  "y"
             type:   "line"
             color:  "#0000B0"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_ALLPoALL_span.csv"
           - name:   "Reserved"
             ycol: "count"
             yaxis:  "y"
             type:   "line"
             color:  "#B0B0B0"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_ALLReALL_span.csv"
           - name:   "Nodes down"
             ycol: "count"
             yaxis:  "y"
             type:   "line"
             color:  "#B00000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_ALLDoALL_span.csv"
           - name:   "Unknown state"
             ycol: "count"
             yaxis:  "y"
             type:   "line"
             color:  "#B03000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_ALLUnALL_span.csv"

       - name: "Queue_stat"
         xcol: "date"
         height: "450px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "#nodes"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Number of nodes requested by eligible waiting jobs<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           %include "jobreport_graphpage_sysoverview_queue_nodes_requ.yaml"  
