# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

- name:   "booster"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#A00040"
  stackgroup: "queue"
  datapath: "data/_sysstat/sysstat_queue_booster_stat.csv"
- name:   "develbooster"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#00A040"
  stackgroup: "queue"
  datapath: "data/_sysstat/sysstat_queue_develbooster_stat.csv"
- name:   "largebooster"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#A0A040"
  stackgroup: "queue"
  datapath: "data/_sysstat/sysstat_queue_largebooster_stat.csv"
