# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "internaltransfer"
    filepath:      "$outputdir/ll/graphpage_internaltransfer.json"
    stat_database: jobreport_json_stat
    stat_table:    datasetstat_graphpages
    columns: 2
    graphs: 
       - name: "transfer_time"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "transfer time (sec)"
         datapath: "data/_internal/steptimings/transfer_reports.csv"
         traces:
           - name:   "transfer time"
             ycol: "dt"
             yaxis:  "y"
             type:   "line"
             color:  "#0000B0"
             
       - name: "number_files_dirs"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "# files/dirs"
         datapath: "data/_internal/steptimings/transfer_reports.csv"
         traces:
           - name:   "number of dirs"
             ycol: "ndirs"
             yaxis:  "y"
             type:   "line"
             stackgroup: "nfiles"
             color:  "#0B0A00"
           - name:   "number of files"
             ycol: "nregfiles"
             yaxis:  "y"
             type:   "line"
             stackgroup: "nfiles"
             color:  "#0A00B0"
             
       - name: "files_dirs_created_deleted"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "# files/dirs"
         datapath: "data/_internal/steptimings/transfer_reports.csv"
         traces:
           - name:   "files/dirs created"
             ycol: "ncreate"
             yaxis:  "y"
             type:   "line"
             color:  "#0B0A00"
           - name:   "files/dirs deleted"
             ycol: "ndelete"
             yaxis:  "y"
             type:   "line"
             color:  "#0A00B0"
           - name:   "files transferred"
             ycol: "nregfilestrans"
             yaxis:  "y"
             type:   "line"
             color:  "#0000B0"

       - name: "total_size"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "total size (GiB)"
         datapath: "data/_internal/steptimings/transfer_reports.csv"
         traces:
           - name:   "total size"
             ycol: "totalfilesize"
             yaxis:  "y"
             type:   "line"
             color:  "#0B0A00"

       - name: "transfer_size"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "transfer size (MiB)"
         datapath: "data/_internal/steptimings/transfer_reports.csv"
         traces:
           - name:   "bytes to transfer"
             ycol: "totalfilesizetrans"
             yaxis:  "y"
             type:   "line"
             color:  "#0B0A00"
             
       - name: "sent_recv"
         xcol: "date"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "transfer size (MiB)"
         datapath: "data/_internal/steptimings/transfer_reports.csv"
         traces:
           - name:   "bytes recv"
             ycol: "totalbytesrecv"
             yaxis:  "y"
             type:   "line"
             color:  "#0B0A00"
           - name:   "bytes sent"
             ycol: "totalbytessent"
             yaxis:  "y"
             type:   "line"
             color:  "#000B0A"
