# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

- name:   "1 node"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#AED6F1"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_1.csv"
- name:   "2 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#85C1E9"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_2.csv"
- name:   "3..4 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#5DADE2"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_4.csv"
- name:   "5..8 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#3498DB"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_8.csv"
- name:   "9..16 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#2E86C1"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_16.csv"
- name:   "17..32 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#2874A6"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_32.csv"
- name:   "33..64 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#21618C"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_64.csv"
- name:   "65..128 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#1B4F72"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_128.csv"
- name:   "129..256 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#E59866"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_256.csv"
- name:   "257..512 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#DC7633"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_512.csv"
- name:   "513..1024 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#D35400"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_1024.csv"
- name:   "1025..2048 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#BA4A00"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_2048.csv"
- name:   "2049..4096 nodes"
  ycol: "sum_nodes"
  yaxis:  "y"
  type:   "line"
  color:  "#A04000"
  stackgroup: "memory"
  datapath: "data/_sysstat/sysstat_hist_size_4096.csv"
