# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "sysinterconnect"
    filepath:      "$outputdir/ll/graphpage_sysinterconnect.json"
    columns: 1
    graphs: 
       - name: "Data_transmitted"
         xcol: "date"
         height: "330px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "MiB/s"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Total data transmitted between nodes<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Data_in"
             ycol: "mbin_sum"
             yaxis:  "y"
             color:  "#B00000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_interconnect_span.csv"
           - name:   "Data_out"
             ycol: "mbout_sum"
             yaxis:  "y"
             color:  "#B0B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_interconnect_span.csv"
          #  - name:   "PROJECT"
          #    ycol: "MbrR_sum"
          #    yaxis:  "y"
          #    color:  "#0000B0"
          #    stackgroup: "sys"
          #    datapath: "data/_sysstat/sysstat_IO_PROJECT_span.csv"
          #  - name:   "SCRATCH"
          #    ycol: "MbrR_sum"
          #    yaxis:  "y"
          #    color:  "#00B000"
          #    stackgroup: "sys"
          #    datapath: "data/_sysstat/sysstat_IO_SCRATCH_span.csv"
       - name: "Packet_transmitted"
         xcol: "date"
         height: "330px"
         layout:
           %include "jobreport_graphpage_layout_range.yaml"
           yaxis: 
               title: "packets/s"
           legend:
               x: "0.0"
               xref: "x domain"
               xanchor: "left"
               y: "1"
               yanchor: "top"
           title:
               text: "<b>Total number of packets transmitted between nodes<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Pck_in"
             ycol: "pckin_sum"
             yaxis:  "y"
             color:  "#B00000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_interconnect_span.csv"
           - name:   "Pck_out"
             ycol: "pckout_sum"
             yaxis:  "y"
             color:  "#B0B000"
             stackgroup: "sys"
             datapath: "data/_sysstat/sysstat_interconnect_span.csv"
          #  - name:   "PROJECT"
          #    ycol: "MbwR_sum"
          #    yaxis:  "y"
          #    color:  "#0000B0"
          #    stackgroup: "sys"
          #    datapath: "data/_sysstat/sysstat_IO_PROJECT_span.csv"
          #  - name:   "SCRATCH"
          #    ycol: "MbwR_sum"
          #    yaxis:  "y"
          #    color:  "#00B000"
          #    stackgroup: "sys"
          #    datapath: "data/_sysstat/sysstat_IO_SCRATCH_span.csv"
