# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

paper_bgcolor: '#FFFFFF'
plot_bgcolor: '#FFFFFF'
xaxis: 
    rangeselector: 
      buttons:
        - step: 'day'
          stepmode: 'backward'
          count: 1
          label: '1d'
        - step: 'day'
          stepmode: 'backward'
          count: 7
          label: '1w'
        - step: 'month'
          stepmode: 'backward'
          count: 1
          label: '1m'
        - step: 'month'
          stepmode: 'backward'
          count: 6
          label: '6m'
        - step: 'all'
    rangeslider: 
      visible: true
      bordercolor: '#888888'
      borderwidth: 1
      thickness: 0.10
      translate: '(0,-13)'
