################
# Footer DBgraph
################
- footersetelem:
    name: "Dependency"
    info: "Database: #Database#"
    graphs: 
       - graph:
            name: "depgraph"
            type: "mermaid"
            # datapath: "data/_internal/DBgraph.json.gz"
            datapath: "data/_internal/DBtab/DBgraph_#Database#_mermaid.md"


