# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

############
# Footer Cores
############
- footersetelem:
    name: "Cores"
    info: "Usage of cores averaged over runtime, nodes and jobs in the last 3 days (using selected pattern)"
    # info: "#UsedCores (>25%): ##UsedCores#, Node Hours: #Node Hours#, Number of Jobs: ##Jobs# (Averaged over runtime, nodes and all jobs in the last 3 days using Pattern #Pattern#)"
    graphs: 
       - graph:
            name: "Core_Usage"
            xcol: "coreid"
            layout:
              barmode: 'group'
              xaxis:
                  %include "jobreport_footer_cpucores_xaxis_opts.yaml"
                  zeroline: false
                  showgrid: false
                  ticks: 'inside'
                  ticklen: 4
                  tickcolor: 'black'
                  minor:
                    dtick: 1
                    ticks: 'inside'
                    ticklen: 4
                    tickcolor: 'black'
              yaxis: 
                  title: "Core usage (%)"
                  showgrid: false
                  # range: [0,100]
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
              %include "jobreport_footer_cpucores_layout.yaml"
            datapath: "data/_sysstat/cp/syscorepattern_#Pattern ID#.csv"
            traces:
              - trace:  
                  name:   "Physical Cores"
                  ycol: "usage1"
                  yaxis:  "y"
                  type:   "bar"
                  marker:
                    color: "#4444c7"
                    # opacity: 0.6
              - trace:  
                  name:   "Logical Cores"
                  ycol: "usage2"
                  yaxis:  "y"
                  type:   "bar"
                  marker:
                    color: "#d14343"
                    # opacity: 0.6
