# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer Cores
############
- footersetelem:
    name: "Cores"
    info: "Job: #JobID#"
    graphs: 
    #    - graph:
    #         name: "Avg_Core_Usage"
    #         xcol: "coreid"
    #         layout:
    #           xaxis:
    #               dtick: 8
    #           yaxis: 
    #               title: "Core usage (%)"
    #           legend:
    #               x: "0.02"
    #               xanchor: "left"
    #               y: "0.98"
    #               yanchor: "top"
    #         datapath: "data/projects/#Project#/#Owner#/COREusage_#JobID#.csv"
    #         traces:
    #           - trace:  
    #               name:   "avg. core usage"
    #               ycol: "usage"
    #               yaxis:  "y"
    #               type:   "scatter"
    #               color:  "#000082"
       - graph:
            name: "Core_Usage"
            xcol: "coreid"
            layout:
              barmode: 'group'
              xaxis:
                  %include "jobreport_footer_cpucores_xaxis_opts.yaml"
                  zeroline: false
                  showgrid: false
                  ticks: 'inside'
                  ticklen: 4
                  tickcolor: 'black'
                  minor:
                    dtick: 1
                    ticks: 'inside'
                    ticklen: 4
                    tickcolor: 'black'
              yaxis: 
                  title: "Core usage (%)"
                  showgrid: false
                  # range: [0,100]
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
              %include "jobreport_footer_cpucores_layout.yaml"
            datapath: "data/projects/#Project#/#Owner#/PCOREusage_#JobID#.csv"
            traces:
              - trace:  
                  name:   "Physical Cores"
                  ycol: "usage1"
                  yaxis:  "y"
                  type:   "bar"
                  marker:
                    color: "#4444c7"
                    # opacity: 0.6
              - trace:  
                  name:   "Logical Cores"
                  ycol: "usage2"
                  yaxis:  "y"
                  type:   "bar"
                  marker:
                    color: "#d14343"
                    # opacity: 0.6
