# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer GPU
############
- footersetelem:
    name: "Interconnect"
    info: "Job: #JobID#"
    graphs: 
       - graph:
            name: "ICMiB"
            xcol: "date"
            layout:
              yaxis: 
                  title: "GiB/s"
            datapath: "data/projects/#Project#/#Owner#/Fabric_#JobID#.csv"
            traces:
              - trace:
                  name:   "bytes_recv"
                  ycol: "mbin"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
                  factor: "1.0 / 1024.0"                  
              - trace:
                  name:   "bytes_send"
                  ycol: "mbout"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"
                  factor: "1.0 / 1024.0"                  
       - graph:
            name: "ICPck"
            xcol: "date"
            layout:
              yaxis: 
                  title: "mio. packets/s"
            datapath: "data/projects/#Project#/#Owner#/Fabric_#JobID#.csv"
            traces:
              - trace:
                  name:   "packets_recv"
                  ycol: "pckin"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
                  factor: "1.0 / 1000.0 / 1000.0"                  
              - trace:
                  name:   "packets_send"
                  ycol: "pckout"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"
                  factor: "1.0 / 1000.0 / 1000.0"                  


