# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer CPU
############
- footersetelem:
    name: "CPU"
    info: "Job: #JobID#"
    graphs: 
       - graph:
            name: "load"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Load"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/#Owner#/LoadMem_#JobID#.csv"
            traces:
              - trace:
                  name:   "Load"
                  ycol: "load"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"

       - graph:
            name: "usage"
            xcol: "date"
            layout:
              yaxis: 
                  title: "CPU usage (%)"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"

            datapath: "data/projects/#Project#/#Owner#/CPUusage_#JobID#.csv"
            traces:
              - trace:
                  name:   "Usage"
                  ycol: "usage"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#984ea3"

       - graph:
            name: "Total Cores"
            xcol: "date"
            layout:
              yaxis: 
                  title: "# Cores > 25% Usage"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/#Owner#/CPUusage_#JobID#.csv"
            traces:
              - trace:  
                  name:   "Cores"
                  ycol: "cores"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#000082"

       - graph:
            name: "Physical_Logical Cores"
            xcol: "date"
            layout:
              yaxis: 
                  title: "# Cores > 25% Usage"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/#Owner#/CPUusage_#JobID#.csv"
            traces:
              - trace:  
                  name:   "Physical Cores"
                  ycol: "cores_phys"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00AA82"
              - trace:  
                  name:   "Logical Cores"
                  ycol: "cores_logic"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#AAAA82"


