#################
# Footer ProjStat
#################
- footersetelem:
    name: "Jobs"
    info: "Project: #Project#"
    graphs: 
       - graph:
            name: "numjobsperday"
            xcol: "date"
            layout:
              yaxis: 
                  title: "#jobs/day"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/projstat.csv"
            traces:
              - trace:  
                  name:   "Job Size"
                  ycol: "numjobs"
                  yaxis:  "y"
                  type:   "bar"
                  color:  "#008882"
- footersetelem:
    name: "Job-Size"
    info: "Project: #Project#"
    graphs: 
       - graph:
            name: "numnodes"
            xcol: "date"
            layout:
              yaxis: 
                  title: "#nodes/job"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/projstat.csv"
            traces:
              - trace:  
                  name:   "Job Size"
                  ycol: "numnodes"
                  yaxis:  "y"
                  type:   "bar"
                  color:  "#000082"

- footersetelem:
    name: "Job-Duration"
    info: "Project: #Project#"
    graphs: 
       - graph:
            name: "walltime"
            xcol: "date"
            layout:
              yaxis: 
                  title: "hours/job"
              yaxis2: 
                  title: "% wall used"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/projstat.csv"
            traces:
              - trace:  
                  name:   "Wall Time"
                  ycol:   "wall"
                  yaxis:  "y"
                  type:   "bar"
                  color:  "#000082"
                  opacity: 0.6
              - trace:  
                  name:   "Run Time"
                  ycol:   "runtime"
                  yaxis:  "y"
                  type:   "bar"
                  color:  "#880000"
                  opacity: 0.6
              - trace:  
                  name:   "Wall Usage rate"
                  ycol:   "wallusage"
                  yaxis:  "y2"
                  type:   "scatter"
                  color:  "#404040"
                  opacity: 0.6

- footersetelem:
    name: "Load"
    info: "Project: #Project#"
    graphs: 
       - graph:
            name: "load"
            xcol: "date"
            layout:
              yaxis: 
                  title: "load/node"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/projstat.csv"
            traces:
              - trace:  
                  name:   "Load"
                  ycol: "load"
                  yaxis:  "y"
                  type:   "bar"
                  color:  "#A00082"

- footersetelem:
    name: "CPU usage"
    info: "Project: #Project#"
    graphs: 
       - graph:
            name: "CPU usage"
            xcol: "date"
            layout:
              yaxis: 
                  title: "% CPU usage"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/projstat.csv"
            traces:
              - trace:  
                  name:   "CPU Usage"
                  ycol: "usage"
                  yaxis:  "y"
                  type:   "bar"
                  color:  "#A00082"
                  
- footersetelem:
    name: "CPU used cores"
    info: "Project: #Project#"
    graphs: 
       - graph:
            name: "CPU used cores"
            xcol: "date"
            layout:
              yaxis: 
                  title: "# cores used"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/projstat.csv"
            traces:
              - trace:  
                  name:   "Used cores"
                  ycol: "used_cores"
                  yaxis:  "y"
                  type:   "bar"
                  color:  "#A00082"

- footersetelem:
    name: "GPU usage"
    info: "Project: #Project#"
    graphs: 
       - graph:
            name: "GPU usage"
            xcol: "date"
            layout:
              yaxis: 
                  title: "% GPU usage"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/projects/#Project#/projstat.csv"
            traces:
              - trace:  
                  name:   "GPU usage"
                  ycol: "gpu_util"
                  yaxis:  "y"
                  type:   "bar"
                  color:  "#A00082"
                  
