# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer CPU
############
- footersetelem:
    name: "Position in Queue"
    info: "Job: #JobID#, Project: #Project#, Owner: #Owner#"
    graphs: 
       - graph:
            name: "PositionInQueue"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Position"
            datapath: "data/projects/#Project#/#Owner#/Jobdata_#JobID#.csv"
            traces:
              - trace:
                  name:   "PositionInQueue"
                  ycol: "posinqueue"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
- footersetelem:
    name: "Time to Start"
    info: "Job: #JobID#, Project: #Project#, Owner: #Owner#"
    graphs: 
       - graph:
            name: "TimeToStart"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Est. time to start (h)"
            datapath: "data/projects/#Project#/#Owner#/Jobdata_#JobID#.csv"
            traces:
              - trace:
                  name:   "TimeToStart"
                  ycol: "t_est"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
- footersetelem:
    name: "Priority"
    info: "Job: #JobID#, Project: #Project#, Owner: #Owner#"
    graphs: 
       - graph:
            name: "Priority"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Priority"
            datapath: "data/projects/#Project#/#Owner#/Jobdata_#JobID#.csv"
            traces:
              - trace:
                  name:   "Priority (higher is better)"
                  ycol: "userprio"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
- footersetelem:
    name: "Reason"
    info: "Job: #JobID#, Project: #Project#, Owner: #Owner#"
    graphs: 
       - graph:
            name: "Reason"
            xcol: "date"
            layout:
              margin:
                  l: 50
                  r: 400
                  t: 0
                  b: 30
              yaxis: 
                  title: "Reason #"
              annotations: 
                -   xref: "paper"
                    yref: "paper"
                    x: 1.0
                    xanchor: "left"
                    align: "left"
                    y: 0.0
                    yanchor: "bottom"
                    text: "<b>     Reasons:</b><br> 0: None                   7: TimeLimit<br> 1: Priority               8: QOSMaxJobsPerUserLimit<br> 2: Dependency             9: QOSMaxWallPerJobLimit<br> 3: QOSMaxNodePerUserLimit 10: BeginTime<br> 4: NonZeroExitCode        11: JobLaunchFailure<br> 5: Resources              12: BadConstraints<br> 6: Nodes_DOWN,_DRAINED    13: Other"
                    showarrow: false
                    font:
                      family: "'Liberation Mono','Courier New'"
            datapath: "data/projects/#Project#/#Owner#/Jobdata_#JobID#.csv"
            traces:
              - trace:
                  # Reasons: 0->None, 1->Priority, 2-> Dependency, 3-> QOSMaxNodePerUserLimit, 4 -> NonZeroExitCode, 5-> Resources 6-> Nodes_required_for_job_are_DOWN,_DRAINED, 7-> TimeLimit, 8-> QOSMaxJobsPerUserLimit, 9->QOSMaxWallDurationPerJobLimit, 10->BeginTime, 11->JobLaunchFailure, 12->BadConstraints, 13 -> Other 
                  map:
                    0: None
                    1: Priority
                    2: Dependency
                    3: QOSMaxNodePerUserLimit
                    4: NonZeroExitCode
                    5: Resources
                    6: Nodes_DOWN,_DRAINED
                    7: TimeLimit
                    8: QOSMaxJobsPerUserLimit
                    9: QOSMaxWallDurationPerJobLimit
                    10: BeginTime
                    11: JobLaunchFailure
                    12: BadConstraints
                    13: Other 
                  name:   "Reason"
                  ycol: "reason"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"


