# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer GPU
############
- footersetelem:
    name: "GPU"
    info: "Job: #JobID#"
    %include "jobreport_footer_gpu_pattern.yaml"
    graphs: 
       - graph:
            name: "gpuuse"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Usage (%)"
            datapath: "data/projects/#Project#/#Owner#/GPU_#JobID#.csv"
            traces:
              - trace:
                  name:   "Usage"
                  ycol: "gpuuse"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
       - graph:
            name: "gpumem"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Memory (GiB)"
            datapath: "data/projects/#Project#/#Owner#/GPU_#JobID#.csv"
            traces:
              - trace:  
                  name:   "Memory"
                  ycol: "gpumem"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#000082"
                  factor: "1.0 / 1024.0 / 1024.0 / 1024.0"
       - graph:
            name: "gpupow"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Power Usage (W)"
            datapath: "data/projects/#Project#/#Owner#/GPU_#JobID#.csv"
            traces:
              - trace:  
                  name:   "Power Usage"
                  ycol: "gpupow"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#008200"
                  factor: "1.0 / 1000.0" 
       - graph:
            name: "gputemp"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Temperature (&deg;C)"
            datapath: "data/projects/#Project#/#Owner#/GPU_#JobID#.csv"
            traces:
              - trace:  
                  name:   "Temperature"
                  ycol: "gputemp"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#828200"


