# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer CPU
############
- footersetelem:
    name: "CPU"
    info: "Job: #JobID#"
    graphs: 
       - graph:
            name: "loadmem"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Load"
              yaxis2: 
                  title: "Memory Usage (GiB)"
            datapath: "data/projects/#Project#/#Owner#/LoadMem_#JobID#.csv"
            traces:
              - trace:
                  name:   "Load"
                  ycol:   "load"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
              - trace:  
                  name:   "Memory Usage"
                  ycol:   "mem"
                  yaxis:  "y2"
                  type:   "scatter"
                  color:  "#000082"
                  factor: "1.0 / 1024.0 / 1024.0 / 1024.0"                  


