# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer GPU
############
- footersetelem:
    name: "Total I/O"
    info: "Job: #JobID#"
    graphs: 
       - graph:
            name: "FS_all_write"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_all.csv"
            traces:
              - trace:
                  name:   "wrote"
                  ycol: "MBwrite_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
       - graph:
            name: "FS_all_read"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_all.csv"
            traces:
              - trace:
                  name:   "read"
                  ycol: "MBread_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"
       - graph:
            name: "FS_all_open_close"
            xcol: "date"
            layout:
              yaxis: 
                  title: "open close operation/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_all.csv"
            traces:
              - trace:
                  name:   "OpenClose"
                  ycol: "MOpenClose_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"

- footersetelem:
    name: "$PROJECT"
    info: "Job: #JobID#"
    graphs: 
       - graph:
            name: "FS_project_write"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_project.csv"
            traces:
              - trace:
                  name:   "wrote"
                  ycol: "MBwrite_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
       - graph:
            name: "FS_project_read"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_project.csv"
            traces:
              - trace:
                  name:   "read"
                  ycol: "MBread_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"
       - graph:
            name: "FS_project_open_close"
            xcol: "date"
            layout:
              yaxis: 
                  title: "open close operation/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_project.csv"
            traces:
              - trace:
                  name:   "OpenClose"
                  ycol: "MOpenClose_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"

- footersetelem:
    name: "$SCRATCH"
    info: "Job: #JobID#"
    graphs: 
       - graph:
            name: "FS_scratch_write"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_scratch.csv"
            traces:
              - trace:
                  name:   "wrote"
                  ycol: "MBwrite_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
       - graph:
            name: "FS_scratch_read"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_scratch.csv"
            traces:
              - trace:
                  name:   "read"
                  ycol: "MBread_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"
       - graph:
            name: "FS_scratch_open_close"
            xcol: "date"
            layout:
              yaxis: 
                  title: "open close operation/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_scratch.csv"
            traces:
              - trace:
                  name:   "OpenClose"
                  ycol: "MOpenClose_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"

- footersetelem:
    name: "$DATA"
    info: "Job: #JobID#"
    graphs: 
       - graph:
            name: "FS_fastdata_write"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_fastdata.csv"
            traces:
              - trace:
                  name:   "wrote"
                  ycol: "MBwrite_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
       - graph:
            name: "FS_fastdata_read"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_fastdata.csv"
            traces:
              - trace:
                  name:   "read"
                  ycol: "MBread_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"
       - graph:
            name: "FS_fastdata_open_close"
            xcol: "date"
            layout:
              yaxis: 
                  title: "open close operation/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_fastdata.csv"
            traces:
              - trace:
                  name:   "OpenClose"
                  ycol: "MOpenClose_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"

- footersetelem:
    name: "$HOME"
    info: "Job: #JobID#"
    graphs: 
       - graph:
            name: "FS_home_write"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_home.csv"
            traces:
              - trace:
                  name:   "wrote"
                  ycol: "MBwrite_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
       - graph:
            name: "FS_home_read"
            xcol: "date"
            layout:
              yaxis: 
                  title: "MiB/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_home.csv"
            traces:
              - trace:
                  name:   "read"
                  ycol: "MBread_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"
       - graph:
            name: "FS_home_open_close"
            xcol: "date"
            layout:
              yaxis: 
                  title: "open close operation/s"
            datapath: "data/projects/#Project#/#Owner#/FSusage_#JobID#_home.csv"
            traces:
              - trace:
                  name:   "OpenClose"
                  ycol: "MOpenClose_sec"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B000"
                  
                  

