# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer CPU
############
- footersetelem:
    name: "Nodes"
    info: "Feature: #Feature#, Status: #Status#, Substatus: #Substatus#"
    graphs: 
       - graph:
            name: "count"
            xcol: "date"
            layout:
              yaxis: 
                  title: "#nodes"
            datapath: "data/_sysstat/sysstat_#Feature##Status##Substatus#.csv"
            traces:
              - trace:
                  name:   "# nodes"
                  ycol: "count"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
                  
- footersetelem:
    name: "Load"
    info: "Feature: #Feature#, Status: #Status#, Substatus: #Substatus#"
    graphs: 
       - graph:
            name: "load"
            xcol: "date"
            layout:
              yaxis: 
                  title: "avg. load/node"
            datapath: "data/_sysstat/sysstat_#Feature##Status##Substatus#_minmax.csv"
            traces:
              - trace:
                  name:   "avgloadnode"
                  ycol: "load"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
                  
- footersetelem:
    name: "Cores"
    info: "Feature: #Feature#, Status: #Status#, Substatus: #Substatus#"
    graphs: 
       - graph:
            name: "usedcores"
            xcol: "date"
            layout:
              yaxis: 
                  title: "# avg. used cores"
            datapath: "data/_sysstat/sysstat_#Feature##Status##Substatus#_minmax.csv"
            traces:
              - trace:
                  name:   "# avgusedcores"
                  ycol: "cores"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#B00000"
                  
- footersetelem:
    name: "Memory"
    info: "Feature: #Feature#, Status: #Status#, Substatus: #Substatus#"
    graphs: 
       - graph:
            name: "usedmemory"
            xcol: "date"
            layout:
              yaxis: 
                  title: "# avg. used memory (GiB)"
            datapath: "data/_sysstat/sysstat_#Feature##Status##Substatus#_minmax.csv"
            traces:
              - trace:
                  name:   "avgerage total memory used"
                  ycol: "mem"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#C00000"
                  
- footersetelem:
    name: "Total"
    info: "Feature: #Feature#, Status: #Status#, Substatus: #Substatus#"
    graphs: 
       - graph:
            name: "totalcores"
            xcol: "date"
            layout:
              yaxis: 
                  title: "# avg.tot.Cores"
            datapath: "data/_sysstat/sysstat_#Feature##Status##Substatus#.csv"
            traces:
              - trace:
                  name:   "average # total cores"
                  ycol: "totalcores"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#B00000"
       - graph:
            name: "totalmemory"
            xcol: "date"
            layout:
              yaxis: 
                  title: "# avg. total memory (GiB)"
            datapath: "data/_sysstat/sysstat_#Feature##Status##Substatus#.csv"
            traces:
              - trace:
                  name:   "average total memory"
                  ycol: "totalmem"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#C00000"


