annotations:
    - x: 7.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA0'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: 
          - "gpu"
          - "cpu"
        GPU Node:
          - 1
          - 0
    - x: 23.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA1-GPU1'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: "gpu"
        GPU Node:
          - 1
    - x: 23.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA1'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: "cpu"
        GPU Node:
          - 0
    - x: 39.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA2'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: 
          - "gpu"
          - "cpu"
        GPU Node:
          - 1
          - 0
    - x: 55.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA3-GPU0'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: "gpu"
        GPU Node:
          - 1
    - x: 55.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA3'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: "cpu"
        GPU Node:
          - 0
    - x: 71.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA4'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: 
          - "gpu"
          - "cpu"
        GPU Node:
          - 1
          - 0
    - x: 87.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA5-GPU3'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: "gpu"
        GPU Node:
          - 1
    - x: 87.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA5'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: "cpu"
        GPU Node:
          - 0
    - x: 103.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA6'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: 
          - "gpu"
          - "cpu"
        GPU Node:
          - 1
          - 0
    - x: 119.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA7-GPU2'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: "gpu"
        GPU Node:
          - 1
    - x: 119.5
      y: 0
      xref: 'x'
      yref: 'paper'
      text: 'NUMA7'
      showarrow: false
      font: 
        size: 10
        color: 'rgb(70, 70, 70)'
      align: 'center'
      bordercolor: 'rgb(70, 70, 70)'
      borderwidth: 1
      bgcolor: '#ffffff'
      xanchor: 'center'
      yanchor: 'top'
      yshift: -5
      show_pattern: 
        Queue: "cpu"
        GPU Node:
          - 0
shapes:
    - type: 'rect'
      xref: 'x'
      yref: "paper"
      x0: 15.5
      y0: -0.5
      x1: 31.5
      y1: 1
      layer: 'below'
      # label:
      #   text: "NUMA1->GPU1"
      #   textposition: "bottom center"
      #   font:
      #     color: 'rgb(0, 0, 0)'
      #   yanchor: top
      line:
        color: 'rgb(170, 170, 170)'
        width: 1
      fillcolor: 'rgb(170, 170, 170)'
      # opacity: 0.3
      show_pattern: 
        Queue: 
          - "gpu"
          - "cpu"
        GPU Node:
          - 1
          - 0
    - type: 'rect'
      xref: 'x'
      yref: "paper"
      x0: 47.5
      y0: -0.5
      x1: 63.5
      y1: 1
      layer: 'below'
      # label:
      #   text: "NUMA3->GPU0"
      #   textposition: "bottom center"
      #   font:
      #     color: 'rgb(0, 0, 0)'
      #   yanchor: top
      line:
        color: 'rgb(170, 170, 170)'
        width: 1
      fillcolor: 'rgb(170, 170, 170)'
      # opacity: 0.2
      show_pattern: 
        Queue: 
          - "gpu"
          - "cpu"
        GPU Node:
          - 1
          - 0
    - type: 'rect'
      xref: 'x'
      yref: "paper"
      x0: 79.5
      y0: -0.5
      x1: 95.5
      y1: 1.0
      layer: 'below'
      # label:
      #   text: "NUMA5->GPU3"
      #   textposition: "middle center"
      #   font:
      #     color: 'rgb(0, 0, 0)'
      #   yanchor: top
      line:
        color: 'rgb(170, 170, 170)'
        width: 1
      fillcolor: 'rgb(170, 170, 170)'
      # opacity: 0.2
      show_pattern: 
        Queue: 
          - "gpu"
          - "cpu"
        GPU Node:
          - 1
          - 0
    - type: 'rect'
      xref: 'x'
      yref: "paper"
      x0: 111.5
      y0: -0.5
      x1: 127.5
      y1: 1
      layer: 'below'
      # label:
      #   text: "NUMA7->GPU2"
      #   textposition: "bottom center"
      #   font:
      #     color: 'rgb(0, 0, 0)'
      #   yanchor: top
      line:
        color: 'rgb(170, 170, 170)'
        width: 1
      fillcolor: 'rgb(170, 170, 170)'
      # opacity: 0.4
      show_pattern: 
        Queue: 
          - "gpu"
          - "cpu"
        GPU Node:
          - 1
          - 0
