############
# Footer CPU
############
- footersetelem:
    name: "Jobs up to 10 nodes"
    info: "Memory Class: #Memory Class#"
    graphs: 
       - graph:
            name: "mem"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Number of nodes"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/_sysstat/sysstat_hist_maxmem_#Memory Class#.csv"
            traces:
              - trace:  
                  name:   "1"
                  ycol:   "n_1"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#a50026"
              - trace:  
                  name:   "2"
                  ycol:   "n_2"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#d73027"
              - trace:  
                  name:   "3"
                  ycol:   "n_3"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#f46d43"
              - trace:  
                  name:   "4"
                  ycol:   "n_4"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#fdae61"
              - trace:  
                  name:   "5"
                  ycol:   "n_5"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#fee08b"
              - trace:  
                  name:   "6"
                  ycol:   "n_6"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#d9ef8b"
              - trace:  
                  name:   "7"
                  ycol:   "n_7"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#a6d96a"
              - trace:  
                  name:   "8"
                  ycol:   "n_8"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#66bd63"
              - trace:  
                  name:   "9"
                  ycol:   "n_9"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#1a9850"
              - trace:  
                  name:   "10"
                  ycol:   "n_10"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#006837"
- footersetelem:
    name: "Jobs up to 256 nodes"
    info: "Memory Class: #Memory Class#"
    graphs: 
       - graph:
            name: "mem"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Number of nodes"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/_sysstat/sysstat_hist_maxmem_#Memory Class#.csv"
            traces:
              - trace:  
                  name:   "12"
                  ycol:   "n_12"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#d73027"
              - trace:  
                  name:   "16"
                  ycol:   "n_16"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#f46d43"
              - trace:  
                  name:   "24"
                  ycol:   "n_24"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#fdae61"
              - trace:  
                  name:   "32"
                  ycol:   "n_32"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#fee08b"
              - trace:  
                  name:   "64"
                  ycol:   "n_64"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#ffffbf"
              - trace:  
                  name:   "96"
                  ycol:   "n_96"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#d9ef8b"
              - trace:  
                  name:   "128"
                  ycol:   "n_128"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#a6d96a"
              - trace:  
                  name:   "192"
                  ycol:   "n_192"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#66bd63"
              - trace:  
                  name:   "256"
                  ycol:   "n_256"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#1a9850"
- footersetelem:
    name: "Jobs from 384 nodes"
    info: "Memory Class: #Memory Class#"
    graphs: 
       - graph:
            name: "mem"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Number of nodes"
              legend:
                  x: "0.02"
                  xanchor: "left"
                  y: "0.98"
                  yanchor: "top"
            datapath: "data/_sysstat/sysstat_hist_maxmem_#Memory Class#.csv"
            traces:
              - trace:  
                  name:   "384"
                  ycol:   "n_384"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#d73027"
              - trace:  
                  name:   "512"
                  ycol:   "n_512"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#fc8d59"
              - trace:  
                  name:   "768"
                  ycol:   "n_768"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#fee08b"
              - trace:  
                  name:   "1024"
                  ycol:   "n_1024"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#ffffbf"
              - trace:  
                  name:   "2048"
                  ycol:   "n_2048"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#d9ef8b"
              - trace:  
                  name:   "4096"
                  ycol:   "n_4096"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#91cf60"
              - trace:  
                  name:   "8192"
                  ycol:   "n_8192"
                  yaxis:  "y"
                  type:   "line"
                  stackgroup: "mem"
                  color:  "#1a9850"


