# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

############
# Footer CPU
############
- footersetelem:
    name: "Power"
    info: "System-Name: #System-Name#"
    graphs: 
       - graph:
            name: "power"
            xcol: "date"
            layout:
              yaxis: 
                  title: "System Power Usage"
            datapath: "data/_sysstat/sysenvstat_#System-Name#.csv"
            traces:
              - trace:
                  name:   "System Power Usage (kW)"
                  ycol: "power"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B0B0"

- footersetelem:
    name: "Water Cooling Temperature"
    info: "System-Name: #System-Name#"
    graphs: 
       - graph:
            name: "water-temp"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Water Cooling Temperature (&deg;C)"
            datapath: "data/_sysstat/sysenvstat_#System-Name#.csv"
            traces:
              - trace:
                  name:   "Water Cooling Outlet Temperature (&deg;C)"
                  ycol: "water_outlet_temp"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#A00000"
              - trace:
                  name:   "Water Cooling Inlet Temperature (&deg;C)"
                  ycol: "water_inlet_temp"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#0000B0"

- footersetelem:
    name: "Water Cooling Spec"
    info: "System-Name: #System-Name#"
    graphs: 
       - graph:
            name: "water-flowrate"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Water Cooling Flow rate (m3/hour)"
            datapath: "data/_sysstat/sysenvstat_#System-Name#.csv"
            traces:
              - trace:
                  name:   "Water Cooling Flow rate (m3/hour)"
                  ycol: "water_flowrate"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#0000B0"
       - graph:
            name: "water-power"
            xcol: "date"
            layout:
              yaxis: 
                  title: "Water Cooling Power (kW)"
            datapath: "data/_sysstat/sysenvstat_#System-Name#.csv"
            traces:
              - trace:
                  name:   "Water Cooling Power (kW)"
                  ycol: "water_power"
                  yaxis:  "y"
                  type:   "scatter"
                  color:  "#00B0B0"
                  
