# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

%YAML 1.1
---
#
# LLview da Configuration file
#
# definition of databases (default folders when it is not given in command line)
paths:
  dbdir: './perm/db'
  archdir: './arch/db'

archive:
  archive_data: yes
  remove_data: yes

options:
  parallel: yes
  parwaitsec: 40   # timeout in sec

# Definition of data types (used in SQL definitions of tables)
datatypes:
  %include "conf_common/datatypes.yaml"

databases:

  # jobs database, must be the first DB in list (defines the jobmap structure)
  %include "conf_jobs/jobs.yaml"

  # job step info
  %include "conf_jobs/jobstep.yaml"

  # job errmsg info
  # %include "conf_jobs/joberr.yaml"

  # reservations
  %include "conf_jobs/reservations.yaml"

  # classes
  %include "conf_jobs/classes.yaml"
  
  # load, memory, status of nodes 
  %include "conf_cpu/loadmem.yaml"

  # # per core info
  # %include "conf_cpu/pcpucores.yaml"

  # interconnect map info
  %include "conf_fabric/icmap.yaml"

  # # interconnect info (fabric)
  # %include "conf_fabric/fabric.yaml"

  # # file system usage (fsusage)  
  # #  %include "conf_fs/fsusage.yaml"
  # %include "conf_fs/fsusage_per_fs.yaml"

  # # GPU usage
  # %include "conf_gpu/gpu.yaml"

  # # SYSTEM info
  # %include "conf_sysstat/sysstat.yaml"
  # %include "conf_sysstat/nodeerr.yaml"

  #  DB for internal statitics of DB usage
  %include "conf_internal/DBstat.yaml"

  #  DB for internal statitics about workflow step timings
  %include "conf_internal/step_timings.yaml"
  %include "conf_internal/transfer.yaml"

  #  DB for account mapping data
  %include "conf_roles/accountmap.yaml"
  
  #  DB for jobreporting
  %include "conf_jobreport/jobreport_databases.yaml"

  #  DB for LMLstat
  %include "conf_lmlstat/lmlstat_databases.yaml"

  # #  DB for JuMonC
  %include "conf_jumonc/jumonc_databases.yaml"


# config options for jobreporting
jobreport:
  paths:
    tmpdir: './tmp'
    outputdir: './tmp/jobreport/data'
  %include "conf_jobreport/jobreport_main.yaml"

# config options for lmlstat (system status file in Client-LML format)
lmlstat:
  %include "conf_lmlstat/lmlstat_main.yaml"
  


# TODO
# - ended column (done) 
# - JURI: project/user conf (done)
# - mentor (done)
# - support/active projects
# - queued  (support/project/user)
# - queued_details (support/project/user)
# - support/nodes
