# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- dataset:
    name: roles_user_active_dat
    set:        roles
    filepath:   '$outputdir/sec_files/user_active_list.dat'
    columns:        'wsaccount,id,project,project'
    header:         '[active_user]'
    format_str:      '%s[%s@%s] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="U" and numjobs > 0'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_active_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat

- dataset:
    name: roles_user_nonactive_dat
    set:        roles
    filepath:   '$outputdir/sec_files/user_nonactive_list.dat'
    columns:        'wsaccount,id,project,project'
    header:         '[nonactive_user]'
    format_str:      '%s[%s@%s] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="U" and numjobs IS NULL'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_active_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat

- dataset:
    name: roles_PI_active_dat
    set:        roles
    filepath:   '$outputdir/sec_files/PI_active_list.dat'
    columns:        'wsaccount,id,project,project'
    header:         '[active_pi]'
    format_str:      '%s[%s@%s] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="L" and numjobs>0'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_active_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat

- dataset:
    name: roles_PI_nonactive_dat
    set:        roles
    filepath:   '$outputdir/sec_files/PI_nonactive_list.dat'
    columns:        'wsaccount,id,project,project'
    header:         '[nonactive_pi]'
    format_str:      '%s[%s@%s] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="L" and numjobs is NULL'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_active_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat
    
- dataset:
    name: roles_COPI_active_dat
    set:        roles
    filepath:   '$outputdir/sec_files/COPI_active_list.dat'
    columns:        'wsaccount,id,project,project'
    header:         '[active_copi]'
    format_str:      '%s[%s@%s] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="C" and numjobs>0'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_active_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat

- dataset:
    name: roles_COPI_nonactive_dat
    set:        roles
    filepath:   '$outputdir/sec_files/COPI_nonactive_list.dat'
    columns:        'wsaccount,id,project,project'
    header:         '[nonactive_copi]'
    format_str:      '%s[%s@%s] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="C" and numjobs is NULL'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_active_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat

- dataset:
    name: roles_PA_active_dat
    set:        roles
    filepath:   '$outputdir/sec_files/PA_active_list.dat'
    columns:        'wsaccount,id,project,project'
    header:         '[active_pa]'
    format_str:      '%s[%s@%s] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="A" and numjobs>0'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_active_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat

- dataset:
    name: roles_PA_nonactive_dat
    set:        roles
    filepath:   '$outputdir/sec_files/PA_nonactive_list.dat'
    columns:        'wsaccount,id,project,project'
    header:         '[nonactive_pa]'
    format_str:      '%s[%s@%s] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="A" and numjobs is NULL'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_active_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat

- dataset:
    name: roles_mentor_dat
    set:        roles
    filepath:   '$outputdir/sec_files/mentor_list.dat'
    columns:        'wsaccount,id'
    header:         '[mentor]'
    format_str:      '%s[] = %s'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="M"'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_aggr_l1_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat
    
- dataset:
    name: roles_support_dat
    set:        roles
    filepath:   '$outputdir/sec_files/support_list.dat'
    columns:        'wsaccount,id'
    header:         '[supporter]'
    format_str:      '%s[%s] = support/index.html'
    format:         'dat'
    column_ts:      'u_ts'
    sql_where:      'kind="S"'
    renew:          'daily(14:20)'
    data_database:   jobreport
    data_table:      rolemap_aggr_l1_stat
    stat_database:   jobreport_stat_roles
    stat_table:      datasetstat
