- dataset:
    name: projstat_csv
    set:        sysstat
    FORALL:     'P:VAR_projectlist'
    filepath:   '$outputdir/projects/$P/projstat.csv'
    columns:        'ts,numjobs_sum, 
                     numnodes_min,numnodes_avg,numnodes_max, 
                     wall_min,wall_avg,wall_max, 
                     runtime_min,runtime_avg,runtime_max,
                     wallusage_avg,
                     load_min,load_avg,load_max,
                     usage_min,usage_avg,usage_max,
                     used_cores_min,used_cores_avg,used_cores_max,
                     gpu_util_min,gpu_util_avg,gpu_util_max'
    header:         'date,numjobs,numnodes,wall,runtime,wallusage,load,usage,used_cores,gpu_util'
    column_convert: 'ts->todate_1_wo_time, 
                     wall_min->hourfrac,wall_avg->hourfrac,wall_max->hourfrac, 
                     runtime_min->hourfrac,runtime_avg->hourfrac,runtime_max->hourfrac,
                     wallusage_min->toPercent,wallusage_avg->toPercent,wallusage_max->toPercent,
                     usage_min->toPercent,usage_avg->toPercent,usage_max->toPercent'
    column_filemap: 'P:account'
    format_str:      '%s,%d, %f;%.2f;%f,%.2f;%.2f;%.2f,%.2f;%.2f;%.2f,%.2f,%.2f;%.2f;%.2f,%.2f;%.2f;%.2f,%.2f;%.2f;%.2f,%.2f;%.2f;%.2f'
    column_ts:      'ts'
    format:         'csv'
    sql_where:      '_time_res=1440'
    renew:          'always'
#    renew:          'daily(14:00)'
    data_database:   jobreport
    data_table:      projstat_per_project
    stat_database:   jobreport_stat_projstat
    stat_table:      datasetstat_projstat
