# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- dataset:
    name: sysenvstat_csv
    set:        sysstat
    FORALL:     'S:VAR_sysenvstat_system'
    filepath:   '$outputdir/_sysstat/sysenvstat_${S}.csv'
    columns:        'ts,power_avg,water_flowrate_avg,water_inlet_temp_avg,water_outlet_temp_avg,water_power_avg'
    header:         'date,power,water_flowrate,water_inlet_temp,water_outlet_temp,water_power'
    column_convert: 'ts->todate_1'
    column_filemap: 'S:sysname'
    format_str:      '%s,%f,%f,%f,%f,%f'
    column_ts:      'ts'
    format:         'csv'
    renew:          'daily(14:00)'
    time_aggr:      'span'
    data_database:   sysstatstate
    data_table:      sysstat_time_aggr
    stat_database:   jobreport_stat_sysstat
    stat_table:      datasetstat_env
    
- dataset:
    name: sysrackpwr_csv
    set:        sysstat
    FORALL:     'S:VAR_sysrackpwr_system'
    filepath:   '$outputdir/_sysstat/sysrackpwr_${S}.csv'
    columns:        'ts,power_avg'
    header:         'date,power'
    column_convert: 'ts->todate_1, power_avg->toThousand'
    column_filemap: 'S:name'
    format_str:      '%s,%f'
    column_ts:      'ts'
    format:         'csv'
    renew:          'always'
    time_aggr:      'span'
    data_database:   sysstatstate
    data_table:      rackpwr_time_aggr
    stat_database:   jobreport_stat_sysstat
    stat_table:      datasetstat_pwr

- dataset:
    name: syscorepattern_csv
    set:        sysstat
    FORALL:     'P:VAR_corepattern'
    filepath:   '$outputdir/_sysstat/cp/syscorepattern_${P}.csv'
    columns:        'ts,coreid,usage1_min,usage1_avg,usage1_max,usage2_min,usage2_avg,usage2_max'
    header:         'date,coreid,usage1,usage2'
    column_convert: 'ts->todate_1,usage1_min->toPercent,usage1_avg->toPercent,usage1_max->toPercent,usage2_min->toPercent,usage2_avg->toPercent,usage2_max->toPercent'
    column_filemap: 'P:pid'
    format_str:      '%s,%d,%f;%f;%f,%f;%f;%f'
    column_ts:      'ts'
    format:         'csv'
    renew:          'always'
    sqldebug:       'yes'
    data_database:   pcpucoresstate
    data_table:      pcpucores_time_aggr_coreid_span_avg
    stat_database:   jobreport_stat_sysstat
    stat_table:      datasetstat
    mngt_actions:   'remove_older_3days'

