# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- dataset:
    name: fabric_node_dat
    set:        fabric
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/Fabric_${J}_node.dat'
    columns:        'jobid,ts,nodeid,mbin,mbout,pckin,pckout'
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    format:         'dat'
    format_str:      '%-10s %10d %12s %10.3f %10.3f %10.3f %10.3f'
    format_header:   '%-10s %10s %12s %10s %10s %10s %10s'
    column_filemap: 'J:jobid'
    data_database:   fabricstate
    data_table:      fabric_by_jobid_nodeid_ts
    stat_database:   jobreport_stat_fabric
    stat_table:      datasetstat_node_dat
    mngt_actions:   'compress_finished_files,archive_jobs_files'

- dataset:
    name: fabric_csv
    set:        fabric
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/Fabric_${J}.csv'
    columns:        'ts,mbin_min,mbin_avg,mbin_max,mbout_min,mbout_avg,mbout_max,pckin_min,pckin_avg,pckin_max,pckout_min,pckout_avg,pckout_max'
    header:         'date,mbin,mbout,pckin,pckout'
    column_convert: 'ts->todate_1,mbin_min->cut3digits,mbin_avg->cut3digits,mbin_max->cut3digits
                                  mbout_min->cut3digits,mbout_avg->cut3digits,mbout_max->cut3digits
                                  pckin_min->cut3digits,pckin_avg->cut3digits,pckin_max->cut3digits
                                  pckout_min->cut3digits,pckout_avg->cut3digits,pckout_max->cut3digits'
    format_str:      '%s,%f;%f;%f,%f;%f;%f,%f;%f;%f,%f;%f;%f'
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    format:         'csv'
    column_filemap: 'J:jobid'
    data_database:   fabricstate
    data_table:      fabric_aggr_by_jobid_ts
    stat_database:   jobreport_stat_fabric
    stat_table:      datasetstat_csv
    mngt_actions:   'compress_finished_files,archive_jobs_files'

  # incremental update of files:
  # - internal stat table stores ts of last added entry to file
  # - column_filemap: specifies mapping of table column to variable
  #                   name used in filename pattern
  #                   limitation: only one column allowed
  
# System Interconnect Overview
###############################

- dataset:
    name: sysstat_interconnect_csv
    set:        interconnect
    filepath:   '$outputdir/_sysstat/sysstat_interconnect_span.csv'
    columns:        'ts,mbin_sum,mbout_sum,pckin_sum,pckout_sum'
    header:         'date,mbin_sum,mbout_sum,pckin_sum,pckout_sum'
    format_str:      '%s,%f,%f,%d,%d'
    column_convert: 'ts->todate_1'
    format:         'csv'
    column_ts:      'ts'
    time_aggr:      'span'
    renew:          'daily(14:00)'
    data_database:   fabricstate
    data_table:      fabric_time_aggr_ts
    stat_database:   jobreport_stat_fabric
    stat_table:      datasetstat
