###############################
# Support
###############################
- dataset:
    name:        support_all_csv
    set:         csv_support
    filepath:    '$outputdir/support/all.csv.gz'
    format:      'csv'
    create_empty_files: yes
    sql_where:   'owner!="unknown"'
    column_ts:   'ts'
    # max_entries: 5000
    csv_delimiter: ';'
    renew:       'always'
    order:       "jobid DESC"
    sqldebug:    'yes'
    stat_table:  datasetstat_support
    %include "./jobreport_datafiles_json_common_joblist.yaml"

# - dataset:
#     name: support_running_json
#     set:        json_support
#     filepath:   '$outputdir/support/running.json.gz'
#     sql_where:  'owner!="unknown"'
#     table_cache: alljobs
#     table_cache_par_level: 8
#     selecttimevar:   lastts
#     selecttimerange: TS_NOW-120,TS_NOW+1
#     stat_table: datasetstat_support
#     order:      "jobid DESC"
#     format:     'json'
#     %include "./jobreport_datafiles_json_common_joblist.yaml"

# - dataset:
#     name: support_today_json
#     set:        json_support
#     filepath:   '$outputdir/support/today.json.gz'
#     sql_where:  'owner!="unknown"'
#     table_cache: alljobs
#     selecttimevar:   lastts
#     selecttimerange: TS_STARTOFTODAY,TS_NOW-120
#     stat_table:  datasetstat_support
#     order:       "jobid DESC"
#     format:      'json'
#     %include "./jobreport_datafiles_json_common_joblist.yaml"

# - dataset:
#     name: support_days_json
#     set:        json_support
#     FORALL:     'D:(001,002,003,004,005,006,007,008,009,010,011,012,013,014,014,015,016,017,018,019,020,021)'
#     filepath:   '$outputdir/support/jobbyday_$D.json.gz'
#     sql_where:  'owner!="unknown"'
#     table_cache: alljobs
#     selecttimevar:   lastts
#     selecttimerange: TS_STARTOFTODAY-($D*24*3600),TS_STARTOFTODAY-(($D-1)*24*3600)
#     stat_table:  datasetstat_support
#     order:       "jobid DESC"
#     format:      'json'
#     %include "./jobreport_datafiles_json_common_joblist.yaml"

- dataset:
    name: support_jobtoday
    set:        json_support
    filepath:   '$outputdir/_queued/mapjobid_to_day.csv.gz'
    sql_where:  'owner!="unknown" AND (lastts>TS_STARTOFTODAY-(21*24*3600))'
    data_table_join_col: jobid 
    data_table:      "joblist"
    data_database:   jobreport
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    format:         'csv'
    column_convert: 'lastts->jobdays_sincenow'
    columns:        'jobid, lastts'
    column_ts:      'lastts'
    header:         'jobid,day'
    format_str:      '%s,%d'
    
- dataset:
    name:            support_mentorlist_json
    set:             json_support
    filepath:       '$outputdir/support/mentorlist.json.gz'
    data_database:   accountmap
    data_table:     "mentorlist"
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    format:         'json'
    columns:        'wsaccount, cnt, projects'
   
- dataset:
    name: support_queueddetails_json
    set:        json_queued
    filepath:   '$outputdir/support/queueddetails.json.gz'
    data_database:   jobreport
    data_table:      queuedjobs
    table_cache:     queuedjobs
    table_cache_par_level: 4
    selecttimevar:   ts
    selecttimerange: TS_NOW-120,TS_NOW+1
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    format:         'json'
    columns:        'userprio, jobid, ts, owner, account, mentor, queue, numnodes, state, qos, wall, restart, posinqueue, waittime, queuedate, timetostart, 
                     runtime, starttime, endtime, reason, dependency, chainid, wf_id, wf_jid, ArrayJobId, ArrayTaskId, resid, detailedstatus'
    column_convert: 'wall->hhmm_short,waittime->hhmmss_short,timetostart->hhmm_short,runtime->hhmm_short,reason->wrapstr50'
    order: "jobid DESC, userprio DESC"

- dataset:
    name: support_workflows_json
    set:        json_queued
    filepath:   '$outputdir/support/workflows.json.gz'
    data_database:   jobreport
    data_table:      workflows,workflows_spec
    data_table_join_col: wf_id
    table_cache:     workflows
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    format:         'json'
    order: "wf_id DESC"
    %include "./jobreport_datafiles_workflow_columns.yaml"

- dataset:
    name: support_active_user
    set:        mapstat
    filepath:   '$outputdir/support/active_user.json.gz'
    data_database:   jobreport
    data_table:      alljobs_stat
    table_cache:     mapstat
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    sql_where:      'owner!="unknown"'
    format:         'json'
    columns:        'owner,account,mentor,numjobs,nh,numnodes_avg,numqueuedjobs,qnh,qnumnodes_avg'
    column_convert: 'numjobs->onlygtnull, nh->onlygtnull, numnodes_avg->onlygtnull, numqueuedjobs->onlygtnull, qnumnodes_avg->onlygtnull'
    order: "owner, account, mentor"
    
- dataset:
    name: support_all_user
    set:        alluser
    filepath:   '$outputdir/support/all_user.json.gz'
    data_database:   jobreport
    data_table:      rolemap_aggr_l1_stat
    table_cache:     alluser
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    sql_where:      'kind="U"'
    format:         'json'
    columns:        'id,wsaccount,numjobs,numprojects,projects'
    column_convert: 'projects->as_array'
    order: "id"

- dataset:
    name: support_all_mentors
    set:        allmentors
    filepath:   '$outputdir/support/all_mentors.json.gz'
    data_database:   jobreport
    data_table:      rolemap_aggr_l1_stat
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    sql_where:      'kind="M"'
    format:         'json'
    columns:        'id,wsaccount,numjobs,numprojects,projects'
    column_convert: 'projects->as_array'

- dataset:
    name: support_all_PIs
    set:        allPIs
    filepath:   '$outputdir/support/all_PIs.json.gz'
    data_database:   jobreport
    data_table:      rolemap_aggr_l1_stat
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    sql_where:      'kind="L"'
    format:         'json'
    columns:        'id,wsaccount,numjobs,numprojects,projects'
    column_convert: 'projects->as_array'

- dataset:
    name: support_all_PAs
    set:        allPAs
    filepath:   '$outputdir/support/all_PAs.json.gz'
    data_database:   jobreport
    data_table:      rolemap_aggr_l1_stat
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    sql_where:      'kind="A"'
    format:         'json'
    columns:        'id,wsaccount,numjobs,numprojects,projects'
    column_convert: 'projects->as_array'

- dataset:
    name: support_all_projects
    set:        allProjects
    filepath:   '$outputdir/support/projectlist.json.gz'
    data_database:   jobreport
    data_table:      projstat_per_project_aggr
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    sql_where:      'account!="0"'
    format:         'json'
    columns:        'account,ts,numjobs_sum,numnodes_min, numnodes_avg, numnodes_max, wall_min, wall_avg,
                     wall_max, runtime_min, runtime_avg, runtime_max, wallusage_min,
                     wallusage_avg, wallusage_max, load_min, load_avg, load_max, usage_min,
                     usage_avg, usage_max, used_cores_min, used_cores_avg, used_cores_max,
                     gpu_util_min, gpu_util_avg, gpu_util_max'
    column_convert: 'ts->todate_std_hhmm,
                     wall_min->hhmmss_short,wall_avg->hhmmss_short,wall_max->hhmmss_short,
                     runtime_min->hhmmss_short,runtime_avg->hhmmss_short,runtime_max->hhmmss_short,
                     wallusage_min->toPercent,wallusage_avg->toPercent,wallusage_max->toPercent,
                     usage_min->toPercent,usage_avg->toPercent,usage_max->toPercent'
    order: "account ASC"
    
- dataset:
    name: support_cb_csv
    set:        csv_cb
    filepath:   '$outputdir/cb/cb_list.csv.gz'
    data_database:   CB
    column_ts:   'max_ts'
    csv_delimiter: ';'
    renew:       'always'
    data_table:      cb_benchmarks
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    sqldebug:    'yes'
    format:         'csv'
    columns:        'name,min_ts,max_ts,count'
    column_convert: 'min_ts->todate_std_hhmm,max_ts->todate_std_hhmm'

%include "../../conf_cb/tablecsv_cb.yaml"
%include "../../conf_cb/csv_cb.yaml"