###############################
# Mentor
###############################
- dataset:
    name: mentor_running_json
    set:                 json_mentor
    FORALL:             'M:VAR_mentor'
    filepath:           '$outputdir/mentors/mentor_$M/running.json.gz'
    column_filemap:     'M:mentor'
    format:             'json'
    sql_where:          'mentor!="-"'
    table_cache:         alljobs
    selecttimevar:       lastts
    selecttimerange:    TS_NOW-120,TS_NOW+1
    checksumvar:        lastts
    create_empty_files: yes
    data_database:      jobreport
    data_table:         joblist
    stat_database:      jobreport_json_stat
    stat_table:         datasetstat_mentor_running
    order:              "jobid DESC"
    %include "./jobreport_datafiles_json_common_joblist.yaml"

- dataset:
    name: mentor_today_json
    set:                 json_mentor
    FORALL:             'M:VAR_mentor'
    filepath:           '$outputdir/mentors/mentor_$M/today.json.gz'
    column_filemap:     'M:mentor'
    format:             'json'
    sql_where:          'mentor!="-"'
    table_cache:         alljobs
    selecttimevar:       lastts
    selecttimerange:    TS_STARTOFTODAY,TS_NOW-120
    checksumvar:        lastts
    create_empty_files: yes
    data_database:      jobreport
    data_table:         joblist
    stat_database:      jobreport_json_stat
    stat_table:         datasetstat_mentor_today
    order:              "jobid DESC"
    %include "./jobreport_datafiles_json_common_joblist.yaml"

- dataset:
    name: mentor_threeweeks_json
    set:                 json_mentor
    FORALL:             'M:VAR_mentor'
    filepath:           '$outputdir/mentors/mentor_$M/threeweeks.json.gz'
    column_filemap:     'M:mentor'
    format:             'json'
    sql_where:          'mentor!="-"'
    table_cache:         alljobs
    selecttimevar:       lastts
    selecttimerange:    TS_STARTOFTODAY-(21)*24*3600, TS_STARTOFTODAY
    checksumvar:        lastts
    create_empty_files: yes
    data_database:      jobreport
    data_table:         joblist
    stat_database:      jobreport_json_stat
    stat_table:         datasetstat_mentor_threeweeks
    order:              "jobid DESC"
    %include "./jobreport_datafiles_json_common_joblist.yaml"

- dataset:
    name: mentor_queueddetails_json
    set:             json_queued
    FORALL:             'M:VAR_mentor'
    filepath:           '$outputdir/mentors/mentor_$M/queueddetails.json.gz'
    column_filemap:     'M:mentor'
    data_database:   jobreport
    data_table:      queuedjobs
    table_cache:     queuedjobs
    selecttimevar:   ts
    selecttimerange: TS_NOW-120,TS_NOW+1
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    format:         'json'
    columns:        'userprio, jobid, ts, owner, account, mentor, queue, numnodes, state, qos, wall, restart, posinqueue, waittime, queuedate, timetostart, 
                     runtime, starttime, endtime, reason, dependency, chainid, wf_id, wf_jid, ArrayJobId, ArrayTaskId, resid, detailedstatus'
    column_convert: 'wall->hhmm_short,waittime->hhmmss_short,timetostart->hhmm_short,runtime->hhmm_short'
    order: "jobid DESC, userprio DESC"

- dataset:
    name: mentor_workflows_json
    set:        json_queued
    FORALL:          'M:VAR_mentor'
    filepath:        '$outputdir/mentors/mentor_$M/workflows.json.gz'
    column_filemap:  'M:mentor'
    data_database:   jobreport
    data_table:      workflows,workflows_spec
    data_table_join_col: wf_id
    table_cache:     workflows
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    format:         'json'
    order:          "wf_id DESC"
    %include "./jobreport_datafiles_workflow_columns.yaml"