# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

###############################
# User
###############################
- dataset:
    name: user_access_owner
    set:                 access_user
    FORALL:             'P,U:VAR_project_user'
    filepath:           '$outputdir/projects/$P/$U/.htaccess'
    format:             'access'
    column_filemap:     'P:project,U:id'
    columns:            'id,project,wsaccount'
    data_database:      accountmap
    data_table:         usermap
    table_cache:        Uusermap
    table_cache_par_level: 4
    filemode:           new 
    stat_database:      jobreport_access_stat
    stat_table:         datasetstat_user_access
    pre_rows:           '# Owner' 
    row_format:         'Require user %s\n'
    row_columns:        'wsaccount'
    %include "jobreport_datafiles_access_groupfile_support.yaml"

- dataset:
    name: user_access_pipa
    set:                 access_project
    FORALL:             'P,U:VAR_project_user'
    filepath:           '$outputdir/projects/$P/$U/.htaccess'
    format:             'access'
    column_filemap:     'P:project,U:id'
    columns:            'd1.project,d1.id,d2.wsaccount'
    data_database:       accountmap
    data_table:          usermap,pipamap
    data_table_join_col: project
    table_cache:         Upipamap
    table_cache_par_level: 4
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_user_access
    filemode:            append 
    pre_rows:           '# PI/PA' 
    row_format:         'Require user %s\n' 
    row_columns:        'wsaccount'

    
- dataset:
    name: user_access_mentor
    set:                 access_project
    FORALL:             'P,U:VAR_project_user'
    filepath:           '$outputdir/projects/$P/$U/.htaccess'
    format:             'access'
    column_filemap:     'P:project,U:id'
    columns:            'd1.project,d1.id,d2.wsaccount'
    data_database:      accountmap
    data_table:         usermap,mentormap
    data_table_join_col: project
    table_cache:        Umentormap
    table_cache_par_level: 4
    stat_database:      jobreport_access_stat
    stat_table:         datasetstat_user_access
    filemode:           append 
    pre_rows:           '# Mentor' 
    row_format:         'Require user %s\n'
    row_columns:        'wsaccount'


###############################
# Project
###############################
- dataset:
    name: project_access_pipa
    set:                 access_project
    FORALL:             'P:VAR_project'
    filepath:           '$outputdir/projects/$P/.htaccess'
    format:             'access'
    column_filemap:     'P:project'
    columns:            'project,id,wsaccount'
    data_database:       accountmap
    data_table:          pipamap
    table_cache:         Ppipamap
    table_cache_par_level: 4
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_project_access
    filemode:            new 
    pre_rows:           '# PI/PA' 
    row_format:         'Require user %s\n' 
    row_columns:        'wsaccount'
    %include "jobreport_datafiles_access_groupfile_support.yaml"

    
- dataset:
    name: project_access_mentor
    set:                 access_project
    FORALL:             'P:VAR_project'
    filepath:           '$outputdir/projects/$P/.htaccess'
    format:             'access'
    column_filemap:     'P:project'
    columns:            'project,id,wsaccount'
    data_database:      accountmap
    data_table:         mentormap
    table_cache:        Pmentormap
    table_cache_par_level: 4
    stat_database:      jobreport_access_stat
    stat_table:         datasetstat_project_access
    filemode:           append 
    pre_rows:           '# Mentor' 
    row_format:         'Require user %s\n'
    row_columns:        'wsaccount'

###############################
# Mentor
###############################
- dataset:
    name: mentor_access_mentor
    set:                 access_mentor
    FORALL:             'M:VAR_mentor'
    filepath:           '$outputdir/mentors/mentor_$M/.htaccess'
    format:             'access'
    column_filemap:     'M:wsaccount'
    columns:            'wsaccount'
    data_database:       accountmap
    data_table:          mentorlist
    table_cache:         Mmentormap
    table_cache_par_level: 1
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_mentor_access
    filemode:            new 
    pre_rows:           '# Mentor' 
    row_format:         'Require user %s\n' 
    row_columns:        'wsaccount'
    %include "jobreport_datafiles_access_groupfile_support.yaml"
    

###############################
# Support
###############################
- dataset:
    name: support_access
    set:                 access_support
    filepath:           '$outputdir/support/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    %include "jobreport_datafiles_access_groupfile_support.yaml"

###############################
# Group file
###############################
- dataset:
    name: groupfile_alluser
    set:                 access_project
    FORALL:             'P:VAR_project'
    filepath:           '$outputdir/sec_files/.htgroups'
    format:             'access'
    columns:            'alluser'
    data_database:       accountmap
    data_table:          alluser
    data_table_join_col: project
    table_cache:         Galluser
    table_cache_par_level: 1
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    pre_rows:           '# GROUPS' 
    row_format:         'alluser: %s\n' 
    row_columns:        'alluser'

- dataset:
    name: groupfile_support
    set:                 access_project
    FORALL:             'P:VAR_project'
    filepath:           '$outputdir/sec_files/.htgroups_support'
    format:             'access'
    columns:            'support'
    data_database:       accountmap
    data_table:          support
    data_table_join_col1: project
    table_cache:         Gsupport
    table_cache_par_level: 1
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new
    row_format:         'support: %s\n' 
    row_columns:        'support'

    

###############################
# Top directory files
###############################
- dataset:
    name: secfiles_access1
    set:                 access_support
    filepath:           '$outputdir/sec_files/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    rows:               'Require all denied\n' 

- dataset:
    name: secfiles_access2
    set:                 access_support
    filepath:           '$outputdir/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    rows:               'Require all denied\nHeader set Cache-Control "max-age=60, private"\n' 

- dataset:
    name: secfiles_access3
    set:                 access_support
    filepath:           '$outputdir/projects/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    rows:               'Require all denied\nHeader set Cache-Control "max-age=60, private"\n' 

- dataset:
    name: secfiles_access4
    set:                 access_support
    filepath:           '$outputdir/LLtemplates/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    rows:               'AddType text/x-handlebars-template .handlebars\nRequire all granted\n' 
    
- dataset:
    name: secfiles_access5
    set:                 access_support
    filepath:           '$outputdir/_info/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    rows:               'AddType text/x-handlebars-template .handlebars\nRequire all granted\n' 

- dataset:
    name: secfiles_access6
    set:                 access_support
    filepath:           '$outputdir/ll/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    rows:               'AddType text/x-handlebars-template .handlebars\nRequire all granted\n' 

- dataset:
    name: secfiles_access7
    set:                 access_support
    filepath:           '$outputdir/_sysstat/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    %include "jobreport_datafiles_access_groupfile_support.yaml"

- dataset:
    name: secfiles_access8
    set:                 access_support
    filepath:           '$outputdir/_queued/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    %include "jobreport_datafiles_access_groupfile_alluser.yaml"

- dataset:
    name: secfiles_access9
    set:                 access_support
    filepath:           '$outputdir/_internal/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    %include "jobreport_datafiles_access_groupfile_support.yaml"

- dataset:
    name: secfiles_access10
    set:                 access_support
    filepath:           '$outputdir/_internal/DBtab/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    %include "jobreport_datafiles_access_groupfile_support.yaml"

- dataset:
    name: secfiles_access11
    set:                 access_support
    filepath:           '$outputdir/_internal/steptimings/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    %include "jobreport_datafiles_access_groupfile_support.yaml"
    
- dataset:
    name: secfiles_access12
    set:                 access_support
    filepath:           '$outputdir/llview_batch/.htaccess'
    format:             'access'
    stat_database:       jobreport_access_stat
    stat_table:          datasetstat_support_access
    filemode:            new 
    %include "jobreport_datafiles_access_groupfile_alluser.yaml"
    
