# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

post_rows:          'Require valid-user\n# All User\nAuthGroupFile ${LLVIEW_WEB_DATA}/data/sec_files/.htgroups\nRequire group alluser\nRequire group support\n'
