# logprefix: "jureptool"
filemode: "w"
format: "%(asctime)s %(funcName)s(%(lineno)-3d): [%(levelname)-8s] %(message)s"
datefmt: "%Y-%m-%d %H:%M:%S"
level: "INFO" # Default value; Options: 'DEBUG', 'INFO', 'WARNING', 'ERROR' from more to less verbose logging


