# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

steptimings:
  tables:
    
    - table:
        name: steptimings
        options:
          update:
            LML: steptime
          update_trigger:
            - steptimings_wfstat
            - steptimings_stat
            - steptimingscurrent
            - steptimingscurrentstep
            - steptimings_time_aggr_ts
          archive:
            limit: max(wf_startts)-3d
          index: id
        columns: 
          - { name: wf_startts,   type: ts_t,               LML_from: wf_startts,              LML_default: -1 }
          - { name: wf_name,      type: name_t,             LML_from: wf_name,                 LML_default: 'unknown' }
          - { name: name,         type: name_t,             LML_from: name,                    LML_default: "-" }
          - { name: id,           type: name_t,             LML_from: id,                      LML_default: 'unknown' }
          - { name: startts,      type: ts_t,               LML_from: start_ts,                LML_default: -1, LML_minlastinsert: mintsinserted }
          - { name: endts,        type: ts_t,               LML_from: end_ts,                  LML_default: -1        }
          - { name: dt,           type: ts_t,               LML_from: dt,                      LML_default: -1        }
          - { name: nr,           type: cnt_t,              LML_from: nr,                      LML_default: -1 }
          - { name: groupnr,      type: cnt_t,              LML_from: group,                   LML_default: -1 }
          - { name: cmplx,        type: cnt_t,              LML_from: cmplx,                   LML_default: 0 }
          - { name: wf_cnt,       type: cnt_t,              LML_from: wf_cnt,                  LML_default: 0 }

    # contains all know steps
    - table:
        name: steptimingscurrent
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql:  DELETE FROM steptimingscurrent;
                    INSERT INTO steptimingscurrent (wf_startts,wf_name,name,id,startts,endts,dt,nr,groupnr,cmplx,wf_cnt)
                           SELECT wf_startts,wf_name,name,id,startts,endts,dt,nr,groupnr,cmplx,wf_cnt
                           FROM steptimings
                           WHERE (id||startts)
                                 IN (SELECT id||ts_max
                                     FROM steptimings_stat)
              sqldebug: 0
        columns: 
          - { name: wf_startts,   type: ts_t,               LML_default: -1        }
          - { name: wf_name,      type: name_t,             LML_default: 'unknown' }
          - { name: name,         type: name_t,             LML_default: "-" }
          - { name: id,           type: name_t,             LML_default: 'unknown' }
          - { name: startts,      type: ts_t,               LML_default: -1        }
          - { name: endts,        type: ts_t,               LML_default: -1        }
          - { name: dt,           type: ts_t,               LML_default: -1        }
          - { name: nr,           type: cnt_t,              LML_default: -1 }
          - { name: groupnr,      type: cnt_t,              LML_default: -1 }
          - { name: cmplx,        type: cnt_t,              LML_default: 0 }
          - { name: wf_cnt,       type: cnt_t,              LML_default: 0 }

    # contains only step which were active in the current workflow 
    - table:
        name: steptimingscurrentstep
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql:  DELETE FROM steptimingscurrentstep;
                    INSERT INTO steptimingscurrentstep (wf_startts,wf_name,name,id,startts,endts,dt,nr,groupnr,cmplx,wf_cnt)
                           SELECT a.wf_startts,a.wf_name,a.name,a.id,a.startts,a.endts,a.dt,a.nr,a.groupnr,a.cmplx,a.wf_cnt
                           FROM steptimingscurrent a, steptimings_wfstat b
                           WHERE (a.wf_name = b. wf_name) and (a.wf_cnt=b.wf_cnt)
              sqldebug: 0
        columns: 
          - { name: wf_startts,   type: ts_t,               LML_default: -1        }
          - { name: wf_name,      type: name_t,             LML_default: 'unknown' }
          - { name: name,         type: name_t,             LML_default: "-" }
          - { name: id,           type: name_t,             LML_default: 'unknown' }
          - { name: startts,      type: ts_t,               LML_default: -1        }
          - { name: endts,        type: ts_t,               LML_default: -1        }
          - { name: dt,           type: ts_t,               LML_default: -1        }
          - { name: nr,           type: cnt_t,              LML_default: -1 }
          - { name: groupnr,      type: cnt_t,              LML_default: -1 }
          - { name: cmplx,        type: cnt_t,              LML_default: 0 }
          - { name: wf_cnt,       type: cnt_t,              LML_default: 0 }

    - table:
        name: steptimings_time_aggr_ts
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              aggr_by_time_resolutions: [1, 60, 1440]     # in minutes (1 min, 1 hour, 1 day)
              aggr_by_time_mintsvar: mintsinserted
              sql: DELETE FROM steptimings_time_aggr_ts WHERE (startts >= mintsinserted);
                   INSERT INTO steptimings_time_aggr_ts (_time_res, _time_cnt, startts, id, dt, cmplx)
                                                SELECT 1,1, startts, id, dt, cmplx
                                                FROM steptimings
                                                WHERE (startts >= mintsinserted)
              sqldebug: 0
          archive:
            limit_aggr_time: [ 4320, 133920, 2628000 ]     # in minutes (3 days, 93 days, 5 years)
            limit_aggr_time_var: startts
        columns: 
          - { name: _time_res, type: _time_res_t }
          - { name: _time_cnt, type: _time_cnt_t }
          - { name: startts,   type: ts_t,    time_aggr: TS }
          - { name: id,        type: fid_t,   time_aggr: KEY  }
          - { name: dt,        type: ts_t,    time_aggr: AVG  }
          - { name: cmplx,     type: count_t, time_aggr: AVG  }

    - table:
        name: steptimings_stat
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql:  
                    DELETE FROM steptimings_stat;
                    INSERT INTO steptimings_stat (id,cnt,ts_min,ts_max,dt_min,dt_avg,dt_max,cmplx_min,cmplx_avg,cmplx_max)
                           SELECT id,count(*),
                                  min(startts),max(startts),
                                  min(dt),avg(dt),max(dt),
                                  min(cmplx),avg(cmplx),max(cmplx)
                           FROM steptimings GROUP BY id;
        columns: 
          - { name: id,           type: name_t }
          - { name: cnt,          type: cnt_t  } 
          - { name: ts_min,       type: ts_t   }
          - { name: ts_max,       type: ts_t   }
          - { name: dt_min,       type: ts_t   }
          - { name: dt_avg,       type: ts_t   }
          - { name: dt_max,       type: ts_t   }
          - { name: cmplx_min,    type: cnt_f_t   }
          - { name: cmplx_avg,    type: cnt_f_t   }
          - { name: cmplx_max,    type: cnt_f_t   }

    - table:
        name: steptimings_wfstat
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql:  
                    DELETE FROM steptimings_wfstat;
                    INSERT INTO steptimings_wfstat (wf_name,wf_cnt)
                           SELECT wf_name,max(wf_cnt)
                           FROM steptimings GROUP BY wf_name;
        columns: 
          - { name: wf_name,      type: name_t }
          - { name: wf_cnt,       type: cnt_t  } 
          
# Update tables: (fill new time_aggr table with data from old span tables)
# one line:
# select _time_res,count(*),sum(_time_cnt),min(startts),max(startts),(max(startts)-min(startts))/60.0/60.0/24.0 from steptimings_time_aggr_ts group by _time_res;insert into steptimings_time_aggr_ts (_time_res,_time_cnt,startts, id, dt, cmplx) select 1,1,startts, id, dt, cmplx from steptimings where startts<(select min(startts) from steptimings_time_aggr_ts where (_time_res=1));insert into steptimings_time_aggr_ts (_time_res,_time_cnt,startts, id, dt, cmplx) select 60,60,startts, id, dt, cmplx from steptimings_hourly where startts<=(select min(startts) from steptimings_time_aggr_ts where (_time_res=60));insert into steptimings_time_aggr_ts (_time_res,_time_cnt,startts, id, dt, cmplx) select 1440,1440,startts, id, dt, cmplx from steptimings_daily where startts<=(select min(startts) from steptimings_time_aggr_ts where (_time_res=1440));select _time_res,count(*),sum(_time_cnt),min(startts),max(startts),(max(startts)-min(startts))/60.0/60.0/24.0 from steptimings_time_aggr_ts  group by _time_res;

