# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

transfer:
  tables:
    
    - table:
        name: transfer
        options:
          update:
            LML: transferstat
          archive:
            limit: max(trans_ts)-504h
        columns: 
          - { name: trans_ts,     type: ts_t,               LML_from: ts,                      LML_default: -1, LML_minlastinsert: mintsinserted }
          - { name: ts_name,      type: name_t,             LML_from: name,                    LML_default: 'unknown' }
          - { name: startts,      type: ts_t,               LML_from: startts,                 LML_default: -1        }
          - { name: endts,        type: ts_t,               LML_from: endts,                   LML_default: -1        }
          - { name: dt,           type: ts_t,               LML_from: transfertime,            LML_default: -1        }
          
          - { name: nfiles,       type: cnt_t,              LML_from: nfiles,                  LML_default: -1 }
          - { name: nregfiles,    type: cnt_t,              LML_from: nregfiles,               LML_default: -1 }
          - { name: ndirs,        type: cnt_t,              LML_from: ndirs,                   LML_default: -1 }

          - { name: ncreate,      type: cnt_t,              LML_from: ncreate,                 LML_default: -1 }
          - { name: ndelete,      type: cnt_t,              LML_from: ndelete,                 LML_default: -1 }

          - { name: nregfilestrans,     type: cnt_t,        LML_from: nregfilestrans,          LML_default: -1 }
          - { name: totalfilesize,      type: bytes_t,      LML_from: totalfilesize,           LML_default: -1 }
          - { name: totalfilesizetrans, type: bytes_t,      LML_from: totalfilesizetrans,      LML_default: -1 }

          - { name: totalbytessent, type: bytes_t,          LML_from: totalbytessent,      LML_default: -1 }
          - { name: totalbytesrecv, type: bytes_t,          LML_from: totalbytesrecv,      LML_default: -1 }

          
