jumoncstate:
  tables:
    #---------------------------
    # table, filled by LML input
    #---------------------------
    - table:
        name: jumonc
        options:
          update:
            LML: jumonc
            mode: replace
          update_trigger:
          archive:
            limit: max(ts)-25h
#          index: nodeid,ts
        columns: 
          - { name: jobid,       type: jobid_t,    LML_from: jobid,       LML_default: 'unknown' }
          - { name: nodeid,      type: nodeid_t,   LML_from: nodeid,      LML_default: 'unknown' }
          - { name: ts,          type: ts_t,       LML_from: ts,          LML_default: -1 }
          - { name: numvars,     type: count_t,    LML_from: numvars,     LML_default: 0 }
          - { name: path,        type: longstr_t,  LML_from: path,        LML_default: '' }
          - { name: type0,       type: shortstr_t, LML_from: 0type,       LML_default: '' }
          - { name: type1,       type: shortstr_t, LML_from: 1type,       LML_default: '' }
          - { name: type2,       type: shortstr_t, LML_from: 2type,       LML_default: '' }
          - { name: type3,       type: shortstr_t, LML_from: 3type,       LML_default: '' }
          - { name: type4,       type: shortstr_t, LML_from: 4type,       LML_default: '' }
          - { name: type5,       type: shortstr_t, LML_from: 5type,       LML_default: '' }
          - { name: type6,       type: shortstr_t, LML_from: 6type,       LML_default: '' }
          - { name: type7,       type: shortstr_t, LML_from: 7type,       LML_default: '' }
          - { name: type8,       type: shortstr_t, LML_from: 8type,       LML_default: '' }
          - { name: type9,       type: shortstr_t, LML_from: 9type,       LML_default: '' }
          - { name: name0,       type: longstr_t,  LML_from: 0name,       LML_default: '' }
          - { name: name1,       type: longstr_t,  LML_from: 1name,       LML_default: '' }
          - { name: name2,       type: longstr_t,  LML_from: 2name,       LML_default: '' }
          - { name: name3,       type: longstr_t,  LML_from: 3name,       LML_default: '' }
          - { name: name4,       type: longstr_t,  LML_from: 4name,       LML_default: '' }
          - { name: name5,       type: longstr_t,  LML_from: 5name,       LML_default: '' }
          - { name: name6,       type: longstr_t,  LML_from: 6name,       LML_default: '' }
          - { name: name7,       type: longstr_t,  LML_from: 7name,       LML_default: '' }
          - { name: name8,       type: longstr_t,  LML_from: 8name,       LML_default: '' }
          - { name: name9,       type: longstr_t,  LML_from: 9name,       LML_default: '' }
          - { name: description0,   type: longstr_t,  LML_from: 0description,   LML_default: '' }
          - { name: description1,   type: longstr_t,  LML_from: 1description,   LML_default: '' }
          - { name: description2,   type: longstr_t,  LML_from: 2description,   LML_default: '' }
          - { name: description3,   type: longstr_t,  LML_from: 3description,   LML_default: '' }
          - { name: description4,   type: longstr_t,  LML_from: 4description,   LML_default: '' }
          - { name: description5,   type: longstr_t,  LML_from: 5description,   LML_default: '' }
          - { name: description6,   type: longstr_t,  LML_from: 6description,   LML_default: '' }
          - { name: description7,   type: longstr_t,  LML_from: 7description,   LML_default: '' }
          - { name: description8,   type: longstr_t,  LML_from: 8description,   LML_default: '' }
          - { name: description9,   type: longstr_t,  LML_from: 9description,   LML_default: '' }
          - { name: minimum0,       type: longstr_t,  LML_from: 0minimum,       LML_default: '' }
          - { name: minimum1,       type: longstr_t,  LML_from: 1minimum,       LML_default: '' }
          - { name: minimum2,       type: longstr_t,  LML_from: 2minimum,       LML_default: '' }
          - { name: minimum3,       type: longstr_t,  LML_from: 3minimum,       LML_default: '' }
          - { name: minimum4,       type: longstr_t,  LML_from: 4minimum,       LML_default: '' }
          - { name: minimum5,       type: longstr_t,  LML_from: 5minimum,       LML_default: '' }
          - { name: minimum6,       type: longstr_t,  LML_from: 6minimum,       LML_default: '' }
          - { name: minimum7,       type: longstr_t,  LML_from: 7minimum,       LML_default: '' }
          - { name: minimum8,       type: longstr_t,  LML_from: 8minimum,       LML_default: '' }
          - { name: minimum9,       type: longstr_t,  LML_from: 9minimum,       LML_default: '' }
          - { name: maximum0,       type: longstr_t,  LML_from: 0maximum,       LML_default: '' }
          - { name: maximum1,       type: longstr_t,  LML_from: 1maximum,       LML_default: '' }
          - { name: maximum2,       type: longstr_t,  LML_from: 2maximum,       LML_default: '' }
          - { name: maximum3,       type: longstr_t,  LML_from: 3maximum,       LML_default: '' }
          - { name: maximum4,       type: longstr_t,  LML_from: 4maximum,       LML_default: '' }
          - { name: maximum5,       type: longstr_t,  LML_from: 5maximum,       LML_default: '' }
          - { name: maximum6,       type: longstr_t,  LML_from: 6maximum,       LML_default: '' }
          - { name: maximum7,       type: longstr_t,  LML_from: 7maximum,       LML_default: '' }
          - { name: maximum8,       type: longstr_t,  LML_from: 8maximum,       LML_default: '' }
          - { name: maximum9,       type: longstr_t,  LML_from: 9maximum,       LML_default: '' }

    - table:
        name: jumonc_by_ts
        options:
          update:
            LML: jumonc
            mode: add
          update_trigger:
            - jumonc_current_jobid
            - jumonc_stat_by_jobid
            - jumonc_desc_by_jobid
          archive:
            limit: max(ts)-25h
#          index: nodeid,ts
        columns: 
          - { name: jobid,        type: jobid_t,  LML_from: jobid,        LML_default: 'unknown' }
          - { name: nodeid,       type: nodeid_t, LML_from: nodeid,       LML_default: 'unknown' }
          - { name: ts,           type: ts_t,     LML_from: ts,           LML_default: -1,  LML_minlastinsert: mintsinserted}
          - { name: value0,       type: float_t,  LML_from: 0value,       LML_default: '' }
          - { name: value1,       type: float_t,  LML_from: 1value,       LML_default: '' }
          - { name: value2,       type: float_t,  LML_from: 2value,       LML_default: '' }
          - { name: value3,       type: float_t,  LML_from: 3value,       LML_default: '' }
          - { name: value4,       type: float_t,  LML_from: 4value,       LML_default: '' }
          - { name: value5,       type: float_t,  LML_from: 5value,       LML_default: '' }
          - { name: value6,       type: float_t,  LML_from: 6value,       LML_default: '' }
          - { name: value7,       type: float_t,  LML_from: 7value,       LML_default: '' }
          - { name: value8,       type: float_t,  LML_from: 8value,       LML_default: '' }
          - { name: value9,       type: float_t,  LML_from: 9value,       LML_default: '' }
          
    - table:
        name: jumonc_stat_by_jobid
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql: DELETE FROM jumonc_stat_by_jobid WHERE jobid IN (SELECT jobid from jumonc_current_jobid);
                   INSERT INTO jumonc_stat_by_jobid (jobid,ts,jmc_ndps)
                        SELECT jobid, MAX(ts), COUNT(ts)
                               FROM jumonc_by_ts
                               WHERE jobid IN (SELECT jobid from jumonc_current_jobid)
                               GROUP by jobid;
          archive:
            limit: max(ts)-25h
#          index: nodeid,ts
        columns: 
          - { name: jobid,       type: jobid_t }
          - { name: ts,          type: ts_t    }
          - { name: jmc_ndps,    type: count_t }

    - table:
        name: jumonc_desc_by_jobid
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql: DELETE FROM jumonc_desc_by_jobid WHERE jobid IN (SELECT jobid from jumonc_current_jobid);
                   INSERT INTO jumonc_desc_by_jobid (jobid,ts,numvars,jmc_ndps,names,descriptions,minimums,maximums)
                        SELECT A.jobid, A.ts, A.numvars, B.jmc_ndps,
                               name0||'::'||name1||'::'||name2||'::'||name3||'::'||name4||'::'||name5||'::'||name6||'::'||name7||'::'||name8||'::'||name9,
                               description0||'::'||description1||'::'||description2||'::'||description3||'::'||description4||'::'||description5||'::'||description6||'::'||description7||'::'||description8||'::'||description9,
                               minimum0||'::'||minimum1||'::'||minimum2||'::'||minimum3||'::'||minimum4||'::'||minimum5||'::'||minimum6||'::'||minimum7||'::'||minimum8||'::'||minimum9,
                               maximum0||'::'||maximum1||'::'||maximum2||'::'||maximum3||'::'||maximum4||'::'||maximum5||'::'||maximum6||'::'||maximum7||'::'||maximum8||'::'||maximum9
                               FROM jumonc A, jumonc_stat_by_jobid B
                               WHERE A.jobid IN (SELECT jobid from jumonc_current_jobid) AND A.jobid=B.jobid;
              sqldebug: 0
          archive:
            limit: max(ts)-25h
#          index: nodeid,ts
        columns: 
          - { name: jobid,        type: jobid_t }
          - { name: ts,           type: ts_t    }
          - { name: numvars,      type: count_t }
          - { name: jmc_ndps,     type: count_t }
          - { name: names,        type: longstr_t }
          - { name: descriptions, type: extralongstr_t }
          - { name: minimums,     type: longstr_t }
          - { name: maximums,     type: longstr_t }
          
          
    - table:
        name: jumonc_current_jobid
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sqldebug: 0
              sql: DELETE FROM jumonc_current_jobid;
                   INSERT INTO jumonc_current_jobid
                        SELECT jmc.jobid
                               FROM jumonc jmc
                               WHERE (jmc.ts >= mintsinserted-59);
          update_trigger:
        columns: 
          - { name: jobid,    type: jobid_t }
          
