###############################
# Support
###############################
- dataset:
    name:            client_lml_state_full
    set:             lmlstat
    filepath:        '$outputdir/system_state_LML.xml'
    format:          'lml'
    stat_database:   'lmlstat_lml_stat'
    stat_table:      'datasetstat_lml_state'
    groups:
       - group:
         name:     'jobs'
         type:     'job'
         idprefix: 'j'
         key:      'jobid'
         data_database:       'lmlstat'
         data_table:          'jobs'
         attributes:       
           - { name: step,       col: "jobid"  }
           - { name: owner,      col: "owner"  }
           - { name: account,    col: "account"  }
           - { name: state,      col: "state"  }
           - { name: status,     col: "jstatus"  }
           - { name: queue,      col: "queue"  }
           - { name: qos,        col: "qos"  }
           - { name: command,    col: "command"  }
           - { name: reason,          col: "reason"  }
           - { name: detailedstatus,  col: "detailedstatus"  }
           - { name: dependency,      col: "dependency"  }
           - { name: starttime,       col: "starttime"  }
           - { name: endtime,         col: "endtime"  }
           - { name: runtime,         col: "runtime"  }
           - { name: queuedate,       col: "queuedate"  }
           - { name: group,      col: "jgroup"  }
           - { name: name,       col: "name"  } 
           - { name: numnodes,   col: "numnodes"  } 
           - { name: totalcores, col: "totalcores"  } 
           - { name: totaltasks, col: "totaltasks"  } 
           - { name: tpt,        col: "tpt"  } 
           - { name: userprio,   col: "userprio"  } 
           - { name: wall,       col: "wall"  } 
           - { name: vnodelist,  col: "vnodelist"  }

           - { name: load_avg,  col: "load_avg", if: "gt0"  }
           - { name: load_min,  col: "load_min", if: "gt0"  }
           - { name: load_max,  col: "load_max", if: "gt0"  }
           
           - { name: memU_avg,  col: "used_mem_avg", if: "gt0"  }
           - { name: memU_min,  col: "used_mem_min", if: "gt0"  }
           - { name: memU_max,  col: "used_mem_max", if: "gt0"  }

           - { name: mbin_avg,   col: "mbin_avg", if: "gt0"  }
           - { name: mbin_min,   col: "mbin_min", if: "gt0"  }
           - { name: mbin_max,   col: "mbin_max", if: "gt0"  }
           - { name: mbout_avg,  col: "mbout_avg", if: "gt0"  }
           - { name: mbout_min,  col: "mbout_min", if: "gt0"  }
           - { name: mbout_max,  col: "mbout_max", if: "gt0"  }
           - { name: pckin_avg,  col: "pckin_avg", if: "gt0"  }
           - { name: pckin_min,  col: "pckin_min", if: "gt0"  }
           - { name: pckin_max,  col: "pckin_max", if: "gt0"  }
           - { name: pckout_avg, col: "pckout_avg", if: "gt0"  }
           - { name: pckout_min, col: "pckout_min", if: "gt0"  }
           - { name: pckout_max, col: "pckout_max", if: "gt0"  }

           - { name: gpulist,      col: "gpulist" , if: "notempty" }
           - { name: reservation,  col: "resid" ,   if: "notempty" }

           
           
       - group:
         name:     'nodes'
         type:     'node'
         idprefix: 'nd'
         key:      'nodeid'
         sql_where: 'nodeid NOT LIKE ("all%")'
         data_database:       'lmlstat'
         data_table:          'nodes'
         attributes:       
           - { name: id,       col: "nodeid"  }
           - { name: classes,  col: "classes"  }
           - { name: load,     col: "load"  }
           - { name: memU,     col: "used_mem"  }
           - { name: physmem,  col: "total_mem"  }
           - { name: ncores,   col: "total_cores"  }
           - { name: ncoresU,  col: "used_cores"  }
           - { name: state,    col: "status"  }
           - { name: substate, col: "substatus"  }
           - { name: features, col: "feat"  }
           - { name: gpus,     col: "ngpus"  }
           - { name: fs_bw_all,  col: "fs_bw_all"  }
           - { name: fs_br_all,  col: "fs_br_all"  }
           - { name: fs_oc_all,  col: "fs_oc_all"  }
           - { name: fs_dts_all, col: "fs_dts_all"  }
           - { name: fs_bw_home,  col: "fs_bw_home"  }
           - { name: fs_br_home,  col: "fs_br_home"  }
           - { name: fs_oc_home,  col: "fs_oc_home"  }
           - { name: fs_dts_home, col: "fs_dts_home"  }
           - { name: fs_bw_project,  col: "fs_bw_project"  }
           - { name: fs_br_project,  col: "fs_br_project"  }
           - { name: fs_oc_project,  col: "fs_oc_project"  }
           - { name: fs_dts_project, col: "fs_dts_project"  }
           - { name: fs_bw_scratch,  col: "fs_bw_scratch"  }
           - { name: fs_br_scratch,  col: "fs_br_scratch"  }
           - { name: fs_oc_scratch,  col: "fs_oc_scratch"  }
           - { name: fs_dts_scratch, col: "fs_dts_scratch"  }
           - { name: fs_bw_fastdata,  col: "fs_bw_fastdata"  }
           - { name: fs_br_fastdata,  col: "fs_br_fastdata"  }
           - { name: fs_oc_fastdata,  col: "fs_oc_fastdata"  }
           - { name: fs_dts_fastdata, col: "fs_dts_fastdata"  }
           - { name: fb_mbin,  col: "fb_mbin"  }
           - { name: fb_mbout, col: "fb_mbout"  }
           - { name: fb_pckin,  col: "fb_pckin"  }
           - { name: fb_pckout, col: "fb_pckout"  }
           
         attributes_add:       
           - { name: load_MIN,   val: "0",        onlyfirst: 1 }
           - { name: load_MAX,   val: "512",      onlyfirst: 1 }
           - { name: load_UNIT,  val: "cpus",     onlyfirst: 1 }
           - { name: memU_MIN,   val: "0",        onlyfirst: 1 }
           - { name: memU_MAX,   val: "512000",   onlyfirst: 1 }
           - { name: memU_UNIT,  val: "MB",       onlyfirst: 1 }
           - { name: physmem_MIN,   val: "0",        onlyfirst: 1 }
           - { name: physmem_MAX,   val: "512000",   onlyfirst: 1 }
           - { name: physmem_UNIT,  val: "MB",       onlyfirst: 1 }
           - { name: memUP_MIN,   val: "0",        onlyfirst: 1 }
           - { name: memUP_MAX,   val: "100",      onlyfirst: 1 }
           - { name: memUP_UNIT,  val: "%",        onlyfirst: 1 }
           - { name: fb_mbin_MIN,   val: "0",        onlyfirst: 1 }
           - { name: fb_mbin_MAX,   val: "20000",    onlyfirst: 1 }
           - { name: fb_mbin_UNIT,  val: "MB/s",     onlyfirst: 1 }
           - { name: fb_mbout_MIN,  val: "0",        onlyfirst: 1 }
           - { name: fb_mbout_MAX,  val: "20000",    onlyfirst: 1 }
           - { name: fb_mbout_UNIT, val: "MB/s",     onlyfirst: 1 }
           - { name: fb_pckin_MIN,   val: "0",        onlyfirst: 1 }
           - { name: fb_pckin_MAX,   val: "10000000", onlyfirst: 1 }
           - { name: fb_pckin_UNIT,  val: "packets",  onlyfirst: 1 }
           - { name: fb_pckout_MIN,  val: "0",        onlyfirst: 1 }
           - { name: fb_pckout_MAX,  val: "10000000", onlyfirst: 1 }
           - { name: fb_pckout_UNIT, val: "packets",  onlyfirst: 1 }

       - group:
         name:     'gpunodes'
         type:     'node'
         idprefix: 'gpu'
         key:      'gpuid'
         data_database:       'lmlstat'
         data_table:          'gpunodes'
         attributes:       
           - { name: id,         col: "gpuid"  }
           - { name: pid,        col: "nodeid"  }
           - { name: ts,         col: "ts"  }
           - { name: state,      col: "state"  }
           - { name: gpu_clk,    col: "gpu_clk"  }
           - { name: gpu_clkr,   col: "gpu_clkr"  }
           - { name: gpu_eadm_d, col: "gpu_eadm_d"  }
           - { name: gpu_eadm_s, col: "gpu_eadm_s"  }
           - { name: gpu_evdm_d, col: "gpu_evdm_d"  }
           - { name: gpu_evdm_s, col: "gpu_evdm_s"  }
           - { name: gpu_link,   col: "gpu_link"  }
           - { name: gpu_memf,   col: "gpu_memf"  }
           - { name: gpu_memt,   col: "gpu_memt"  }
           - { name: gpu_memu,   col: "gpu_memu"  }
           - { name: gpu_memur,  col: "gpu_memur"  }
           - { name: gpu_pciw,   col: "gpu_pciw"  }
           - { name: gpu_pfst,   col: "gpu_pfst"  }
           - { name: gpu_pu,     col: "gpu_pu"  }
           - { name: gpu_sclk,   col: "gpu_sclk"  }
           - { name: gpu_temp,   col: "gpu_temp"  }
           - { name: gpu_usage,  col: "gpu_usage"  }
           - { name: pcietx,     col: "gpu_pcie_tx"  }
           - { name: pcierx,     col: "gpu_pcie_rx"  }
           - { name: ncores,     col: "ncores"  }
           - { name: features,   col: "features"  }

       - group:
         name:     'classes'
         type:     'class'
         idprefix: 'c'
         key:      'classname'
         data_database:       'clsstate'
         data_table:          'classes'
         attributes:       
           - { name: name,        col: "classname"  }
           - { name: max_size,    col: "max_size"  }
           - { name: max_wall,    col: "max_wall"  }
           - { name: max_tres_pu, col: "max_tres_pu"  }
           - { name: UsageFactor, col: "UsageFactor"  }
           - { name: GraceTime,   col: "GraceTime"  }

           
       - group:
         name:     'system'
         type:     'system'
         idprefix: 'sys'
         key:      'sysid'
         data_database:       'lmlstat'
         data_table:          'systable'
         attributes:       
           - { name: sysid,       col: "sysid"  }
           - { name: hostname,    col: "hostname"  }
           - { name: system_ts,   col: "system_ts"  }
           - { name: system_time, col: "system_ts", convert: "todate_std_hhmmss_jufo" }
         attributes_add:       
           - { name: type,        val: "Cluster"  }

       - group:
         name:     'reservation'
         type:     'reservation'
         idprefix: 'r'
         key:      'resid'
         data_database:       'resstate'
         data_table:          'reservations'
         attributes:       
           - { name: resid,       col: "resid"  }
           - { name: resname,     col: "resname"  }
           - { name: corecnt,     col: "numcores"  }
           - { name: nodecnt,     col: "numnodes"  }
           - { name: state,       col: "state"  }
           - { name: wall,        col: "wall"  }
           - { name: flags,       col: "flags"  }
           - { name: accounts,    col: "accounts"  }
           - { name: nodelist,    col: "nodelist"  }
           - { name: endtime,     col: "endts", convert: "todate_std_hhmmss_jufo" }
           - { name: starttime,   col: "startts", convert: "todate_std_hhmmss_jufo" }


# - dataset:
#     name:            client_lml_state_charts
#     set:             lmlstat
#     filepath:        '$outputdir/system_state_LML_charts.xml'
#     format:          'lml'
#     stat_database:   'lmlstat_lml_stat'
#     stat_table:      'datasetstat_lml_state'
#     charts:
#        %include "./lmlstat_datafiles_chart_memory.yaml"
#        %include "./lmlstat_datafiles_chart_systemusage.yaml"
#        %include "./lmlstat_datafiles_chart_queuestate.yaml"
#        %include "./lmlstat_datafiles_chart_power.yaml"
#        %include "./lmlstat_datafiles_chart_sysio.yaml"
#        %include "./lmlstat_datafiles_chart_fabric.yaml"
