lmlstat:
  tables:

###########
# Jobs
###########

    
  - table:
      name: jobs
      options:
        update:
          LMLstat: update_from_other_db(jobid,tabstatjobs,updatedjobs)
        update_trigger:
        - systable
      columns: 
        - { name: jobid,           type: jobid_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 'unknown' }
        - { name: ts,              type: ts_t,              LLDB_from: jobstate/queuedjobs,    LLDB_from_lastts: yes,         LL_default: -1        }
        - { name: owner,           type: owner_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 'unknown' }
        - { name: jgroup,          type: jgroup_t,          LLDB_from: jobstate/queuedjobs,    LL_default: 'unknown' }
        - { name: jstatus,         type: jstatus_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 'UNKNOWN' }
        - { name: detailedstatus,  type: detailedstatus_t,  LLDB_from: jobstate/queuedjobs,    LL_default: 'UNKNOWN' }
        - { name: state,           type: jstatus_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 'unknown' }
        - { name: wall,            type: wall_t,            LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: wallsoft,        type: wall_t,            LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: queuedate,       type: date_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: name,            type: name_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: comment,         type: comment_t,         LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: totalcores,      type: cores_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: totaltasks,      type: tasks_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: tpt,             type: tasks_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: totalgpus,       type: tasks_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: queue,           type: queue_t,           LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: dependency,      type: dependency_t,      LLDB_from: jobstate/queuedjobs,    LL_default: "" }
        - { name: qos,             type: qos_t,             LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: command,         type: command_t,         LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: classprio,       type: prio_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: groupprio,       type: prio_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: userprio,        type: prio_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: sysprio,         type: prio_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
        - { name: favored,         type: favored_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: restart,         type: restart_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: account,         type: account_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: runtime,         type: time_t,            LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: starttime,       type: date_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "" }
        - { name: endtime,         type: date_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "" }
        - { name: numnodes,        type: tasks_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: reason,          type: comment_t,         LLDB_from: jobstate/queuedjobs,    LL_default: "" }
        - { name: ArrayJobId,      type: jobid_t,           LLDB_from: jobstate/queuedjobs,    LL_default: "" }
        - { name: ArrayTaskId,     type: jobid_t,           LLDB_from: jobstate/queuedjobs,    LL_default: "" }
        - { name: waittime,        type: hour_t,            LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: timetostart,     type: hour_t,            LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
        - { name: posinqueue,      type: pos_t,             LLDB_from: jobstate/queuedjobs,    LL_default: "" }
        - { name: vnodelist,       type: extralongstr_t,    LLDB_from: jobstate/queuedjobs,    LL_default: "" }
        - { name: resid,           type: resid_t,           LLDB_from: jobstate/queuedjobs,    LML_default: "" }
       
        - { name: firstts,         type: ts_t,              LLDB_from: jobstate/currentjobs_deferred,       LL_default: -1 }
        - { name: lastts,          type: ts_t,              LLDB_from: jobstate/currentjobs_deferred,       LL_default: -1 }
        - { name: lastupdts,       type: ts_t,              LLDB_from: jobstate/currentjobs_deferred,       LLDB_from_lastts: yes, LL_default: -1 }
        - { name: finished,        type: flag_t,            LLDB_from: jobstate/currentjobs_deferred,       LL_default: 0 }

        - { name: ldlastts,        type: ts_t,              LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LLDB_from_lastts: yes, LL_default: -1    }
        - { name: load_avg,        type: load_t,            LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }
        - { name: load_min,        type: load_t,            LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }
        - { name: load_max,        type: load_t,            LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }
        - { name: used_cores_avg,  type: cores_t,           LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }
        - { name: used_cores_min,  type: cores_t,           LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }
        - { name: used_cores_max,  type: cores_t,           LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }
        - { name: total_cores_avg, type: cores_t,           LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }
        - { name: used_mem_avg,    type: mem_t,             LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }  
        - { name: used_mem_min,    type: mem_t,             LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }  
        - { name: used_mem_max,    type: mem_t,             LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }  
        - { name: total_mem_avg,   type: mem_t,             LLDB_from: loadmemstate/loadmem_aggr_by_jobid, LL_default: -1 }  

        - { name: falastts,        type: ts_t,              LLDB_from: fabricstate/fabric_aggr_by_jobid,   LLDB_from_lastts: yes, LL_default: -1 }
        - { name: mbin_avg,        type: mb_t,              LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: mbin_min,        type: mb_t,              LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: mbin_max,        type: mb_t,              LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: mbout_avg,       type: mb_t,              LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: mbout_min,       type: mb_t,              LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: mbout_max,       type: mb_t,              LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: pckin_avg,       type: pck_t,             LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: pckin_min,       type: pck_t,             LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: pckin_max,       type: pck_t,             LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: pckout_avg,      type: pck_t,             LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: pckout_min,      type: pck_t,             LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }
        - { name: pckout_max,      type: pck_t,             LLDB_from: fabricstate/fabric_aggr_by_jobid,   LL_default: 0 }

        - { name: gpulist,         type: extralongstr_t,    LLDB_from: gpustate/currentjobs_gpulist, LL_default: "" }
        - { name: gpulastts,       type: ts_t,              LLDB_from: gpustate/currentjobs_gpulist, LLDB_from_lastts: yes, LL_default: -1 }
        
  - table:
      name: updatedjobs
      options:
      columns: 
        - { name: jobid,           type: jobid_t, LL_default: 'unknown' }

  - table:
      name: tabstatjobs
      options:
      columns: 
        - { name: tabspec,         type: name_t,  LL_default: 'unknown' }
        - { name: lasttscol,       type: name_t,  LL_default: 'unknown' }
        - { name: lastts,          type: ts_t,    LL_default: -1        }

###########
# Nodes
###########

  - table:
      name: nodes
      options:
        update:
          LMLstat: update_from_other_db(nodeid,tabstatnodes,updatednodes)
      columns: 
        - { name: nodeid,      type: nodeid_t,   LLDB_from: loadmemstate/loadmem,    LML_default: 'unknown' }
        - { name: ts,          type: ts_t,       LLDB_from: loadmemstate/loadmem,    LML_default: -1,  LLDB_from_lastts: yes }
        - { name: status,      type: status_t,   LLDB_from: loadmemstate/loadmem,     LML_default: 'U' }
        - { name: substatus,   type: status_t,   LLDB_from: loadmemstate/loadmem,     LML_default: '-' }
        - { name: feat,        type: feature_t,  LLDB_from: loadmemstate/loadmem,     LML_default: 'U' }
        - { name: istatus,     type: istatus_t,  LLDB_from: loadmemstate/loadmem,     LML_default: 9 }
        - { name: load,        type: load_t,     LLDB_from: loadmemstate/loadmem,     LML_default: 0 }
        - { name: used_cores,  type: cores_t,    LLDB_from: loadmemstate/loadmem,     LML_default: 0 }
        - { name: total_cores, type: cores_t,    LLDB_from: loadmemstate/loadmem,     LML_default: -1.0 }
        - { name: total_mem,   type: mem_t,      LLDB_from: loadmemstate/loadmem,     LML_default: 0.0 }
        - { name: used_mem,    type: mem_t,      LLDB_from: loadmemstate/loadmem,     LML_default: 0.0 }
        - { name: ngpus,       type: count_t,    LLDB_from: loadmemstate/loadmem,     LML_default: 0.0 }
        - { name: classes,     type: longstr_t,  LLDB_from: loadmemstate/loadmem,     LML_default: '-' }
        - { name: fs_ts_all,   type: ts_t,       LLDB_from: fsusagestate_all/fsusage/ts,  LML_default: 0.0,  LLDB_from_lastts: yes }
        - { name: fs_bw_all,   type: bytes_t,    LLDB_from: fsusagestate_all/fsusage/bw,  LML_default: 0.0 }
        - { name: fs_br_all,   type: bytes_t,    LLDB_from: fsusagestate_all/fsusage/br,  LML_default: 0.0 }
        - { name: fs_oc_all,   type: ops_t,      LLDB_from: fsusagestate_all/fsusage/oc,  LML_default: 0.0 }
        - { name: fs_dts_all,  type: count_t,    LLDB_from: fsusagestate_all/fsusage/dts, LML_default: 0.0 }
        - { name: fs_ts_home,   type: ts_t,      LLDB_from: fsusagestate_home/fsusage/ts,  LML_default: 0.0,  LLDB_from_lastts: yes }
        - { name: fs_bw_home,   type: bytes_t,    LLDB_from: fsusagestate_home/fsusage/bw,  LML_default: 0.0 }
        - { name: fs_br_home,   type: bytes_t,    LLDB_from: fsusagestate_home/fsusage/br,  LML_default: 0.0 }
        - { name: fs_oc_home,   type: ops_t,      LLDB_from: fsusagestate_home/fsusage/oc,  LML_default: 0.0 }
        - { name: fs_dts_home,  type: count_t,    LLDB_from: fsusagestate_home/fsusage/dts, LML_default: 0.0 }
        - { name: fs_ts_project,   type: ts_t,       LLDB_from: fsusagestate_project/fsusage/ts,  LML_default: 0.0,  LLDB_from_lastts: yes }
        - { name: fs_bw_project,   type: bytes_t,    LLDB_from: fsusagestate_project/fsusage/bw,  LML_default: 0.0 }
        - { name: fs_br_project,   type: bytes_t,    LLDB_from: fsusagestate_project/fsusage/br,  LML_default: 0.0 }
        - { name: fs_oc_project,   type: ops_t,      LLDB_from: fsusagestate_project/fsusage/oc,  LML_default: 0.0 }
        - { name: fs_dts_project,  type: count_t,    LLDB_from: fsusagestate_project/fsusage/dts, LML_default: 0.0 }
        - { name: fs_ts_scratch,   type: ts_t,       LLDB_from: fsusagestate_scratch/fsusage/ts,  LML_default: 0.0,  LLDB_from_lastts: yes }
        - { name: fs_bw_scratch,   type: bytes_t,    LLDB_from: fsusagestate_scratch/fsusage/bw,  LML_default: 0.0 }
        - { name: fs_br_scratch,   type: bytes_t,    LLDB_from: fsusagestate_scratch/fsusage/br,  LML_default: 0.0 }
        - { name: fs_oc_scratch,   type: ops_t,      LLDB_from: fsusagestate_scratch/fsusage/oc,  LML_default: 0.0 }
        - { name: fs_dts_scratch,  type: count_t,    LLDB_from: fsusagestate_scratch/fsusage/dts, LML_default: 0.0 }
        - { name: fs_ts_fastdata,   type: ts_t,      LLDB_from: fsusagestate_fastdata/fsusage/ts,  LML_default: 0.0,  LLDB_from_lastts: yes }
        - { name: fs_bw_fastdata,   type: bytes_t,    LLDB_from: fsusagestate_fastdata/fsusage/bw,  LML_default: 0.0 }
        - { name: fs_br_fastdata,   type: bytes_t,    LLDB_from: fsusagestate_fastdata/fsusage/br,  LML_default: 0.0 }
        - { name: fs_oc_fastdata,   type: ops_t,      LLDB_from: fsusagestate_fastdata/fsusage/oc,  LML_default: 0.0 }
        - { name: fs_dts_fastdata,  type: count_t,    LLDB_from: fsusagestate_fastdata/fsusage/dts, LML_default: 0.0 }
        - { name: fb_ts,       type: ts_t,       LLDB_from: fabricstate/fabric/ts,     LML_default: 0.0,  LLDB_from_lastts: yes }
        - { name: fb_mbin,     type: bytes_t,    LLDB_from: fabricstate/fabric/mbin,   LML_default: 0.0 }
        - { name: fb_mbout,    type: bytes_t,    LLDB_from: fabricstate/fabric/mbout,  LML_default: 0.0 }
        - { name: fb_pckin,    type: bytes_t,    LLDB_from: fabricstate/fabric/pckin,  LML_default: 0.0 }
        - { name: fb_pckout,   type: bytes_t,    LLDB_from: fabricstate/fabric/pckout, LML_default: 0.0 }

  - table:
      name: updatednodes
      options:
      columns: 
        - { name: nodeid,           type: nodeid_t, LL_default: 'unknown' }
        
  - table:
      name: tabstatnodes
      options:
      columns: 
        - { name: tabspec,         type: name_t,  LL_default: 'unknown' }
        - { name: lasttscol,       type: name_t,  LL_default: 'unknown' }
        - { name: lastts,          type: ts_t,    LL_default: -1        }


###########
# GPU-nodes
###########
        
  - table:
      name: gpunodes
      options:
        update:
          LMLstat: update_from_other_db(gpuid,tabstatgpunodes,updatedgpunodes)
      columns: 
        - { name: nodeid,      type: nodeid_t,   LLDB_from: gpustate/gpu, LML_default: 'unknown' }
        - { name: gpuid,       type: nodeid_t,   LLDB_from: gpustate/gpu, LML_default: 'unknown' }
        - { name: ts,          type: ts_t,       LLDB_from: gpustate/gpu, LML_default: -1,  LLDB_from_lastts: yes }
        - { name: status,      type: status_t,   LLDB_from: gpustate/gpu, LML_default: 'U' }
        - { name: gpu_clk,     type: clk_t,      LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_clkr,    type: clkr_t,     LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_eadm_d , type: errcnt_t,   LLDB_from: gpustate/gpu, LML_default: 0 } 
        - { name: gpu_eadm_s , type: errcnt_t,   LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_evdm_d , type: errcnt_t,   LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_evdm_s , type: errcnt_t,   LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_link   , type: num_t,      LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_memf   , type: mem_t,      LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_memt   , type: mem_t,      LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_memu   , type: mem_t,      LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_memur  , type: rate_t,     LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_pciw   , type: num_t,      LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_pfst   , type: num_t,      LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_pu     , type: power_t,    LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_sclk   , type: clk_t,      LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_temp   , type: temp_t,     LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_usage  , type: rate_t,     LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_pcie_tx, type: bytes_t,    LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: gpu_pcie_rx, type: bytes_t,    LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: ncores,      type: tasks_t,    LLDB_from: gpustate/gpu, LML_default: 0 }
        - { name: features,    type: feature_t,  LLDB_from: gpustate/gpu, LML_default: "-" }
        - { name: state,       type: status_t,   LLDB_from: gpustate/gpu, LML_default: '-' }
        
  - table:
      name: updatedgpunodes
      options:
      columns: 
        - { name: gpuid,           type: nodeid_t, LL_default: 'unknown' }
        
  - table:
      name: tabstatgpunodes
      options:
      columns: 
        - { name: tabspec,         type: name_t,  LL_default: 'unknown' }
        - { name: lasttscol,       type: name_t,  LL_default: 'unknown' }
        - { name: lastts,          type: ts_t,    LL_default: -1        }
        
  - table:
      name: systable
      options:
        update:
          sql_update_contents:
            sqldebug: 0
            sql: DELETE FROM systable;
                 INSERT INTO systable (sysid,hostname,system_ts)
                 VALUES("cluster","SYSTEM_NAME",TS_NOW);
                
      columns: 
        - { name: sysid,           type: cnt_t,      LL_default: 1   }
        - { name: hostname,        type: longstr_t,  LL_default: "Unknown"  }
        - { name: system_ts,       type: ts_t,       LL_default: -1  }

lmlstat_lml_stat:
  tables:
  - table:
      name: datasetstat_lml_state
      columns: 
        - { name: dataset,         type: longstr_t,  LL_default: 'unknown' }
        - { name: name,            type: name_t,     LL_default: 'unknown' }
        - { name: ukey,            type: ukey_t,     LL_default: 'unknown' }
        - { name: lastts_saved,    type: ts_t,       LL_default: -1        }
        - { name: checksum,        type: checksum_t, LL_default: 0         }
        - { name: status,          type: istatus_t,  LL_default: -1 }   # 0 -> not exists, 1 -> exists, -1 unknown, 2 compressed
        



        
