# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- table:
    name: rolelist
    options:
      update:
        LLjobreport: update_from_other_db(fid,tabstat_rolelist,updatedroles)
      archive:
        limit: max(u_ts)-72d
      update_trigger:
        - rolemap_active_stat
      index: fid,u_ts
    columns: 
      - { name: fid,             type: longstr_t,         LLDB_from: accountmap/rolelist,    LL_default: 'unknown' }
      - { name: u_ts,            type: ts_t,              LLDB_from: accountmap/rolelist,    LLDB_from_lastts: yes,         LL_default: -1        }
      - { name: id,              type: name_t,            LLDB_from: accountmap/rolelist,    LL_default: 'unknown' }
      - { name: wsaccount,       type: name_t,            LLDB_from: accountmap/rolelist,    LL_default: 'unknown' }
      - { name: project,         type: name_t,            LLDB_from: accountmap/rolelist,    LL_default: 'unknown' }
      - { name: kind,            type: shortstr_t,        LLDB_from: accountmap/rolelist,    LL_default: 'unknown' }
     
- table:
    name: tabstat_rolelist
    options:
    columns: 
      - { name: tabspec,         type: name_t,  LL_default: 'unknown' }
      - { name: lasttscol,       type: name_t,  LL_default: 'unknown' }
      - { name: lastts,          type: ts_t,    LL_default: -1        }

- table:
    name: updatedroles
    options:
    columns: 
      - { name: fid,             type: longstr_t, LL_default: 'unknown' }
      
- table:
    name: alljobs_stat
    options:
      update:
        sql_update_contents:
          sql: DELETE FROM alljobs_stat;
               INSERT INTO alljobs_stat (owner,account,mentor,numqueuedjobs,qnumnodes_avg,qnh,numjobs,numnodes_avg,nh)
                                                SELECT q.owner,q.account,q.mentor,
                                                       q.numqueuedjobs,q.qnumnodes_avg,q.qnh,
                                                       j.numjobs,j.numnodes_avg,j.nh
                                                FROM queued_stat q
                                                LEFT JOIN joblist_stat j
                                                ON q.owner=j.owner AND q.account=j.account AND q.mentor=j.mentor
                                                
                                                UNION ALL
                                                
                                                SELECT j.owner,j.account,j.mentor,
                                                       q.numqueuedjobs,q.qnumnodes_avg,q.qnh,
                                                       j.numjobs,j.numnodes_avg,j.nh
                                                FROM joblist_stat j
                                                LEFT JOIN queued_stat q
                                                ON q.owner=j.owner AND q.account=j.account AND q.mentor=j.mentor
                                                WHERE q.owner IS NULL
          sqldebug: 0
    columns: 
      - { name: owner,           type: owner_t       }
      - { name: account,         type: account_t     }
      - { name: mentor,          type: account_t     }
      - { name: numqueuedjobs,   type: cnt_n_t       }
      - { name: qnumnodes_avg,   type: cnt_n_t       }
      - { name: qnh,             type: hour_n_t      }
      - { name: numjobs,         type: cnt_n_t       }
      - { name: numnodes_avg,    type: cnt_n_t       }
      - { name: nh,              type: hour_n_t      }
      
- table:
    name: rolemap_active_stat
    options:
      update:
        sql_update_contents:
          sql: DELETE FROM rolemap_active_stat;
               INSERT INTO rolemap_active_stat (fid,u_ts,id,wsaccount,project,kind, numjobs)
                                                SELECT r.fid, r.u_ts,r.id,r.wsaccount,r.project,r.kind,
                                                       a.numqueuedjobs+a.numjobs
                                                FROM rolelist r
                                                LEFT JOIN alljobs_stat a
                                                ON r.id=a.owner AND r.project=a.account
                                                WHERE r.kind="U"

                                                UNION ALL

                                                SELECT r.fid, r.u_ts,r.id,r.wsaccount,r.project,r.kind,
                                                       SUM(a.numqueuedjobs+a.numjobs)
                                                FROM rolelist r
                                                LEFT JOIN alljobs_stat a
                                                ON  r.project=a.account
                                                WHERE r.kind="M"
                                                GROUP by r.fid, r.u_ts,r.id,r.wsaccount,r.project,r.kind

                                                UNION ALL

                                                SELECT r.fid, r.u_ts,r.id,r.wsaccount,r.project,r.kind,
                                                       SUM(a.numqueuedjobs+a.numjobs)
                                                FROM rolelist r
                                                LEFT JOIN alljobs_stat a
                                                ON  r.project=a.account
                                                WHERE r.kind="L" OR r.kind="A" 
                                                GROUP by r.fid, r.u_ts,r.id,r.wsaccount,r.project,r.kind


                                                UNION ALL

                                                SELECT r.fid, r.u_ts,r.id,r.wsaccount,r.project,r.kind,1
                                                FROM rolelist r
                                                WHERE r.kind="S" and r.wsaccount!='' 

                                                
          sqldebug: 0
      update_trigger:
        - rolemap_aggr_l1_stat
    columns: 
      - { name: fid,             type: longstr_t   }
      - { name: u_ts,            type: ts_t        }
      - { name: id,              type: name_t      }
      - { name: wsaccount,       type: name_t      }
      - { name: project,         type: name_t      }
      - { name: kind,            type: shortstr_t  }
      - { name: numjobs,         type: cnt_n_t     }

- table:
    name: rolemap_aggr_l1_stat
    options:
      update:
        sql_update_contents:
          sql: DELETE FROM rolemap_aggr_l1_stat;
               INSERT INTO rolemap_aggr_l1_stat (u_ts,id,wsaccount,kind,numjobs,numprojects,projects)
                                                SELECT max(u_ts),id,wsaccount,kind,SUM(numjobs),
                                                COUNT(project), GROUP_CONCAT(project, ",")
                                                FROM rolemap_active_stat
                                                GROUP BY id,wsaccount,kind

                                                
          sqldebug: 0
    columns: 
      - { name: u_ts,            type: ts_t        }
      - { name: id,              type: name_t      }
      - { name: wsaccount,       type: name_t      }
      - { name: kind,            type: shortstr_t  }
      - { name: numjobs,         type: cnt_n_t     }
      - { name: numprojects,     type: count_t        }
      - { name: projects,        type: extralongstr_t }

      
