# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- table:
    name: sysstat
    options:
      update:
        LLjobreport: update_from_other_db(fid,tabstat_sysstat,updatedsysstat)
      update_trigger:
      archive:
        LLjobreport: max(ts_start)-1h
      index: ts
    columns: 
      - { name: fid,             type: fid_t,      LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: 'unknown' }
      - { name: ts,              type: ts_t,       LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LLDB_from_lastts: yes,   LL_default: -1        }
      - { name: feat,            type: feature_t,  LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: 'UNKNOWN' }
      - { name: status,          type: status_t,   LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: 'UNKNOWN' }
      - { name: count,           type: count_t,    LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 }
      - { name: load_avg,        type: load_t,     LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 }
      - { name: load_min,        type: load_t,     LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 }
      - { name: load_max,        type: load_t,     LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 }
      - { name: used_cores_avg,  type: cores_f_t,  LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 }
      - { name: used_cores_min,  type: cores_f_t,  LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 }
      - { name: used_cores_max,  type: cores_f_t,  LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 }
      - { name: total_cores_avg, type: cores_f_t,  LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 }
      - { name: used_mem_avg,    type: mem_f_t,    LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 } 
      - { name: used_mem_min,    type: mem_f_t,    LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 } 
      - { name: used_mem_max,    type: mem_f_t,    LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 } 
      - { name: total_mem_avg,   type: mem_f_t,    LLDB_from: loadmemstate/loadmem_aggr_by_ts_feat_status,    LL_default: -1 } 

- table:
    name: tabstat_sysstat
    options:
    columns: 
      - { name: tabspec,         type: name_t,  LL_default: 'unknown' }
      - { name: lasttscol,       type: name_t,  LL_default: 'unknown' }
      - { name: lastts,          type: ts_t,    LL_default: -1        }
      
- table:
    name: updatedsysstat
    options:
    columns: 
      - { name: fid,           type: fid_t, LL_default: 'unknown' }
      

      
