# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- table:
    name: queuedjobs
    options:
      update:
        LLjobreport: update_from_other_db(jobid,tabstat_queued,updatedqueuedjobs)
      update_trigger:
          - workflows
          - workflows_spec
          - queued_stat
      archive:
        limit: max(ts)-72d
      index: jobid,ts
    columns: 
      - { name: jobid,           type: jobid_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 'unknown' }
      - { name: ts,              type: ts_t,              LLDB_from: jobstate/queuedjobs,    LLDB_from_lastts: yes,         LL_default: -1        }
      - { name: owner,           type: owner_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 'unknown' }
      - { name: detailedstatus,  type: detailedstatus_t,  LLDB_from: jobstate/queuedjobs,    LL_default: 'UNKNOWN' }
      - { name: state,           type: jstatus_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 'unknown' }
      - { name: wall,            type: wall_t,            LLDB_from: jobstate/queuedjobs,    LL_default: -1 }
      - { name: wallsoft,        type: wall_t,            LLDB_from: jobstate/queuedjobs,    LL_default: -1 }
      - { name: queuedate,       type: date_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: starttime,       type: date_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: name,            type: name_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: comment,         type: comment_t,         LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: totalcores,      type: cores_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
      - { name: totaltasks,      type: tasks_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
      - { name: totalgpus,       type: tasks_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
      - { name: queue,           type: queue_t,           LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: dependency,      type: dependency_t,      LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: qos,             type: qos_t,             LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: command,         type: command_t,         LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: classprio,       type: prio_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: groupprio,       type: prio_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: userprio,        type: prio_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: sysprio,         type: prio_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "-" }
      - { name: favored,         type: favored_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
      - { name: restart,         type: restart_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
      - { name: account,         type: account_t,         LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
      - { name: runtime,         type: time_t,            LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
      - { name: endtime,         type: date_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: numnodes,        type: tasks_t,           LLDB_from: jobstate/queuedjobs,    LL_default: 0 }
      - { name: reason,          type: comment_t,         LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: ArrayJobId,      type: jobid_t,           LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: ArrayTaskId,     type: jobid_t,           LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: resid,           type: resid_t,           LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: waittime,        type: hour_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: timetostart,     type: hour_t,            LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: posinqueue,      type: pos_t,             LLDB_from: jobstate/queuedjobs,    LL_default: "" }
      - { name: mentor,          type: account_t,         LLDB_map: "lookup(accountmap/mentormap/wsaccount, project, account)", LL_default: "-none-", }
      - { name: chainid,         type: chainid_t,         LLDB_from: jobstate/queuedjobs,    LML_default: "" }
      - { name: wf_id,           type: jobid_t,           LLDB_from: jobstate/queuedjobs,    LML_default: "" }
      - { name: wf_jid,          type: jobid_t,           LLDB_from: jobstate/queuedjobs,    LML_default: "" }
      - { name: wf_type,         type: shortstr_t,        LLDB_from: jobstate/queuedjobs,    LML_default: "" }
      
- table:
    name: tabstat_queued
    options:
    columns: 
      - { name: tabspec,         type: name_t,  LL_default: 'unknown' }
      - { name: lasttscol,       type: name_t,  LL_default: 'unknown' }
      - { name: lastts,          type: ts_t,    LL_default: -1        }

- table:
    name: updatedqueuedjobs
    options:
    columns: 
      - { name: jobid,           type: jobid_t, LL_default: 'unknown' }
      
- table:
    name: workflows
    options:
      update:
        sql_update_contents:
          vars: mintsinserted
          sql: DELETE FROM workflows WHERE wf_id IN
                                        (SELECT DISTINCT wf_id from queuedjobs
                                            WHERE jobid IN (select jobid from updatedqueuedjobs) AND wf_id!='-' );
               INSERT INTO workflows (wf_id,wf_type,owner,account,mentor,firstts,lastts, wf_jid_list,jobid_list)
                                                SELECT wf_id, wf_type, owner, account, mentor,
                                                MIN(ts),max(ts),
                                                GROUP_CONCAT(wf_jid,' '),
                                                GROUP_CONCAT(jobid||'['||substr(state,1,1)||']',' ') 
                                                FROM queuedjobs
                                                WHERE wf_id IN
                                                   (SELECT DISTINCT wf_id from queuedjobs
                                                    WHERE jobid IN (select jobid from updatedqueuedjobs) AND wf_id!='-' ) 
                                                GROUP by wf_id, wf_type, owner, account, mentor ORDER BY wf_jid
          sqldebug: 0
      archive:
        limit: max(lastts)-21d
    columns: 
      - { name: wf_id,           type: jobid_t           }
      - { name: wf_type,         type: shortstr_t        }
      - { name: owner,           type: owner_t           }
      - { name: account,         type: account_t         }
      - { name: mentor,          type: account_t         }
      - { name: firstts,         type: ts_t              }
      - { name: lastts,          type: ts_t              }
      - { name: wf_jid_list,     type: extralongstr_t    }
      - { name: jobid_list,      type: extralongstr_t    }

- table:
    name: workflows_spec
    options:
      update:
        sql_update_contents:
          vars: mintsinserted
          sql: DELETE FROM workflows_spec WHERE wf_id IN
                                        (SELECT DISTINCT wf_id from queuedjobs
                                            WHERE jobid IN (select jobid from updatedqueuedjobs) AND wf_id!='-' );
               INSERT INTO workflows_spec (wf_id,cnt_jobs_with_metric,numnodes_avg,load_avg,lastts_wf_spec)
                                                SELECT wf_id, COUNT(jobid), ROUND(AVG(numnodes), 2), AVG(load_avg), MAX(ts) 
                                                FROM joblist
                                                WHERE wf_id IN
                                                   (SELECT DISTINCT wf_id from queuedjobs
                                                    WHERE jobid IN (select jobid from updatedqueuedjobs) AND wf_id!='-' ) 
                                                GROUP by wf_id ORDER BY wf_jid
          sqldebug: 0
      archive:
        limit: max(lastts_wf_spec)-21d
    columns: 
      - { name: wf_id,                  type: jobid_t       }
      - { name: cnt_jobs_with_metric,   type: cnt_t         }
      - { name: numnodes_avg,           type: tasks_t       }
      - { name: load_avg,               type: load_t        }
      - { name: lastts_wf_spec,         type: ts_t          }

- table:
    name: queued_stat
    options:
      update:
        sql_update_contents:
          sql: DELETE FROM queued_stat;
               INSERT INTO queued_stat (owner,account,mentor,numqueuedjobs,qnumnodes_avg,qnh)
                                                SELECT owner,account,mentor,COUNT(jobid),AVG(numnodes),SUM(wall/3600.0*numnodes)  
                                                FROM queuedjobs
                                                GROUP by owner,account,mentor
          sqldebug: 0
      update_trigger:
          - alljobs_stat
    columns: 
      - { name: owner,           type: owner_t     }
      - { name: account,         type: account_t   }
      - { name: mentor,          type: account_t   }
      - { name: numqueuedjobs,   type: cnt_t       }
      - { name: qnumnodes_avg,   type: cnt_t       }
      - { name: qnh,             type: hour_t      }
      
- table:
    name: joblist_stat
    options:
      update:
        sql_update_contents:
          sql: DELETE FROM joblist_stat;
               INSERT INTO joblist_stat (owner,account,mentor,numjobs,numnodes_avg,nh)
                                                SELECT owner,account,mentor,COUNT(jobid),AVG(numnodes),SUM(wall/3600.0*numnodes)  
                                                FROM joblist
                                                GROUP by owner,account,mentor
          sqldebug: 0
    columns: 
      - { name: owner,           type: owner_t     }
      - { name: account,         type: account_t   }
      - { name: mentor,          type: account_t   }
      - { name: numjobs,         type: cnt_t       }
      - { name: numnodes_avg,    type: cnt_t       }
      - { name: nh,             type: hour_t       }
      
